automatic/palemoon/palemoon.ketarin.xml, automatic/palemoon/tools/Get-UrlFromFosshub.ps1, automatic/palemoon/tools/chocolateyInstall.ps1
This does require manually changing the __ketarin__ url's passed to `chocopkgup` both for `url` and `url64`
`url` `http://www.fosshub.com/genLink/Pale-Moon/palemoon-{version}.win32.installer.exe`
`url64` `http://www.fosshub.com/genLink/Pale-Moon/palemoon-{version}.win64.installer.exe`
I cannot adequately edit ketarin.xml because for some reason it does not contain the 32 bit url?
=> Updated Pale Moon for use with FossHub

packages/cyg-get/tools/cyg-get.ps1
This package is still using the FTP mirror that has been deprecated. See the https://chocolatey.org/packages/cygwin "Release Notes" for version 1.7.33.20150102.
=> fix cygwin mirror

automatic/smartftp/smartftp.nuspec
the .msi no longer contains the vcredist 2013 merge module. It is now a prerequisite.
=> added dependency: vcredist2013

packages/cyg-get/tools/cyg-get.ps1
The help text in cyg-get seemed to imply that support for installing multiple packages was not available.
This is however not true, it has been supported in cygwin setup.exe from the start, however the powershell script was parsing the arguments and removing the commas that separate the packages.
It works correctly with this patch.
It would be nice if  "choco install package1 package2 -source cygwin" was able to make use of this instead of launching a separate cygwinsetup every time... which is very slow and requires redownloading the package indexes every time.
=> cyg-get support for multiple packages to be installed in a single cygwinsetup session

automatic/smartftp/smartftp.ketarin.xml
url for the 32-bit msi file was pointing to the wrong (64-bit) msi.
=> SmartFTP: Fix 32-bit msi url

automatic/Firefox/tools/chocolateyInstall.ps1
The firefox package would successfully install on the system, but it would not report that it installed successfully because it would call `Get-ChildItem ` on the 64 bit uninstall directory which doesn't exist on 32 bit. This will avoid that check when on a 32 bit platform and will also only try to install the 32 bit version on a 32 bit platform.
=> Fix firefox install on 32 bit only systems

automatic/hostsman/hostsman.ketarin.xml, automatic/hostsman/hostsman.nuspec, automatic/hostsman/tools/chocolateyInstall.ps1
I get the following when I try to test:
```
The packages folder 'C:\code\mine\chocolateyautomaticpackages\name' does not exist. Perhaps you meant to specify the name as something else or you want to override the packages folder path setting of 'C:\code\mine\chocolateyautomaticpackages'. See chocopkgup.exe /help for details.
```
Could someone give a hint?
=> Created hostsman autopackage

automatic/smartftp/smartftp.nuspec
It should have been [min,] instead of (min,)
=> smartftp: fix incorrect version string.

automatic/flashplayerppapi/flashplayerppapi.ketarin.xml, automatic/flashplayerppapi/flashplayerppapi.nuspec, automatic/flashplayerppapi/tools/ChocolateyInstall.ps1, automatic/flashplayerppapi/tools/ChocolateyUninstall.ps1
- uses a different URL and source for $version, may work for the NPAPI and ActiveX packages
- Adobe did not release MSI installer for the PPAPI version (see https://forums.adobe.com/message/8108499#8108499), but the EXE installer supports silent setup. 
- reuses existing Flash icon
- tested installation and uninstallation on Win7 x64 with Chromium 49.0.2598.0 x64
My first PR to this project, please review
=> Add Flash Player PPAPI plugin for Opera and Chromium browsers

automatic/chromium/chromium.ketarin.xml
Changed the URL to be snapshots since Continuous has been decommisioned
=> Changed Continuous to Snapshots

automatic/keepassx/keepassx.ketarin.xml, automatic/keepassx/keepassx.nuspec, automatic/keepassx/tools/chocolateyInstall.ps1
@gep13 This is also an old static package turned autopackage because updates were requested.
This one should be straightforward because the download is direct (no mirrors) and the installer is just a .zip.
=> KeePassX autopackage

automatic/python2-x86_32/tools/chocolateyInstall.ps1, automatic/python2/tools/chocolateyInstall.ps1, automatic/python3-x86_32/tools/chocolateyInstall.ps1, automatic/python3/tools/chocolateyInstall.ps1
This allows pip installed programs that provide scripts to be accessible from the `cmd.exe`. This is how this works on Linux.
Example without this option:
```
pip3 install git+https://github.com/GoSecure/malboxes.git@pip-packaging#egg=malboxes
C:\...> malboxes -V
'malboxes' is not recognized as an internal or external command,
operable program or batch file.
```
Example with this option:
```
pip3 install git+https://github.com/GoSecure/malboxes.git@pip-packaging#egg=malboxes
C:\...> malboxes -V
malboxes-script.py 0.2.0dev
```
=> Added Python2 and Python3 Scripts dir to PATH using installer option (#111)

automatic/chromium/tools/chocolateyInstall.ps1
@gep13 Adding of a MD5 check for the downloaded file. Hopefully another audacity/classic shell issue won't be installed with the help of this check.
=> Proposed Change for MD5

ketarin/qbittorrent.ketarin.xml
Without the parens around `\w+` in the regex, the checksum value doesn't actually get captured for the variable. This fix should correct generation of the qBittorrent package.
Fixes #307
=> qBittorrent: ensure checksum gets captured

extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1
I don't know if this is something you want to do but it would probably save some user frustration with package maintainers that haven't updated download URLs to move away from ones that use the genLink web service.  I tested with the existing IrfanView (still uses genLink) and Audacity (does not use genLink) packages.
=> FossHub genLink URLs don't work and can be easily fixed without touching affected packages.

setup/Update-IconUrl.ps1
Added a script to easily update or add new icon url to nuspec files
Works for a single package, or passing without a name tries to update all packages which have an icon matching the package name.
=> Added Update-IconUrl script

.editorconfig, .gitattributes
Updated .editorconfig to get rid of the duplicated rules, as well as apply to all opened text files.
Updated .gitattributes file to normalize text files to crlf line endings, except for nuspec should normalize to lf line endings.
Added some basic (really basic) whitespace error checking when running `git diff`
=> (suggestion) Updated editorconfig and gitattributes

ketarin/GoogleChrome.ketarin.xml
Got into trouble when trying to install this package with a non-privileged user account.
It makes no sense to me that for 64bit admin is required, while on 32bit it isn't.
Please correct me if I'm wrong.
=> Set "admin=prefers" for 64bit too

manual/kb2999226/kb2999226.nuspec, manual/kb2999226/tools/chocolateyinstall.ps1
Fixed installation on:
- Vista/2008 SP2
- Evaluation editions (e.g. "Microsoft Windows Server 2012 R2 Datacenter Evaluation") and, possibly, other less-known named editions
New feature: detecting lack of the requisite Service Pack on Vista/2008/7/2008 R2 (and suggesting the Chocolatey package for 7/2008 R2 SP1)
Code cleanup:
- simplified control flow
- fixed indentation
=> kb2999226: fixed a few scenarios, simplified code

setup/Update-IconUrl.ps1
if the found icon hasn't already been added and committed
the Test-Path function incorrectly returned
the message from both `git add` and `git commit`
=> (Update-IconUrl.ps1) Fixed Test-Path returning add and commit messages

automatic/Firefox/tools/chocolateyUninstall.ps1
The variable `$uninstallPaths` gets overridden whatever the 64bits detection could be. Prevent that.
=> [Firefox] The 64bits detection is overridden in all cases

automatic/bluefish/bluefish.nuspec
not sure if chocolatey.org supports markdown abbreviations.
If not, they'll just be shown at the bottom of the description
=> (bluefish) converted html markup to markdown

automatic/smartftp/smartftp.nuspec
corrects the docsUrl url which was pointing to a different product (FTP Library).
=> smartftp: fix docsUrl

automatic/virtualbox/tools/chocolateyInstall.ps1
Looks like this needed to be $toolsPath.
This will need a new package fix version notation package version purshed. @majkinetor @AdmiringWorm 
cc @wget
=> virtualbox - variable missing

automatic/smartftp/smartftp.nuspec
SmartFTP now depends on vcredist2017.
=> smartftp: Depends on vcredist2017

automatic/smartftp/smartftp.nuspec
SmartFTP depends on KB2670838 on Windows 7, Windows Server 2008 R2.
=> smartftp: added KB2670838 dependency

manual/kb2670838/kb2670838.nuspec
- and not * is the correct meta character for a bullet.
=> kb2670838: updated description

automatic/audacity/audacity.nuspec, automatic/avidemux/avidemux.nuspec, automatic/codeblocks/codeblocks.nuspec, automatic/lightalloy/lightalloy.nuspec, automatic/mkvtoolnix/mkvtoolnix.nuspec, automatic/qbittorrent/qbittorrent.nuspec, extensions/chocolatey-fosshub.extension/chocolatey-fosshub.extension.nuspec, extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1
fixes #414
While debugging I noticed the referrer was being sent as a literal string - changed quotes.
Tested working with an update of my local audacity install on Win8.1.
I should say I'm not too familiar with PowerShell syntax, so please let me know if there's anything in the regex that might break it (in older PS versions etc).
=> (foshub.extension) Fixed fosshub parsing to find the download url in any attribute [PUSH chocolatey-fosshub.extension]

automatic/.gitignore, automatic/qbittorrent/qbittorrent.nuspec, automatic/qbittorrent/tools/LICENSE.txt, automatic/qbittorrent/tools/VERIFICATION.txt, automatic/qbittorrent/tools/chocolateyinstall.ps1, automatic/qbittorrent/tools/chocolateyuninstall.ps1, automatic/qbittorrent/update.ps1
qBittorrent uses GPL license which allows redistribution
I'm unsure about the creation of embedded packages, so any feedback would be appreciated.
/cc @gep13 @majkinetor @ferventcoder
=> Updated qbittorrent to embed installer

automatic/mkdocs/update.ps1
Not all releases from GitHub are necessarily pushed to the Python Package Index from where the Chocolatey Package will install the tool.
=> (mkdocs) Check PyPi for new package releases instead of GitHub

automatic/mkdocs-material/update.ps1
Not all releases from GitHub are necessarily pushed to the Python Package Index from where the Chocolatey Package will install the tool.
Fixes #481
=> (mkdocs-material) Check PyPi for new package releases instead of GitHub

automatic/poweriso/tools/chocolateyInstall.ps1, automatic/poweriso/update.ps1
I know it isn't optimal, but this was the only way I found that we could get the correct installer.
So unless someone gets the redistribution rights from the poweriso team, this I believe will have to do.
@gep13 @majkinetor 
could you guys test the install script, without changing the hash.
=> (poweriso) Changed to get the actual URL during install

automatic/git-lfs.install/git-lfs.install.nuspec, automatic/git-lfs.install/update.ps1, automatic/git-lfs/git-lfs.nuspec, automatic/git-lfs/update.ps1
The [current release notes link](https://github.com/git-lfs/git-lfs/blob/master/CHANGELOG.md) seems to be outdated (still at 1.5.0). Update release notes link to [GitHub Release Page](https://github.com/git-lfs/git-lfs/releases) and link directly to the current release.
=> (git-lfs*) Update release notes link for the current version

automatic/flashplayeractivex/update.ps1, automatic/flashplayerppapi/flashplayerppapi.nuspec, automatic/flashplayerppapi/tools/ChocolateyInstall.ps1, automatic/flashplayerppapi/update.ps1
@gep13 @AdmiringWorm 
This is just a small update to the Flash ActiveX  URL. The one that @AdmiringWorm changed it to is one of the round robin servers.
The rest is updating the Flash PPAPI package to use AU.
Also is it possible to make the updates to the Flash ActiveX & PPAPI be a incremental package update so that the new URL gets pushed to the public feed 😄. Right now they are both giving 404 errors
=> Adobe Flash Updates and PPAPI to AU status

automatic/git.install/git.install.nuspec, automatic/git.portable/git.portable.nuspec, automatic/git.portable/tools/chocolateyInstall.ps1, automatic/git.portable/update.ps1, automatic/git/git.nuspec
* (git.portable) Update filenames in chocolateyInstall.ps1
* (git.portabe) Add legal files to package
* (git) Remove BOM from .nuspec file
* (git.install) Add legal files to package
There's another issue with `git.install` during AU run: `Choco pack failed with exit code 1`
It works for me locally, is there a way to see the log and detailed error from the AU run somewhere?
Fixes #519
=> (git*) Fix issues with Git packages

automatic/git.install/git.install.nuspec, automatic/git.install/legal/VERIFICATION.txt, automatic/git.install/tools/chocolateyInstall.ps1
Update git.install after changes were pushed to chocolatey.org by AU but not commited to repository.
Or is there another way to have the files updated after a failing run?
=> (git.install) Update git.install after changes were pushed

automatic/git.install/tools/helpers.ps1
Revert logic of registry key detection back as it was before migration to core team repo and refactorings
Fixes #524
=> (git.install) Revert registry detection logic back as it originally was

automatic/cutepdf/cutepdf.nuspec, automatic/cutepdf/tools/chocolateyInstall.ps1
Chocolatey verifier service environment happens to have this service disabled. That's why cutepdf was failing.
Otherwise, I found out that uninstall wasn't silent and cannot be right now without an AutoIt script (see http://superuser.com/questions/580555/cutepdf-writer-problems-with-silent-uninstall). I didn't change a thing on this side.
=> Fixing an install issue on CutePDF Writer when print spooler service is not up and running

automatic/mkdocs-material/mkdocs-material.nuspec
Update dependency to mkdocs since 1.0.0 mkdocs-material requires mkdocs 0.16.0
As per [this comment](http://disq.us/p/1f8z4b3)
=> (mkdocs-material) Update min mkdocs version to 0.16.0

automatic/git-lfs.install/git-lfs.install.nuspec
git-lfs requires Git 1.8.5 or higher based on [this site](https://github.com/git-lfs/git-lfs#getting-started).
=> (git-lfs.install) Update dependeny to Git to 1.8.5

automatic/flashplayeractivex/update.ps1, automatic/flashplayerplugin/update.ps1, automatic/flashplayerppapi/flashplayerppapi.nuspec, automatic/flashplayerppapi/update.ps1, scripts/Get-Padded-Version.ps1
I've added a script to allow for easier access to padding the revision number of packages
which already uses 4-part version scheme.
The script also checks if the global variable 'au_force' is set to true and then increases the revision number based on what is shown as the latest in the corresponding nuspec file.
Also added to the flashplayer* packages to use those scripts (plans to add it to autoit packages as well).
I know I've not added any documentation of the script, and honestly didn't want to use time on it yet either.
/cc @pascalberger @gep13 @ferventcoder
=> (build) Pad version script

automatic/iTunes/tools/chocolateyInstall.ps1, automatic/iTunes/update.ps1
This fixes the invalid cast exception from Object[] to Version[], adds a link to the 32 bit version and points both 32 and 64 bit to the latest version
=> (iTunes) Update to latest version and fix install errors

extensions/chocolatey-core.extension/CHANGELOG.md, extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec, extensions/chocolatey-core.extension/extensions/Get-PackageParameters.ps1
Tested locally:
```
C:\src\github\chocolatey\chocolatey-coreteampackages\extensions\chocolatey-core.extension\extensions [fix_get_pp +0 ~1 -0 !]
λ  import-module .\chocolatey-core.psm1
C:\src\github\chocolatey\chocolatey-coreteampackages\extensions\chocolatey-core.extension\extensions [fix_get_pp +0 ~1 -0 !]
λ  get-packageparameters -Parameters "/foo:bar"
p:  /foo:bar
System.Collections.DictionaryEntry
Name                           Value
----                           -----
foo                            bar
C:\src\github\chocolatey\chocolatey-coreteampackages\extensions\chocolatey-core.extension\extensions [fix_get_pp +0 ~1 -0 !]
λ  get-packageparameters -Parameters "/foo2:bar"
p:  /foo2:bar
System.Collections.DictionaryEntry
Name                           Value
---- …
```
=> Allow numbers in flag names

automatic/git.install/git.install.nuspec, automatic/git/git.nuspec, manual/git-disable-gcm/git-disable-gcm.nuspec, manual/git-disable-gcm/tools/chocolateyInstall.ps1, manual/git-disable-gcm/tools/chocolateyUninstall.ps1, manual/git-disable-gcm/tools/helpers.ps1
Since the Git installer doesn't provide an option for not installing the GCM, I created a separate package which would disable GCM.
Disabling GCM while installing Git was originally requested in https://github.com/ferventcoder/chocolatey-packages/issues/149.
=> (git-disable-gcm) Add package for disabling Git Credential Manager

extensions/chocolatey-core.extension/CHANGELOG.md, extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec, extensions/chocolatey-core.extension/extensions/Get-AvailableDriveLetter.ps1
should return the next free drive letter
very useful for mounting iso-files from cocolateyinstall.ps1
=> (chocolatey-core.extension) New Helper 'Get-AvailableDriveLetter'

automatic/GoogleChrome/update.ps1
This will add padding to the revision number whenever the version is less than `56.0.2925`
**IMPORTANT merge using `[AU googlechrome]`, otherwise the padding is applied but the revision number is not incremented (but still be pushed since `56.0.2925.87 != 56.0.2925.87000`**
fixes #604
=> (googlechrome) Added revision padding

manual/visualstudiocode-disableautoupdate/tools/chocolateyUninstall.ps1, manual/visualstudiocode-disableautoupdate/tools/helpers.ps1, manual/visualstudiocode-disableautoupdate/visualstudiocode-disableautoupdate.nuspec
Current version of Visual Studio Code no longer seems to support `storage.json` file. Setting is therefore written to `settings.json`. Also default channel is now called `default` instead of `stable`.
Needs to be merged with `[PUSH visualstudiocode-disableautoupdate]` in message
=> (visualstudiocode-disableautoupdate) Update to latest Visual Studio Code version

automatic/smartftp/tools/chocolateyInstall.ps1
The new version requires Windows 8.1 (version = 6.3) or higher.
=> smartftp: add min os check

automatic/ccleaner/update.ps1, automatic/defraggler/update.ps1, automatic/speccy/update.ps1
All piriform packages was hanging on appveyor because they was missing the `-UseBasicParsing` flag when calling iwr.
=> (piriform-packages) Fixed update hanging issue

automatic/smartftp/smartftp.nuspec
The package requires Windows 8.1 or higher which makes the dependencies on the Pre-Windows 8.1 KB updates obsolete.
=> smartftp: removed KB dependencies

extensions/chocolatey-core.extension/CHANGELOG.md, extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec, extensions/chocolatey-core.extension/extensions/Get-AppInstallLocation.ps1, extensions/chocolatey-core.extension/extensions/Get-AvailableDriveLetter.ps1, extensions/chocolatey-core.extension/extensions/Get-PackageCacheLocation.ps1, extensions/chocolatey-core.extension/extensions/Get-PackageParameters.ps1, extensions/chocolatey-core.extension/extensions/Get-UninstallRegistryKey.ps1, extensions/chocolatey-core.extension/extensions/Get-WebContent.ps1, extensions/chocolatey-core.extension/extensions/Register-Application.ps1
It is hard to know how future expansion of a PowerShell function is
going to look. When a function is created, it is sometimes set with a
certain number of parameters. When not using `CmdletBinding` other
parameters can be passed and ignored. However, when `CmdletBinding` is
opted into explicitly or implicitly, it doesn't automatically allow for
additional ignored arguments to be passed through. In fact, it out right
errors when you pass more than the arguments that are present. It also
does not allow for splatting with more parameters than are used for a
particular function. This is suboptimal.
Fortunately, for functions with `CmdletBinding`, an additional catch all
parameter can be added to the end to see the other parameters and add
them as part of the function. This allows for future …
=> (GH-621) PowerShell functions - allow for ignored parameters and splatting

automatic/rukerneltool/rukerneltool.nuspec
See <https://github.com/chocolatey/chocolatey-coreteampackages/issues/146>.  Unfortunately, the license is just thrown into the Quick Start guide, which is available only in German.
=> (rukerneltool) Added missing licenseUrl

automatic/flashplayeractivex/update.ps1, automatic/flashplayerplugin/update.ps1, automatic/flashplayerppapi/update.ps1
I am eagerly waiting for the security updates from last week, so I took a shot.
Testing and reading through #628 I verified that `-UseBasicParsing` is the issue here because the `ParsedHtml` member does not exist. The XML based approach in this PR is a little cleaner imho and it's also what the people over at [autopkg](https://github.com/autopkg/recipes/blob/master/AdobeFlashPlayer/AdobeFlashURLProvider.py) use. Note that I am very new to chocolatey packages and I have no idea what `$padVersionUnder` is for :grin:
=> (flashplayer*): use XML download instead of HTML scraping

automatic/7zip.install/7zip.install.nuspec, automatic/7zip.install/tools/chocolateyInstall.ps1, automatic/7zip.install/tools/helpers.ps1, automatic/7zip.install/update.ps1, automatic/7zip/update.ps1
- Simplified installer
- Added shim (closes #549)
- Improved nuspec
- Removed 0 prefix on version
**Notes**:
- I removed helper because that check seems unnecessary - explorer is either running or not.
- This package can now be used as 7zip dependency instead of 7zip.portable
=> (7zip.install) improved and added shim

automatic/putty.install/legal/VERIFICATION.txt, automatic/putty.install/putty.install.nuspec, automatic/putty.install/tools/chocolateyInstall.ps1, automatic/putty.install/update.ps1, automatic/putty.portable/legal/VERIFICATION.txt, automatic/putty.portable/putty.portable.nuspec, automatic/putty.portable/tools/chocolateyInstall.ps1, automatic/putty.portable/update.ps1, automatic/putty/putty.nuspec, automatic/putty/update.ps1
This change only is effective if the user have chocolatey version 0.10.4 or later.
Anything sooner would still install the 32bit version.
fixes #646
=> (putty*) Adding support for 64bit putty installer/archive

automatic/GoogleChrome/GoogleChrome.nuspec, automatic/GoogleChrome/tools/chocolateyInstall.ps1, automatic/GoogleChrome/tools/helpers.ps1, automatic/GoogleChrome/update.ps1
The registry key we previously used for detecting an already installed 32bit installation have changed.
This PR fixes that, while also providing a fallback to check if the `nacl_irt_x86_32.nexe` do exist (this only exists on 32bit installations).
The check for the currently installed version had also broken, so this is also fixed.
fixes #667 
*MERGE with `[AU googlechrome]` in the title*
/cc @majkinetor @mattheyan
=> (googlechrome) Fixed the detection logic for 32bit installs

.appveyor.yml, scripts/Take-Screenshot.ps1, scripts/Test-RepoPackage.ps1, test_all.ps1
With this PR we can finally enable tests for updating, installing, uninstalling package(s) on appveyor when a PR is submitted.
The benefit of this is to notice early on when a package update/install/uninstall is failing (although, some positive failures may still occur).
One drawback though, is that the install/uninstall is only subjective and should still also be tested in a choco test environment.
Feel free to test these changes out by opening a PR at https://github.com/AdmiringWorm/chocolatey-coreteampackages/pulls that is based of the test-pkgs-on-pr branch.
@gep13 this is what I suggested to you on sunday, it also requires the Pull Request web hook to be enabled here on github (as I mentioned on gitter).
=> (build) Enabled running tests on pull requests

automatic/musescore/update.ps1
@gep13 @AdmiringWorm @pascalberger 
Update to take information from the main URL musescore.org .
This gets the latest version from the homepage. This will allow for future thanks to the regex.
=> (Musescore) Regex and releases update

automatic/7zip.install/tools/chocolateyInstall.ps1
Server Core images don't ship with explorer; this check prevents the installation failing because of that. Fixes #690
=> Add test for the existance of explorer.exe

automatic/mkvtoolnix/update.ps1
```
PS> '11.0.0' -gt '9.9.0'
False
PS> [version]'11.0.0' -gt [version]'9.9.0'
True
```
I'd describe myself as a novice with PS code, so this may not be an optimal or idiomatic approach. Please feel free to suggest a better alternative.
=> (mkvtoolnix) update.ps1: fix version detection

automatic/ruby/README.md, automatic/ruby/legal/LICENSE.txt, automatic/ruby/legal/VERIFICATION.txt, automatic/ruby/ruby.nuspec, automatic/ruby/tools/chocolateyInstall.ps1, automatic/ruby/update.ps1, icons/ruby.svg
- Was manual package
- Created embedded package with AU
closes #700
Closes at @ferventcoder 
- https://github.com/ferventcoder/chocolatey-packages/pull/238
- ~~https://github.com/ferventcoder/chocolatey-packages/issues/242~~
- https://github.com/ferventcoder/chocolatey-packages/issues/57 (gem works with this version)
/cc @ferventcoder
=> (ruby) migrated from ferventcoder

manual/vcredist2008/README.md, manual/vcredist2008/tools/chocolateyInstall.ps1, manual/vcredist2008/tools/chocolateyUninstall.ps1, manual/vcredist2008/update.ps1, manual/vcredist2008/vcredist2008.nuspec
closes #724
- Modernized
- Added README.md
- I didn't understand why double install in [original package](https://chocolatey.org/packages/vcredist2008) so I removed it.
- PR for removal on dtgm repo: https://github.com/dtgm/chocolatey-packages/pull/300 (looks like automatic but it probably doesn't work).
Push is required to point package to this repository but other changes are cosmetic.
=> Migrated from dtgm

automatic/ruby/tools/chocolateyInstall.ps1
Ruby now uses RubyInstaller2 as of 2.4, which means a new
way of installing and setting up the DevKit, which is built into
Ruby instead of having to install separately. Unfortunately 
that also means some new changes, as a window pops up 
after the install (thankfully in a non-blocking way) to ask the
user to select how they would like to have the devkit install
proceed. The switch `noridkinstall` prevents that from 
happening. As of any version of Ruby past 2.4.1-1, this will
be the default as well, but it's better to be explicit about 
specifying this behavior.
https://github.com/oneclick/rubyinstaller2/issues/43
https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install
Fixes #742
=> (ruby) Ensure unattended

automatic/sysinternals/update.ps1
As already mentioned in #756 and [here](https://chocolatey.org/packages/sysinternals#comment-3359914265), Microsoft updated archives and forgot to change html:
But http server didn't forget: `Last-Modified` HTTP header in response is correct:
```
Last-Modified: Wed, 14 Jun 2017 00:07:01 GMT
```
In this PR I fixed `update.ps1` to use `Last-Modified` HTTP header instead of `Updated` text.
=> (sysinternals) Last updated date builds from HTTP header

automatic/apache-httpd/apache-httpd.nuspec, automatic/apache-httpd/tools/helpers.ps1
I add -file64 $arguments.file64 to the helpers.ps1 and a dependency on chocolatey version 0.10.5 for apache-httpd package
=> (apache-httpd) add missing file64 and dependency for chocolatey

automatic/openssl.light/tools/chocolateyInstall.ps1
Added a Install-ChocolateyPath to add a path entry for the openssl bin directory
fixes #773
windows 7 testing using choco install -fdv .\openssl.light.nuspec
=> (openssl.light) set path variable in install

automatic/cygwin/tools/chocolateyInstall.ps1
Reversed the check condition for the architecture (32/64 bit).
The package is installing the 32bit binary in 64bit platforms and vice versa.
Simple condition negation, tested on command line.
=> (cygwin) The check for the architecture is reversed

automatic/screencloud/README.md, automatic/screencloud/legal/LICENSE.txt, automatic/screencloud/legal/VERIFICATION.txt, automatic/screencloud/screencloud.nuspec, automatic/screencloud/tools/chocolateyInstall.ps1, automatic/screencloud/tools/chocolateyUninstall.ps1, automatic/screencloud/update.ps1, icons/screencloud.svg
Adds [ScreenCloud](https://screencloud.net/), a FOSS screenshot and upload utility with plugin support, available for Windows, OS X and Linux.
The package is automated, and since I'm using it I will continue to keep it working.
Been using the software for a long time, even wrote some plugins for it, seemed right that it should be available here.
Tested the MSI installer, rest is drycoded for the PR hooks to test as I had limited time to set up the AU environment locally.
=> (ScreenCloud) Add package

automatic/visualstudiocode/update.ps1
Support for 64-Bit versions of Visual Studio Code.
The Visual Studio Code package should install the 64-bit version on 64-bit operating systems which will be [available starting from 1.15](https://code.visualstudio.com/updates/v1_14#_windows-64-bit-insiders)
Fixes #790 
Tested locally with updating to 1.14.2
=> (GH-790) Support Visual Studio Code 64-Bit version

automatic/virtualbox/tools/chocolateyInstall.ps1
```
λ  ls Cert:\CurrentUser\TrustedPublisher -Recurse
PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\TrustedPublisher
Thumbprint                                Subject
----------                                -------
E9A7896217C146DF9FC1F4B64D53B5AC7CF95DD6  CN=Arduino srl, O=Arduino srl, L=Scarmagno, S=Torino, C=IT
B9EAA034C821C159B05D3521BCF7FEB796EBD6FF  CN=Microsoft Corporation, OU=MOPR, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
AF124C200336F4248B03DEDCDA1AE51067F8DAF4  CN=Arduino LLC, O=Arduino LLC, L=Somerville, S=Massachusetts, C=US
A18084D4ADB468E20B5407ADFED44977B12D50EA  CN=U531296, OU=AFT-I, OU=AFT, OU=Users, OU=GDN, DC=ent, DC=off, DC=lsy, DC=pl
6AE09248DA3E30725EF8D91D5A985EE0F6150A18  E=support@adafruit.com, CN=Adafruit Industries, …
```
=> (virtualbox) Problem with Entrust cert store with roamin user

automatic/sourcetree/sourcetree.nuspec
Remove mention of SourceTree Auto Update Deactivation package since it only works for version 1.x
The SourceTree AutoUpdate Deactivation package only works for SourceTree 1.x. Related to #776
=> (sourcetree) Remove mention of SourceTree Auto Update Deactivation package

automatic/classic-shell/update.ps1
The mediafire link currently seems to be the first (and only) link to an `.exe` file beside the fosshub links which are already filtered out
Fixes #818
Tested locally
=> (classic-shell) Fix update

automatic/tor-browser/tools/chocolateyInstall.ps1
Post install of tor-browser, when trying to run it gives the error:
(title) Tor Browser profile Problem
(text) Tor browser does not have permission to access the profile. Please adjust your file system permissions and try again.
Expected Behavior
It should have permissions to run for at least the user account that installed the package.
Current Behavior
Package installer account does not have permission to run the program and files need to manually have permissions changed to
Possible Solution
add this to end of install script:
set NTFS modify file permissions to $toolsDir\tor-browser\ for user account that installed the package
$WhoAmI=whoami
$Acl = Get-Acl "$toolsDir\tor-browser"
$Ar = New-Object system.security.accesscontrol.filesystemaccessrule($WhoAmI,"Modify","Allow") …
=> (tor-browser) Set NTFS modify file permissions

automatic/mkdocs-material/mkdocs-material.nuspec, automatic/mkdocs-material/tools/ChocolateyInstall.ps1, automatic/mkdocs/mkdocs.nuspec, automatic/mkdocs/tools/ChocolateyInstall.ps1
It doesn't work behind the proxy:
```
mkdocs-material v2.0.4 [Approved]
mkdocs-material package files upgrade completed. Performing other installation steps.
Collecting mkdocs-material==2.0.4
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000274174F07B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /simple/mkdocs-material/
```
With CLI proxy:
```
> proxyc -FromSystem
$Env:ftp_proxy   = 'http://10.35.9.55:8080'
$Env:http_proxy  = 'http://10.35.9.55:8080'
$Env:https_proxy = 'http://10.35.9.55:8080'
--------------------------------------------------------------------------------------------------------------- …
```
=> (mkdocs*) added proxy handling

automatic/virtualbox/update.ps1
Implementation of streams on virtualbox throws an error when a stream is both available on download page and old downloads page (see https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/438b0e80e4443264f583e4ae1d781d09894e7485#errors).
While fixing this error, I'm also changing the order of streams in order to sort them from the most recent to the oldest one as recommended for packages with streams (see https://github.com/majkinetor/au#streams).
=> Fix error "Item has already been added" on virtualbox package

manual/visualstudiocode-disableautoupdate/tools/helpers.ps1, manual/visualstudiocode-disableautoupdate/visualstudiocode-disableautoupdate.nuspec
Use correct settings entry for disabling Visual Studio Code auto update.
Should be pushed on merging
In certain cases the wrong settings entry would be writting (`updateChannel` instead of `update.channel`)
Tested locally
=> (visualstudiocode-disableautoupdate) Use correct settings entry in all cases

automatic/git.install/CHANGELOG.md, automatic/git.install/README.md, automatic/git.install/tools/helpers.ps1, automatic/git/README.md
The `git` and `git.install` packages gained a new package parameter `/SChannel`, which configures Git for Windows to use the native Windows SSL/TLS library ("SChannel") instead of OpenSSL.
This change exposes an option of the native installer.
Implements #922.
Tested as follows:
0. preparation
- cpacked both packages
- published to personal MyGet feed ([git](https://www.myget.org/feed/jberezanski-chocolateypackages-dev/package/nuget/git/2.16.2.20180315), [git.install](https://www.myget.org/feed/jberezanski-chocolateypackages-dev/package/nuget/git.install/2.16.2.20180315))
1. test of the new feature
- on a test Windows 8.1 VM installed the packages by running
````
choco install git --version 2.16.2.20180315 --source https://www.myget.org/F/jberezanski-chocolateypackages-dev/api/v2 --params …
```
=> (git) Added ability to use Windows native SSL/TLS via package parameter

automatic/sourcetree/sourcetree.nuspec
Add dependency to .NET 4.7.1 as required by Sourcetree 2.5+
Sourcetree 2.5 changed system requirements to .NET 4.7.1
Tested locally
=> (sourcetree) Add dependency to .NET 4.7.1 as required by Sourcetree 2.5

automatic/nodejs.install/tools/chocolateyInstall.ps1
Removing Performance Counters and Event Tracing features by default due to installer ending prematurely.
Changed SilentArgs during install to skip Performance Counters and Event Tracing
Fixes installation not completing due to issue here:
https://github.com/nodejs/node/issues/4329#issuecomment-254825118
Packed locally and installed. Changes are minimal.
=> nodejs.install - Removing Performance Counters and Event Tracing

automatic/everything/update.ps1
Fetches es.exe from zip archive referenced on https://www.voidtools.com/ru-ru/downloads/#cli, instead of old, non-updated direct url https://www.voidtools.com/es.exe
Solves lack of [es.exe command line options](https://www.voidtools.com/support/everything/command_line_options/), such as colorized output
Tested by AU/appveyor in [my fork](https://ci.appveyor.com/project/galeksandrp/chocolatey-coreteampackages)
=> (Everything) Fix outdated es.exe command line tool

automatic/opera/README.md, automatic/opera/opera.nuspec, automatic/opera/tools/chocolateyInstall.ps1
I added support for two Opera installer arguments - one stops creating desktop shortcut for Opera and the other stops pinning Opera to Windows taskbar.
This change provides better expierence for users, because you can disallow installer from creating desktop shortcut for Opera or pinning it to taskbar, so user won't need to remove shortcut by himself each time.
I packed package with `choco pack` and tested the package with `choco install opera -s . --params "/NoDesktopShortcut /NoTaskbarShortcut"` and with `choco install opera -s .` (to see, if it didn't destroy standard installation) and just in case I also tested uninstalling it.
Tested on Windows 10, version 1803
=> (opera) Parameters for disabling desktop and taskbar shortcuts

automatic/opera/tools/chocolateyUninstall.ps1
I fixed issue #1054 - opera package can be silently uninstalled now.
It solves the one of the most important things - now package is fully silent, like it's recommended in guide lines.
Fixes #1054
I packed package, installed it and of course I tested uninstalling it and it now silently uninstalls.
Tested on Windows 10, version 1803
=> (opera) Fixed silent uninstall

CONTRIBUTING.md, README.md
Just thought it would be nice to have something mentioning which version of chocolatey we should support, I'm suggesting with this PR to support all versions of chocolatey that was made available in the last 12 months (unless a dependency on chocolatey is added), I also talked this over with @gep13 which seemed to agree.
Opening this in the form of discussion though, as I would love different opinions on the matter
/cc @majkinetor @pascalberger
=> (docs) Updated guidelines with choco version requirement

automatic/pdfcreator/pdfcreator.nuspec, automatic/pdfcreator/tools/chocolateyInstall.ps1, automatic/pdfcreator/tools/chocolateyinstall.ahk
* Added an AHK script to walk through the installer without user intervention.  
* Added necessary lines to the chocolateyinstall.ps1 to run the AHK.
* Added an autohotkey.portable dependency in the .NUSPEC (and re-arranged the elements to match the `choco new` template order which I find more logical).
The free, PDFCreator installer is no longer silent and now requires AutoHotKey (or similar) to install without user-intervention.  
Tested install and uninstall on Win7x64 and Win10(Ent1803)x64 and didn't notice any differences in the results from previous pdfcreator installs, *except:*
* The install still opens a URL (to push PDF Architect) on completion, but until there is a Capture-URL function to block installers that do this (something I'm working on), it will have to remain.
I have …
=> pdfcreator - fix non-silent installer

automatic/winscp.portable/update.ps1, automatic/winscp/update.ps1
Update release notes for winscp and winscp.portable package.
While release notes link for winscp.install package was already updated during AU update, the release notes link in the winscp and winscp.portable package was not.
Fixes #1107 
Tested locally
=> (winscp*) Update release notes on update

automatic/vagrant/tools/chocolateyinstall.ps1
Warn on plugin repair failure instead of failing the whole install since vagrant is technically installed correctly.
Instead of letting a failed exit code from `vagrant plugin repair` bubble out of `chocolateyinstall.ps1`, trap the error and issue a warning.
It is a known issue that sometimes vagrant plugin repair will fail after an upgrade, so we shouldn't fail the vagrant installation. See https://www.vagrantup.com/docs/cli/plugin.html for more information.
Fixes https://github.com/chocolatey/chocolatey-coreteampackages/issues/1099
Used "AU" package and ran `Test-Package` to verify that the vagrant installation succeeds even if plugin repair fails.  Also tested a when vagrant plugin repair does not error.
=> (vagrant) `vagrant plugin repair` failure is no longer fatal

automatic/skype/tools/chocolateyInstall.ps1
Using /VERYSILENT instead of /SILENT makes Inno Setup a bit quieter.
Users are understandably concerned about "mystery" install windows.
Manually downloaded https://endpoint920510.azureedge.net/s4l/s4l/download/win/Skype-8.30.0.50.exe, and ran installer with same parameters as in chocolateyInstall.ps1, except /SILENT was changed to /VERYSILENT. Installation succeeded and no installation windows appeared. Skype still (re)launches after installation.
Minor (largely cosmetic) change
=> (Skype) Changed InnoSetup /SILENT parameter to /VERYSILENT

manual/kb2670838/Tools/ChocolateyInstall.ps1, manual/kb2670838/kb2670838.nuspec, manual/kb2999226/kb2999226.nuspec, manual/kb2999226/tools/chocolateyinstall.ps1
Use module-qualified cmdlet name for Install-WindowsUpdate, to prevent accidental clash with the Install-WindowsUpdate command from BoxStarter. 
When using Boxstarter to install chocolatey packages, the Install-WindowsUpdate command with the same name from Boxstarter gets called. This installs ALL critical Windows updates by default, which is unwanted behavior. To work around this issue, please ensure the correct Install-WindowsUpdate is called. See [here the relevant boxstarter issue](https://github.com/chocolatey/boxstarter/issues/293). The same fix was implemented by jberezanski on the KB-packages he maintains, see [the discussion around this fix here](https://github.com/jberezanski/ChocolateyPackages/pull/54) and [the commit with his fix …
=> KB* packages - Work around Boxstarter issue

automatic/cygwin/tools/chocolateyInstall.ps1
Forcing Cygwin to install x86 version in a 64-bit system works, but later installing packages for Cygwin doesn't because the copied setup executable is wrong.
Adding parenthesis for calling the Get-OSArchitectureWidth function
I'm not an experienced PowerShell user or developer, but my guess is that the `-or` takes precedence. So we need to make the function call take precedence.
Only tested in my environment. Sorry for not complying here, but I lack time for it.
=> (cygwin): fix copied setup file

automatic/mixxx/tools/chocolateyInstall.ps1, automatic/mixxx/update.ps1
Do not embed Mixxx anymore as we have overtaken Cloudflare size limit
Fix #1179 
Local test on Windows 10 Pro: update, cpakc install and uninstall went smoothly
- x ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
=> Do not embed Mixxx anymore as we have overtaken Cloudflare size limit

automatic/mp3tag/README.md, automatic/mp3tag/legal/LICENSE.txt, automatic/mp3tag/legal/VERIFICATION.txt, automatic/mp3tag/tools/ChocolateyInstall.ps1, automatic/mp3tag/update.ps1
This makes the package embedded, so it resolves #866 for mp3tag. I added legal folder with verification file and license and of course, made the update script embed installers.
I can't try it on more old versions (cause apparently only the newest version's link is still active), but this fixes #1090. 
Also I added 2 optional install parameters:
`/NoDesktopShortcut` - Do not create desktop shortcut for Mp3tag
`/NoContextMenu` - Do not add Mp3tag to context menu
Package should be embedded if allowed and this app's license allows us to embed the installer. (#866)
Old installers are left behind on package upgrade and this fixes it (#1090)
Some people don't want their desktop to be cluttered by shortcuts and some may not want to clutter context menu, so I added those 2 parameters.
I checked …
=> (mp3tag) Embedded package, fix for #1090

automatic/docker-kitematic/tools/chocolateyInstall.ps1, automatic/docker-kitematic/tools/chocolateyUninstall.ps1
Add a symbolic link to allow the docker tray Kitematic menu option to work after installing Kitematic via the choco package.
The docker tray icon has a menu item 'Kitematic'. Clicking on this when Kitematic is not installed displays a message to install it to C:\Program Files\Docker\Kitematic. This package installs Kitematic into the chocolatey directory under C:\ProgramData\... 
This change adds a symbolic link which points from C:\Program Files\Docker\Kitematic\kitematic.exe to C:\ProgramData\Chocolatey\lib\docker-kitematic\tools\kitematic.exe
This allows the docker tray icon menu item to work when installing Kitematic from a choco package.
After installing Kitematic the user doesn't need to manually move or install into the %ProgramFiles%\Docker\Kitematic directory.
> choco pack
> …
=> Add/Remove a sym-link for docker tray Kitematic menu item

automatic/googlechromebeta/README.md, automatic/googlechromebeta/googlechromebeta.nuspec, automatic/googlechromebeta/tools/chocolateyInstall.ps1, automatic/googlechromebeta/tools/helpers.ps1, automatic/googlechromebeta/update.ps1
New package based on the existing GoogleChrome package that will install the Google Chrome Beta version side-by-side with the standard Google Chrome package.
Add new googlechromebeta package.
The beta version is useful for tests UIs to ensure they are compatible with the next release of Chrome.
Package has been built and tested locally, both installing and uninstalling.
=> RFP - Google Chrome Beta #494

automatic/vcredist140/README.md, automatic/vcredist2017/README.md
In the description an invalid link was found.
Replaced the invalid link with an valid link for both vcredist140 and vcredist2017.
Fixes an invalid link
I verified that the link was working.
=> (vcredist2017;vcredist140) Fixed 404 link for system requirements

automatic/graphviz/tools/chocolateyInstall.ps1, automatic/graphviz/tools/chocolateyUninstall.ps1
Adding circo, sfdp, and twopi layout engines to dot
Graphviz has many layout engines, and different ones are better suited to different graphs.
This simply duplicates an existing line for both installing and uninstalling.
=> graphviz: Add more layout engines to bin files

manual/vcredist2008/tools/chocolateyInstall.ps1
(vcredist2008) When this package is a dependency, it's install script sets the environment variable to force x86 installs.  So the dependent package then only installs the 32 bit version
Restore the original value of the environment variable that is being modified ($Env:chocolateyForceX86)
this fixes the ability to install packages that depend on vcredist2008 and reliably get the x64 version installed
I used choco pack to build the vcredist2008 package (i added a description to the nuspec file)
I then created a chocolatey source with only my newly built vcredist2008 package and saltminion 2019.2
With my change, salt installs the x64 version.
=> (vcredist2008) restore environment after installing 32bit vcredist2008

automatic/nuget.commandline/update.ps1
Add streams for 4.6.x, 4.7.x, 4.8.x and 4.9.x, which all contain newer versions which are not available through Chocolatey.
Several versions of NuGet are not available from Chocolatey, including the latest blessed version 4.9.4, since the version with the latest uploaded data is 4.6.4.
Run update.ps1 locally
=> (nuget.commandline) Add more streams for different 4.x versions

automatic/opera/tools/chocolateyInstall.ps1
1. Add /InstallAllUsers parameter to switch to a system-wide install.
1. Fix syntax errors where a value for an installer argument is provided; the help information obtained directly from the Opera installer (execute it with --help as the argument) indicates using an equals sign to join an argument with its value. I have noticed that some arguments noticeably do not work without the equals sign
This adds a sorely lacking command line argument for the installer: the ability to control the installation context (system-wide vs user-only).
This has been tested locally, by pulling and installing from a Nexus Repository Manager nuget repo which I use with chocolatey.
=> Opera: Add param for All Users installation. Fix syntax errors.

extensions/chocolatey-vscode.extension/CHANGELOG.md, extensions/chocolatey-vscode.extension/chocolatey-vscode.extension.nuspec, extensions/chocolatey-vscode.extension/extensions/Install-VsCodeExtension.ps1, extensions/chocolatey-vscode.extension/extensions/Uninstall-VsCodeExtension.ps1
Add support for installing extensions in insider builds and user level installations of Visual Studio Code.
There were user requests for supporting Insider builds for the Chocolatey extensions:
- https://github.com/pascalberger/chocolatey-packages/issues/115
- https://chocolatey.org/packages/vscode-docker#comment-4561079523
Tested locally with different combinations of Visual Studio Code installations.
=> (chocolatey-vscode.extension) Add support for insider builds and user level installers

automatic/clipgrab/update.ps1
Fixed /automatic/clipgrab/update.ps1 to remove AdWare.
The default ClipGrab executable (cgorg.exe) has third-party offers in it. This fix will use a clean version without third-party offers.
By using a clean version, the user won't have to uninstall any adware that may be installed using the default version. Issue #1309 
This will only change the end of the file, tested and it works.
=> (clipgrab) Fixed /automatic/clipgrab/update.ps1 to remove AdWare

automatic/gnupg/README.md
This corrects the package link in the `README.md` heading to point to: [https://chocolatey.org⁠/packages⁠/gnupg](https://chocolatey.org/packages/gnupg).
This doesn’t require a new publish, as the first heading is not included in the description.
The current link points to the old package ID ([gnupg‑modern](https://chocolatey.org/packages/gnupg-modern)).
=> docs(gnupg): Fix package link in README.md

automatic/curl/update.ps1
Due to not having the control of the order of the urls grabbed from
the website, we are sometimes grabbing the wrong version of the
64bit installer compared to the version we got for the 32bit installer.
This commit fixes that issue.
Reported on: http://disq.us/p/24kj4gl
=> (curl) fix incorrect version being grabbed

automatic/inkscape/tools/chocolateyInstall.ps1, automatic/inkscape/tools/chocolateyUninstall.ps1
This will add a shim for inkscape.exe to allow people to use inkscape directly from the terminal.
This pull request added a new `Install-BinFile` in `automatic/inkscape/tools/chocolateyInstall.ps1` which will allow Inkscape to be launched or to execute commands (https://inkscape.org/de/doc/inkscape-man.html) directly from the terminal. 
Also included in this commit is the `Uninstall-BinFile` located in the newly made `chocolateyUninstall.ps1`, which ensures that the shim is removed when uninstalling inkscape.
I was unable to test this in the Chocolatey Test Environment, but since this is a rather small addition it shouldn't break any stuff.
This is especially useful for people who need to modify/change vector graphics without a GUI or to convert from AI (Illustrator file format) to SVG. …
=> (inkscape) Add shim to inkscape.exe (#1344)

automatic/virtualbox/tools/chocolateyUninstall.ps1
Fixes #1353
Package's uninstallation process was failing when there were no extensions installed.
I tested the updated package in chocolatey test environment.
=> (virtualbox) Uninstall no longer fails when there are no extensions installed

deprecated/packages/gnupg-modern/gnupg-modern.nuspec
This creates a deprecated stub-package for #1333 according to https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package.
Because @gep13 wouldn’t approve [gnupg](https://chocolatey.org/packages/gnupg) until after [gnupg‑modern](https://chocolatey.org/packages/gnupg-modern) was deprecated.
- [Original Repository](https://github.com/jtcmedia/chocolatey-packages)
- [Open Issues](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues) *Add the different issues underneath, and tick those that are fixed in this PR*
---
review?(@gep13, @jtcmedia,@majkinetor, @wget)
=> Deprecate `gnupg‑modern`

automatic/vagrant/tools/chocolateyinstall.ps1, automatic/vagrant/vagrant.nuspec
Some plugins like vagrant-vbguest needs an update to be compatible with the new Vagrant version.
Just added `vagrant plugin update` as post task to the Vagrant update.
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1358
Manually tested.
- [Open Issues](https://github.com/chocolatey/chocolatey-coreteampackages/issues/1358)
=> (vagrant) Update plugins after software update

automatic/mattermost-desktop/update.ps1
Mattermost URL parsing was not sanitized enough leading in Posh .NET WebClient to complain with a `Illegal characters in path.` exception.
See above
Tested locally with AU
=> Sanitize URL properly to allow download with Posh .NET WebClient

automatic/freecad/freecad.nuspec, automatic/freecad/tools/chocolateyInstall.ps1
Manual update, automatic update will work again when a version like "0.19.x" will be released.
Until now, the published version is a mix between the major version and build number so to have again a conventional versioning with the update script, it needs to manually update this package until a version greater or equal to 0.19 is released by Freecad.
```
RemoteVersion : 0.18.4
NuspecVersion : 0.18.16131
```
Manual update of Freecad. New version has been released 8 days ago and the current update script can't update Freecad until a version greater or equal to 0.19 is released.
- [x ] My code follows the code style of this repository.
=> (freecad) manual update

extensions/chocolatey-core.extension/CHANGELOG.md, extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec, extensions/chocolatey-core.extension/extensions/Remove-Process.ps1
This changes the operator used in `Remove-Process` from `-notin` to `-notcontains`.
This fixes fixes #1373 and provides PSv2 compatibility again to the core extension.
Locally on a PSv2 Virtual Machine.
=> (chocolatey-core.extension) Fixed compatibility issue with PSv2

automatic/php/tools/chocolateyInstall.ps1
The extension_dir value in the default php.ini files has changed from
`; extension_dir = "ext"` to `;extension_dir = "ext"`. The replace regex
now matches both formats.
The current method does not actually configure the `extension_dir` value in PHP 7.3.0 upwards
Tested locally in au
=> (php) Fix extension_dir configuration

automatic/smartftp/smartftp.nuspec
I have removed a stale BugTrackerUrl form the nuspec file. I could not find a link on their website to submit bugs.
`The BugTrackerUrl element in the nuspec file should be a valid Url. Please correct this More...` 
The validation is failing for this package
=> (smartftp) removed stale BugTrackerUrl (#1407) [AU smartftp:9.0.2733.0]

automatic/winscp.install/winscp.install.nuspec, automatic/winscp.portable/winscp.portable.nuspec, automatic/winscp/winscp.nuspec
The ProjectUrl was referring to SourceForge, but the page no longer exists. The source code is now on GitHub.
WinSCP 5.17.1 is held in moderation because the ProjectUrl is invalid. This change should resolve that issue.
The URL is valid and is the location of WinSCP source.
=> (WinSCP) Update ProjectSourceUrl

automatic/brave/tools/chocolateyInstall.ps1, automatic/brave/tools/helpers.ps1
Checking the already installed version before downloading the nuspec version.
If the already installed version is greater equal than the nuspec version, then skip installing the outdated version.
Brave is updating automatically faster than the Chocolatey repository.
If upgrading to the outdated version, then an error occurred. (Exit code was '-2147219198')
Some reports about it are available on the package page.
Tested locally.
=> (brave) fix the '-2147219198' error

automatic/keeweb/keeweb.nuspec, automatic/keeweb/legal/LICENSE.txt, automatic/keeweb/legal/VERIFICATION.txt
The verifier failed for KeeWeb as upstream changed the link to the LICENSE file. Now fixed.
Fix the license file URL
Build, installed an uninstalled the package on Windows 10 and Windows 7 ESU.
=> Fix KeeWeb license URL

automatic/firefox/Readme.firefox.md, automatic/firefox/Readme.firefoxesr.md
Replace angle brackets in Readme with capitals because angle brackets are not displayed correctly on chocolatey.org/packages
See #1458
This is purely cosmetically, no functionality change
Any better suggestion is welcome!
=> (Firefox) replace angle brackets with capital letters

automatic/k9s/legal/VERIFICATION.txt, automatic/k9s/tools/chocolateyinstall.ps1, automatic/k9s/update.ps1
Remove 32bit version support
update.ps1 script no longer works because new releases does not contains the 32 bit exe file.
https://github.com/derailed/k9s/releases/tag/v0.19.3
contains minimal changes tested locally
=> (k9s) Remove 32bit version support

automatic/msys2/legal/VERIFICATION.txt, automatic/msys2/msys2.nuspec, automatic/msys2/tools/helpers.ps1, automatic/msys2/update.ps1
After latest changes in msys2 chololatey package is not installing anymore
Fixes #1479 
In docker container with chocolatey installed:
```
choco pack
choco install chocolatey-core.extension
choco install msys2.20200517.0.0.nupkg
```
Dockerfile
```
FROM mcr.microsoft.com/windows:1909
ENV chocolateyUseWindowsCompression false
RUN powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && rmdir /s/q "%temp%" && mkdir "%temp%" && del /q %ProgramData%\chocolatey\logs\*
RUN choco feature enable -n=allowGlobalConfirmation && rmdir /s/q "%temp%" && mkdir "%temp%" && del /q %ChocolateyInstall%\logs\*
RUN choco feature disable -n=showDownloadProgress && rmdir /s/q "%temp%" && mkdir …
```
=> (msys2) update to working version

automatic/nomacs.portable/update.ps1, automatic/nomacs/update.ps1
nomacs/nomacs.portable: the previously used page to check for new releases doesn't seem to be updated by the software maintainers any more, directly use the GitHub release page instead.
verified it actually get's the correct version by manually running the iwr & regex - link match in powershell.
=> (nomacs)/.portable - use github release page instead of outdated nomacs website

automatic/keeweb/update.ps1
This package filtered on 64.exe, but arm64.exe is first so the package isn't working
I've made the change for it to work.
Changed (href -match '64.exe$') into href -match 'x64.exe$'
the package wasn't passing the verification because of the wrong system type
Tested on my computer
=> (Keeweb) Update keeweb updater broked because of the new arm64 version

automatic/keepassxc/keepassxc.nuspec, automatic/keepassxc/legal/VERIFICATION.txt, automatic/keepassxc/tools/chocolateyInstall.ps1, automatic/keepassxc/update.ps1
Keepassxc 2.6 beta shouldn't have been pushed. Prevent that and use the GitHub API for proper detection.
See above.
On local Windows 7 and Windows 10 dev based environment.
=> (keepassxc) Ensure beta versions are not detected by using GitHub API

automatic/keeweb/tools/chocolateyUninstall.ps1, automatic/keeweb/update.ps1
Keeweb added an arm 64 version of the exe which was breaking the x64 detection. Fix that.
Take the opportunity to use the GitHub API rather than the HTML parsing.
On local Windows 7 and Windows 10 dev based environment + the test instance of the verifier.
=> Fix keeweb

automatic/flightgear/tools/chocolateyInstall.ps1, automatic/flightgear/update.ps1
Updated auto-update script
Now tracking stable releases scraping the homepage
Newer releases are no longer uploaded to the Windows folder on ftp's since Nov2016, so the updater got stuck.
Copy-Paste parts of the script on the W10 PowerShell prompt to ensure output validity.
Script as a whole not tested.
```
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
````
=> (FlightGear) Update update.ps1

automatic/cutepdf/tools/chocolateyInstall.ps1, automatic/cutepdf/tools/chocolateyUninstall.ps1
Adds a uninstalls script because the chocolatey autouninstaller does not find a
silent switch to make the uninstall silent. 
Add code to uninstall old versions of cutepdf, because the installer requires older version(s) to be uninstalled before a new version can be install. If an older version of cutepdf is installed, the new installer will exit with code 1.
Allows CutePDF to be silently uninstalled.
Also
Fixes: #1500 
Tested install, uninstall, and upgrade in the chocolatey test environment and on a machine with windows 10 2004 and chocolatey 0.10.15
=> (CutePDF) Add uninstall script and fix install exit code 1

automatic/freecad/tools/helper.ps1
This will allow this package to pass verification
@AdmiringWorm @majkinetor @gep13 @pascalberger 
This package [.portable](https://chocolatey.org/packages/freecad.portable) has been stuck in verification limbo since April 19th, 2020. I had asked if this or that should be done to get this package to pass verification. The answer was always not familiar with it will get back to you.
The use of the Get-Version cmdlet causes grief if the package AU is not installed. Since all Core Packages have `$ErrorActionPreference = 'Stop';` This was causing a **_HARD Stop_** and thus causing the verification to Fail.
The cmdlet of `Get-Command` has `-erroraction` as a choice of parameters. Setting this to Continue will allow the package to complete the if..else lines
- [Original …
=> (freecad) adding erroraction continue

automatic/1password/1password.nuspec, automatic/1password/tools/chocolateyInstall.ps1, automatic/1password/update.ps1, automatic/1password/update_helper.ps1
The new installer requires --silent to be used for the installation of 1Password 7
Also .NET framework 4.7.2+ is now required for 1Password 7.
Fixes #1186
Tested on chocolatey-test-environment
=> (1password) Fixed silent installation

automatic/calibre/update.ps1
Changes the $releases page in the AU script to the page for the 5.x Calibre releases. 
Updates the version in the error checking regex to check for 5 rather than 4.
Allows the Calibre package to update to 5.x releases
Ran the update script on my local Powershell 5 machine.
Manually checked the changes made by the update script, and tested the updated package in the test environment.
=> (Calibre) Update AU script for 5.x releases

automatic/ffmpeg/tools/chocolateyInstall.ps1, automatic/ffmpeg/update.ps1
- Currently, FFmpeg upstream https://ffmpeg.zeranoe.com/builds has gone down forever. #1552 
- Now, the updater looks for the build from https://www.gyan.dev/ffmpeg/builds/ instead of previous upstream. I got it found on its official website https://ffmpeg.org/download.html#build-windows . Also, there is a problem. It looks like they provide x64 bit zip files. Another alternative was https://github.com/BtbN/FFmpeg-Builds/releases but the problem there is that it provides daily builds and package needs to updated daily. Not worth it.
Without it `ffmpeg` will never be upgraded.
Fixes #1552
=> (ffmpeg) Fix updater with new Upstream

automatic/youtube-dl/youtube-dl.nuspec
Fixes to package URLs to point to main dev's working Git repo, to fix InvalidUrlProvided errors at validation.
Fixes errors in nuspec package caused by currently offline GitHub URLs. https://chocolatey.org/packages/youtube-dl/2020.11.12
URLs tested.
=> (youtube-dl) Switch to current GitLab working repo in nuspec package

automatic/mpc-hc-clsid2/update.ps1
I have made it so that MPC-HC-CLSID2 will let the AU get the latest stable releases without outputting an error.
This fixes the AU giving an error every time it runs because MPC-HC-CLSID2 does not have conventional update names.
I have run it locally along with a private PR to ensure the bot will run correctly. They both were successful.
=> (mpc-hc-clsid2) AU Fix for Stable Releases

automatic/keepassxc/tools/chocolateyInstall.ps1, automatic/keepassxc/update.ps1
Switches Keepassxc to `Install-ChocolateyInstallPackage` from `Install-ChocolateyPackage`
Install-ChocolateyPackage "downloads" the package before install, creating an extra copy in temp and taking longer on install.
Install-ChocolateyInstallPackage is more efficient as it installs directly, 
Tested on a Windows 10 machine, and in the test environment.
AU update script adjusted according to the changes and tested.
=> (Keepassxc) switch to install-chocolateyinstallpackage

automatic/protoc/protoc.nuspec, automatic/protoc/tools/chocolateyBeforeModify.ps1, automatic/protoc/tools/chocolateyinstall.ps1, automatic/protoc/update.ps1
Fixed the google protocol buffer library staled automatic update problem (issue #1588). Also removed explicit shimming generation and removal as @majkinetor and @AdmiringWorm suggested in pull request #1345.
1. I did not use streams, because, compared to the chromium package, this one relies on the github release page and the prerelease version is not guaranteed to even exist within the first few pages, and I feel like it might be tricky to handle these "nullable" values in streams. As a compromise, I am now limiting the download link regex match to search for stable versions only.
2. I removed the call to `Install-BinFile` and the script `chocolateyBeforeModify.ps1` as suggested in pull request #1345.
Fixes issue #1588.
Tested locally.
=> (protoc) fix the staled version problem

automatic/youtube-dl/youtube-dl.nuspec
Changes various URLs in the nuspec back to the youtube-dl official yt-dl repository links. 
The repository was taken down in response to a DMCA notice but has been put back up. 
The URLs were changed in #1562 to point to a temporary mirror of the repository, but that mirror has been taken down.
Some of the current URLs are broken because they pointed to a temporary mirror which has been taken down.
So the package is not passing the validator
Ran through CNC, installed locally and in the chocolatey test env.
=> (Youtube-dl) Revert URLs back to official repo now that it is back up.

automatic/autohotkey.portable/tools/chocolateyInstall.ps1
This commit encloses `Get-OSArchitectureWidth 64` with parentheses and removes an unnecessary space.
This commit ensures that the 32-bit version of AutoHotkey v2 can be installed on an x64 environment.
=> (autohotkey.portable) Fix if condition and typo

automatic/thunderbird/thunderbird.nuspec
Verification fix - thunderbird package has been stuck in "waiting for maintainer" for alsmost two weeks
The URL to the thunderbird developer docs has changed.
With this change the thunderbird package should build and verify again
Tested by opening the new url in a webbrowser, should have no influence on any part of the actual installation.
THere's no actual code change here - only one changed URL in the spec file for thunderbird.
=> FIX: Thunderbird Dev Docs URL was changed

CONTRIBUTING.md, README.md
Fix links to Chocolatey docs
The Contributing and Readme files had a broken link (to the Quick Start guide), I've fixed that and also updated the other links to Chocolatey docs in those two files to avoid an unnecessary redirect. (The documentation has moved from chocolatey.org/docs to docs.chocolatey.org)
Links tested manually
=> (no package) Fix links to Chocolatey docs

automatic/mkdocs/mkdocs.nuspec
see meta section in https://pypi.org/project/mkdocs/, mkdocs doesn't work with `python<=3.5`.
If a user has only python2 installed it will create an error because mkdocs support only `Python >=3.5`. This PR changes the minimum to 3.5.
=> (mkdocs) change minimum python version to 3.5

automatic/freecad/update_helper.ps1
I've changed the regex for getting 64bit executable filename from github releases.
`... (\-[0-9])? ...`
It seems that the freecad team decided to append `-1` to the filename of the executable.
I've tested this on my local windows 10 (20H2) pc.
```
PS E:\git\chocolatey-coreteampackages\automatic\freecad> .\update.ps1
freecad - checking updates using au version 2020.11.21
*** Stream: portable ***
URL check
https://github.com/FreeCAD/FreeCAD/releases/download/0.19.1/FreeCAD-0.19.1.a88db11-WIN-x64-portable-1.7z
https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-portable.7z
nuspec version: 0.19.1
remote version: 0.19.1
No new version found
*** Stream: stable ***
URL check
https://github.com/FreeCAD/FreeCAD/releases/download/0.19.1/FreeCAD-0.19.1.a88db11-W …
```
=> (freecad) adds support for new installer name

manual/vcredist2008/tools/chocolateyInstall.ps1, manual/vcredist2008/vcredist2008.nuspec, manual/vcredist2010/tools/chocolateyInstall.ps1, manual/vcredist2010/update.ps1, manual/vcredist2010/vcredist2010.nuspec
These are similar changes as requested for vcredist2005 in https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1657.
Additionally, vcredist2008 is held in moderation due to invalid bugTrackerUrl.
Manually, in a Windows Server 2019 VM.
=> (vcredist2008, vcredist2010) Update metadata and prevent double install of 32-bit version

.appveyor.yml
This commit updates the token being used for AppVeyor with the new PAT format.
GitHub suggested regenerating this token to take advantage of the [new token formats](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/). Though not breaking anything, it seemed useful for documentation.
N/A
=> (maint) Updates AppVeyor github_api_key

automatic/k9s/tools/chocolateyinstall.ps1, automatic/k9s/update.ps1
From 0.24.10 onwards, k9s has changed the format of the asset files. See https://github.com/derailed/k9s/releases/tag/v0.24.10. Because of this, the automatic update has been failing. See https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#k9s
This PR updates the update script to reflect the asset rename
I noticed the chocolatey didn't have the latest version of k9s and on investigating I found that the error is due to the asset rename. Pre 0.24.10, the asset was called `k9s_Windows_x86_64.tar.gz`. From 0.24.10 onwards it is called `k9s_v0.24.10_Windows_x86_64.tar.gz`. Note the version name in the file. The PR solves this by generating the asset file name including the version name.
I have tested this locally by running `update.ps1` and it is able to fetch the latest file …
=> (k9s) Updated K9s update script to reflect changes to asset rename

.github/CODEOWNERS, automatic/octave.portable/README.md, automatic/octave.portable/octave.portable.nuspec, automatic/octave.portable/tools/chocolateyBeforeModify.ps1, automatic/octave.portable/tools/chocolateyInstall.ps1, automatic/octave.portable/tools/chocolateyUninstall.ps1, automatic/octave.portable/update.ps1
The octave.portable package was not operating correctly.  The desktop icon and
the shims were not launching the package correctly following an install and
there was no icon available for the package.
This change is required to bring the package to currency given changes in the
directory structure and launch parameters. Without these changes the package
does not operate as expected.
The issues with the package were caused by updates to the required
parameters and directory structure for the package and an incorrect shim
which did not configure an envrionment appropriately being installed.
To address these issues a number of changes were made:
* Update desktop icon parameters - desktop icon not launching Octave
as `--force-gui` is no longer a supported parameter
* Repoint shim from …
=> (octave.portable) Update package to launch correctly with current versions

automatic/1password/1password.nuspec, automatic/1password/Readme.md
Updated the 1Password name in the description to match the spelling of the name on the official website.
So that the name in the description on Chocolatey Community matches the official name.
I haven't tested it in any way, but my changes concern only the description, so there should be no problems.
=> (1password) Update 1Password name

automatic/smartftp/smartftp.nuspec
The latest version of SmartFTP no longer requires vcredist:
"The Visual C++ Redistributable Package (vcredist) is no longer installed."
https://www.smartftp.com/en-us/changelog/1
Manual
=> smartftp - removed vcredist dependency

automatic/smartftp/tools/chocolateyInstall.ps1
Version 10.x of the product requires Windows 10 Version 1607 or higher:
"Windows 10 1607 (Anniversary Update) or newer is required."
Reference: https://www.smartftp.com/en-us/changelog/1
=> smartftp: Minimum OSVersion is Windows 10 Build 14393

automatic/thunderbird/thunderbird.nuspec
docsUrl now points to https://developer.thunderbird.net
The Thunderbird docs have moved off MDN after the recent reshuffle there. The old docsUrl is now 404ing,
which causes the automatic updates of Thunderbird on Chocolatey to fail verification. This change fixes the
'The DocsUrl element in the nuspec file should be a valid Url' error during verification.
Not tested, but only an update to a string in .nuspec file
=> (Thunderbird) Update docsUrl to new location

automatic/firefox/tools/helpers.ps1
The current method of detecting system locale is not robust enough. Take "zh-HK" as an example, it should be fallback to "zh_TW", but this package fallback "zh-HK" to "en-US". This commit detects fallback locale by sending `Accept-Language: zh-HK` header to https://www.mozilla.org/ to get Mozilla fallback locale.
=> (firefox) Improve the method of detecting system locale

automatic/k9s/tools/chocolateyinstall.ps1, automatic/k9s/update.ps1
This is basically a continuation of already existing PR #1685. If this gets approved and merged, that another one can be removed (I do not want to step on anyone's toes though). Also solves #1712.
k9s has changed the format of the asset files in version 0.24.10. The maintainer later then decided to revert back that change. This PR handles both types of asset names in case the maintainer decides to change the name again.
Pre 0.24.10, the asset was called k9s_Windows_x86_64.tar.gz. On 0.24.10 onwards it was called k9s_v0.24.10_Windows_x86_64.tar.gz and in 0.24.11 to 0.24.15, they have reverted back to k9s_Windows_x86_64.tar.gz. The PR solves this by generating the asset file name first by excluding the version name and on failure including the version name.
Tested this locally by running …
=> (k9s) Use new structure for url

automatic/autohotkey.portable/tools/chocolateyInstall.ps1
In AutoHotkey v2.0-a135-b66a8739, the executable files "AutoHotkeyU32.exe" and "AutoHotkeyU64.exe" have been renamed to "AutoHotkey32.exe" and "AutoHotkey64.exe". This commit ensures a flawless installation and usage.
fixes #1663
=> (autohotkey.portable) Consider new filenames for v2

automatic/git.install/README.md, automatic/git.install/git.install.nuspec, automatic/git.install/tools/chocolateyInstall.ps1, automatic/git.install/tools/helpers.ps1
Replace the usage of registry keys to set the options to the `/o:<key>=<value>` parameters as indicated in [this comment](https://github.com/git-for-windows/git/issues/2912#issuecomment-734281023).
Add new parameters requested in https://github.com/chocolatey-community/chocolatey-packages/issues/1702 (Use Windows' default console window is already the option `WindowsTerminal` of the package), https://github.com/chocolatey-community/chocolatey-packages/issues/1692 and https://github.com/chocolatey-community/chocolatey-packages/issues/1452.
This change avoids messing with the registry and provides requested parameters.
As a user of chocolatey and this package, I needed some of these options.
I have tested the new parameters of the package in a brand new w11 VM.
=> (git) Add parameters

automatic/php/php.nuspec
This PR fixes the `projectSourceUrl` in `php` package.
PHP now uses the GitHub repository [`php/php-src`](https://github.com/php/php-src), and the use of [`git.php.net`](http://git.php.net) has been discontinued.
This should fix the package validation error here - https://community.chocolatey.org/packages/php/8.1.0
The updated URL in this PR is valid and is the location of PHP source.
=> (php) Fix php projectSourceUrl

automatic/thunderbird/tools/chocolateyInstall.ps1
During installation of Thunderbird, and if the application was running the installation would fail due to there being multiple paths being passed in when we start the process. This pull request changes that to make sure that we only pass in the first unique path that is found from the running processes.
The reason for the multiple paths is due to there being more than 1 thunderbird process when the application is running.
To make the package work when thunderbird is running.
1. Create a fix version of the package by running `.\test_all.ps1 thunderbird`
2. Set up or restore a snapshot of the chocolatey test environment.
3. Install a previous version of thunderbird (must be lower than the actual version of thunderbird. `choco install thunderbird --version 91.3.1`).
4. Launch thunderbird
5. …
=> (thunderbird) Throws error if Thunderbird was running when installation was started

automatic/ffmpeg-full/README.md, automatic/ffmpeg/README.md
added links to descriptions of which libraries are included for ffmpeg packages
For the ffmpeg and ffmpeg-full packages, in the readme, I added links to the site that shows the libraries included for each
* Currently, packages refer to an "essentials" and "full" build, but in the upstream project there is no such thing as either of those. Long-time users of ffmpeg could/do look at it wondering what either of them mean.
* fixes https://github.com/chocolatey-community/chocolatey-packages/issues/1765
- ~[ ] The added/modified package passed install/uninstall in the chocolatey test environment.~
=> Ffmpeg libraries

automatic/msys2/README.md
I've updated the README.md file for msys2. These should flow into the 'description` in the .nupspec file.
Note that how we add this info, the message and the formatting are all up for debate. I wanted to get something up here for discussion. Once agreed, I feel we should require any updates to a package to add this to the README files (perhaps by adding it to https://github.com/chocolatey-community/chocolatey-packages/issues/1754).
Questions are still being asked via Disqus for many packages. As Disqus is generally not responded to it makes sense to clarify where questions and issues should be raised. Going forward we should add this to all packages.
I haven't tested this as it was an update to Markdown.
N/A.
=> (msys2) Clarify where to raise issues

automatic/libreoffice-streams/README.fresh.md, automatic/libreoffice-streams/README.md, automatic/libreoffice-streams/README.still.md
I've updated the README*.md files for libreoffice. These should flow into the 'description` in the .nupspec file.
Note that how we add this info, the message and the formatting are all up for debate. I wanted to get something up here for discussion. Once agreed, I feel we should require any updates to a package to add this to the README files (perhaps by adding it to #1754).
Closes #1803.
Questions are still being asked via Disqus for many packages. As Disqus is generally not responded to it makes sense to clarify where questions and issues should be raised. Going forward we should add this to all packages.
I haven't tested this as it was an update to Markdown.
=> (libreoffice) Clarify package update lagging behind software release and where to raise issues / questions

.github/PULL_REQUEST_TEMPLATE.md
Added a checkbox into the PR template to confirm that the package description length.
The package description has a maximum length of 4000 chars and if it above that length the package will error when being pushed. If somebody submits a PR that updates this field, we should remind them to check it's length.
It hasn't. This is a change to markdown.
N/A.
=> (maint) Add check of package description length

automatic/blender/Readme.md
Updated the description notes to warn that when multiple versions of Blender are installed, the package will fail to uninstall.
Fixes #1795 
The installer allows multiple versions to be installed and Chocolatey doesn't know which one to uninstall, so it fails. In the [comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1795#issuecomment-1040041182) it was agreed that it wasn't desirable for all versions to be uninstalled.
It hasn't. This is an update to the description field.
N/A
=> (blender) Uninstall fails when multiple software versions installed

automatic/brave/README-beta.md, automatic/brave/README-release.md, automatic/brave/update.ps1
Fixed the detection of the Brave browser software versions.
Fixes #1791 
The automation for detecting the software versions of Brave was broken. I've used the feeds suggested in [this comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1791#issuecomment-1030152913). Because there is a version returned does not mean there is a Windows artefact for it. So added some code to test if the software is actually there.
I ran the update.ps1 script with the current version numbers (from the feeds) and using different version numbers fed into the code and checked the created nupkg files. Somebody with more experience of how the builds work here would be better placed to do more extensive testing.
N/A
=> (brave) Fix Brave package version detection / automation

.github/workflows/toc.yml, CONTRIBUTING.md, README.md
This pull request adds a new GitHub Action workflow that will generate and push a new commit to the repository when it needs to update the TOC content for both the Readme.md and Contributing.md files.
To have a TOC available for the files, without the need for us to create the TOC content manually.
1. Tested on my fork to ensure that it works as expected. See https://github.com/AdmiringWorm/chocolatey-coreteampackages/commit/312146ba6f67b7282bf1ebf435fd9e1453611013 as what it will create for this PR.
N/A
Loosely related to #1754
=> (docs) Add automatic generation of TOC content

automatic/bleachbit.install/tools/chocolateyInstall.ps1
Changes `$toolsPath` to `$toolsDir`, because `$toolsPath` is not defined in this package.
Fixes #1850
Installed in the test environment and ensured that the installer was removed.
=> (bleachbit.install) fix installer removal

automatic/brave/tools/helpers.ps1
The first number in brave version contains now 3 digits instead 2 (major version of Brave is now "100").
I suggest this change to support major versions with any number of digits.
See https://github.com/chocolatey-community/chocolatey-packages/issues/1848 for more details.
` $installedVersion = $key.Version[3..($key.Version.length - 1)]`
works only with Brave major version with 2 digits (less than version 100.x.y.z)
To support any number of digits, My proposal is to replace with:
`$installedVersion = $key.Version -replace "\d+\.(.*)", '$1'`
Previous helpers.ps1 does not allow to install new Chocolatey packages for Brave since the version of Brave has reached 100.x.y.z
https://github.com/chocolatey-community/chocolatey-packages/issues/1848
```
[ChocolateyPS] C:\> [version]$installedVersion …
```
=> (brave) Update helpers.ps1 to support Brave major version with more of 2 digits

automatic/notepadplusplus.commandline/README.md, automatic/notepadplusplus.commandline/notepadplusplus.commandline.nuspec, automatic/notepadplusplus.commandline/tools/chocolateyInstall.ps1, automatic/notepadplusplus.install/README.md, automatic/notepadplusplus.install/tools/chocolateyBeforeModify.ps1, automatic/notepadplusplus.install/tools/chocolateyInstall.ps1, automatic/notepadplusplus.install/tools/chocolateyUninstall.ps1
This pull request updates the packages notepadplusplus.install and notepadplusplus.commandline to stop the npp process when it is already running.
If it is found to be running during the upgrade, it will relaunch the npp executable when possible without blocking the installation of the package.
There are no data lost because of the stopping of the process that I could found, with the exception if it is a very old installation of npp already running (version on test-environment installed.
If the npp process is already running, there is only a partial upgrade of the software that happens. As such we need to stop the process first.
Tested in the chocolatey-test-environment, and both .install and .commandline is tested using the same steps.
1. Install an older version of the package
2. Launch …
=> (notepadplusplus*) Add logic for stopping and restarting notepad++ process

automatic/graphviz/update.ps1
Not tested but looking at https://www.graphviz.org/download/ the `stable_` prefix was dropped since version 2.50
automatic updates are not working, this should fix it
=> [graphviz] Update auto update installer match string

automatic/mp3tag/legal/VERIFICATION.txt, automatic/mp3tag/tools/ChocolateyInstall.ps1, automatic/mp3tag/update.ps1
This updates the package to include the new 64-bit installer.
Additionally, the update posts changed format recently as well, this updates the regex to work with the new format.
Fixes #1895 
An up-to-date package with all installer architectures is desirable. 
Ran `update.ps1` locally, it updated the package no issues. Installed and uninstall 32 and 64 bit versions in the test environment.
N/A
=> (mp3tag) Add support 64-bit installer and update AU version detection

automatic/gimp/tools/chocolateyInstall.ps1, automatic/gimp/update.ps1
This adds a IWR HEAD check on the default mirror download URL. If it fails, it falls back to the main site download URL.
Fixes #1847 
Install and uninstall in the test env. 
The fallback logic was tested with other invalid URLs.
N/A
=> (gimp) add fallback from mirror to main site

automatic/sysinternals/tools/chocolateyBeforeModify.ps1
This does a `Remove-Process` on anything that is inside the package `$toolsPath` during the beforemodify script.
This closes any programs from sysinternals that are running, so as to allow
uninstalls and upgrades to continue without failing.
Fixes #1884 
1. Installed inside test environment.
2. Opened `procexp.exe`
3. Force upgraded, ensuring that the upgrade succeeds
4. Re-opened `procexp.exe` 
5. Uninstalled 
N/A
=> (sysinternals) Removes processes in before modify

automatic/everything/legal/VERIFICATION.txt, automatic/everything/tools/chocolateyInstall.ps1, automatic/everything/update.ps1
This removes the Everything Command Line, es.exe and adds a notice that it can be installed with the `es` package.
Part of #1705 
`update.ps1` tested locally. 
Updated package installed and uninstalled in the test environment.
N/A
=> (everything) remove es.exe and add notice

automatic/gimp/gimp.nuspec
The latest version of GIMP is [failing in Chocolatey ](https://community.chocolatey.org/packages/gimp/2.10.32) due to a now removed link to the mailing lists. This update provides a link to the new mailing list listing.
This is a simple URL update to allow the new version of GIMP to pass automatic inspection.
N/A
=> (gimp) Update GIMP mailingListUrl to new URL

.gitignore, automatic/kubernetes-cli/update.ps1
One commit ignores `.gz` files.
The other adds streams for recent minor versions.
Fixes #1674
Ran `update.ps1` locally, and installed resulting packages in test environment.
N/A
=> (kubernetes-cli) add streams for recent minor versions

automatic/thunderbird/README.md, automatic/thunderbird/tools/chocolateyInstall.ps1
Adds a `/NoStop` parameter.
Fixes #1721
- Built package with `update.ps1`
- Installed thunderbird version 91.9.1 in the test environment
- Opened thunderbird
- Upgraded to the built package with `--params="'/NoStop'"`
- Validated that the warning about thunderbird not being stopped was shown and that thunderbird was not stopped
- Closed and restarted thunderbird manually and validated that it was updated to 91.10.0
- Uninstalled thunderbird
N/A
=> (thunderbird) add NoStop parameter

automatic/thunderbird/README.md, automatic/thunderbird/tools/chocolateyInstall.ps1
This brings in the package parameters with the extra installer options from the firefox package, as both thunderbird and firefox have the same available arguments.
Fixes #1593
Ran `update.ps1` to build the package. Installed in the test evironment with the added package parameters. Validated that the changed install location worked, that the shortcut were not created, that the update service was not installed, and that the `policy.json` was created. Then validated that the uninstall still worked.
N/A
=> (thunderbird) bring in package parameters from firefox

automatic/firefox/tools/chocolateyInstall.ps1
Removes usage of `Convert-ToJson` and fixes formatting.
Fixes #1931
Discovered in #1918
Installed with `/NoAutoUpdate` in the test environment, and ensured that the `policies.json` file was still created correctly.
=> (firefox) Stop using Convert-ToJson and fix formatting

automatic/umlet/tools/chocolateyInstall.ps1, automatic/umlet/umlet.nuspec
This lets the user choose a java runtime instead of forcing one.
This closes #1942.
The umlet package should be migrated away from the Oracle JRE due to licensing FUD.
=> remove the jre8 dependency and warn the user to manually install a java runtime

automatic/intunewinapputil/update.ps1
Update the script logic to exclude the zip file from the package as we don't have the rights to distribute it.
We don't have permissions to distribute the zip file, so it should not be included in the package.
I have manually run the `update.ps1` file and ensured that the generated `nupkg` file does not include the zip file.
=> (intunewinapputil) Don't include files with the package

automatic/ccleaner/update.ps1
This changeset should modify CCleaner's update script to use an endpoint query, similarly to what CCleaner itself uses, to check for software updates.
Fixes #1960.
I came across the mentioned issue and felt inclined to chime in with an alternative approach to updating the script's regex pattern. Using a regular expression match against a web page's contents can be brittle and subject to failure with unanticipated structural/formatting changes to the web page, as evidenced by the issue raised.
Using Fiddler, I sniffed CCleaner's traffic and came across a request to the following URL:
https://www.ccleaner.com/auto?a=0&p=cc&v=5.92.9652&l=1033&lk=&mk=CMS6-NK32-VYSM-VVU6-EYIH-5FXW-9YH2-XVB8-VTTT&o=10.0W6&au=1&mx=4B6BA6B23E286D4C292C528C1D940CB787BD38E84DD5D0F7D9FE3D10662915C3&gd=1891ed9c-bcbf-4 …
=> (ccleaner) Query auto-update endpoint for update checks

automatic/git.install/tools/chocolateyBeforeModify.ps1, automatic/git.install/tools/chocolateyInstall.ps1, automatic/git.install/tools/helpers.ps1
This changeset implements a package-level workaround for https://github.com/chocolatey/choco/issues/1092, as originally discussed in https://github.com/chocolatey-community/chocolatey-packages/discussions/1924.
Fixes #1938.
When upgrading `git.install` indirectly (via either `choco upgrade git` or `choco upgrade all`, which will alphabetically iterate through `git` first), `choco` will fail to execute `chocolateyBeforeModify.ps1` of any package dependencies being installed. In the context of `git.install`, this contains commands to stop any running instances of `gpg-agent.exe`, which may run as a background process when commit signing is enabled. Commit signing is a commonly enabled feature to help certify the authenticity of a given commit's author.
While this would ideally be fixed …
=> (git.install) Terminate gpg-agent when indirectly upgrading

automatic/vagrant/update.ps1
Looks like Vagrant have changed the filename and the links on the page being scraped.
Fixes #1973 
Ran the `update.ps1` file and checked the amended `.nuspec` and `chocolateyInstall.ps1`
N/A
=> (#1973) Update to match new filenames

automatic/vim/tools/chocolateybeforemodify.ps1, automatic/vim/tools/chocolateyinstall.ps1, automatic/vim/tools/chocolateyuninstall.ps1, automatic/vim/tools/helpers.ps1, automatic/vim/vim.nuspec
Stop manually generating `vimtutor.bat` and let `install.exe` generate it.
Add Write-Debug. Fix style.
`vimtutor.bat` is a batch file which is generated in `windir` by `install.exe`.
Batch files like this provide vim related command on cmd.exe/Powershell: `vim`, `gvim`, `vimtutor` commands etc.
`install.exe` is a program which are to be invoked after unzipping Vim install archive.
We were copying `vimtutor.bat` from unzipped folder, but it's wrong. 
`vimtutor.bat` should be generated by `install.exe`.
This PR includes fix for `vimtutor.bat` and coding style for blank lines.
`vimtutor.bat` from unzipped folder differs from what `install.exe` generates. We were using the wrong one and it keeps `vimtutor` command on cmd.exe/Powershell from launching with GVim, the GUI version of Vim.
The …
=> (vim) Fix vimtutor

automatic/codelite/legal/VERIFICATION.txt, automatic/codelite/tools/chocolateyInstall.ps1, automatic/codelite/update.ps1
This changeset resolves `codelite`'s current update script failure by removing 32-bit support from the package.
Fixes #1965.
The upgrade script is failing as follows:
```shell
codelite - checking updates using AU version 2021.7.18
URL check
Exception: D:\Cloud\Dropbox\Documents\PowerShell\Modules\AU\2021.7.18\Public\Update-Package.ps1:110:67
Line |
110 |  … heck_url $url -Options $Latest.Options) { throw "${res}:$url" } else  …
|                                              ~~~~~~~~~~~~~~~~~~~
| URL syntax is invalid:
```
The root cause is that `$Latest.URL32` is not being populated with a valid URL, because [the download page](https://downloads.codelite.org/) no longer contains a link that matches the URL pattern historically used by the latest stable 32-bit installer. Browsing directly …
=> (codelite) Remove 32-bit installer support

scripts/Get-GitHubRelease.ps1, scripts/au_extensions.psm1
Adds a script to address the updates to GitHub Release parsing. 
This has been kept simple, not addressing that wasn't needed for this issue.
As discussed in #2007, the way we were using for scraping GitHub releases in this repository has changed / become unsupported. This function is now available in AU via Update_All (and within the repository). It allows us to simplify update scripts that were previously scraping GitHub releases.
This PR is a prerequisite for the numerous package updates for that issue.
- `Get-LatestGitHubRelease` has been tested against public releases
- `Get-LatestGitHubRelease` has been tested against private releases with a token
- `Get-LatestGitHubRelease` has been used with a PAT hoping to not get rate limited
- Tested using this in Update.ps1 scripts via …
=> (#2007) Adds Get-LatestGitHubRelease

automatic/git.install/update.ps1, automatic/git.portable/update.ps1
This commit updates the handling of how git packages
are being checked, to use the GitHub API when
we try to download/check for the files for the current
release.
To have the package `git`, `git.install` and `git.portable` up to date.
Tested by running `.\update_all.ps1 Git*` (There will be failing packages not related to the three packages intended for this update).
=> (git*) Fix update script to use API

automatic/owncloud-client/update.ps1
This changeset should modify ownCloud's update script to use an endpoint query, similarly to what ownCloud itself uses, to check for software updates.
Fixes #1985.
I came across the mentioned issue and felt inclined to help triage the issue. The root cause ended up being a web scraping related failure. Not long ago, I resolved a similar issue with `ccleaner`, and it turns out this package could also benefit from a similar conversion.
Using Fiddler, I sniffed ownCloud's traffic and came across a request to the following URL:
https://updates.owncloud.com/client/?version=2.10.1.7187&platform=win32&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=&msi=true
I then took this to Postman and removed a few unnecessary query parameters (`oem`, `buildArch` and `versionSuffix`), then …
=> (owncloud-client) Query auto-update endpoint for update checks

automatic/virtualbox/tools/chocolateyInstall.ps1
Title says it all for the most part. Adding 3010 (`ERROR_SUCCESS_REBOOT_REQUIRED`) to the install script's list of valid exit codes.
Fixes #2006.
In this situation, this would cause the package to print a misleading error message. We should avoid suggesting an error condition occurred when no apparent problem exists.
1. `choco pack` against the modified package code.
2. `choco install virtualbox --version=6.1.38`
3. Produce any condition with the installer that will require a reboot to successfully complete installation.
4. Upgrade to the modified package with `choco upgrade virtualbox --source="."`
5. Reboot the operating system.
6. Confirm the upgrade operation has succeeded as expected.
> **Note**
> I had a difficult time reliably reproducing this via a real-world use case. I've …
=> (virtualbox) Add ERROR_SUCCESS_REBOOT_REQUIRED (3010) to Valid Exit Codes

scripts/Test-RepoPackage.ps1
This improves the package name extraction from nupkg filename in `Test-RepoPackage.ps1` to properly detect the package name when it ends with a dot followed only by numbers, e.g. package name such as `python3.7`. This works as long as the folder name for the package contains that part of the package name as well.
Required for #1993 to pass, seemed to make more sense as a separate PR.
I've tested in on a few cases:
- Package with no dots in it (e.g `audacity`).
- Package with dots where none of the segments (aside from the first one) contain only numbers (e.g. `autoit.install`, `7zip.install`)
- Packages whose names don't always match the folder name - `1password` and `360ts` can generate a variant of the package named `1password4` and `360tse`, respectively. To make this work, after …
=> Fix pkg name extraction from nupkg filename when it contains dots

automatic/composer/update.ps1
Updates to use the GitHub REST API for releases.
The previous method for scraping GitHub assets from the release page has been broken.
This updates this package to use the REST API.
This adds to #2007.
- Successfully ran update_all.ps1 with this package. This was an improvement on the recent failures in the Appveyor logs.
- ~[ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).~
- ~[ …
=> (composer) Updates Update.ps1 with Get-GitHubRelease

automatic/nodejs.install/tools/chocolateyInstall.ps1
Changed the SilentArgs in the package to remove `REMOVE=NodeEtwSupport`. I could find no information on this, but it looks like it's been removed from the MSI as an installer argument / property. Removing this allowed the installation to continue.
Package is failing verification as it's exiting with a 1603 error.
Installed in a clean Windows Sandbox environment.
Fixes #2027
=> (nodejs.install) Fix installer silent arguments

automatic/nodejs.install/update.ps1
This fixes the silent arguments of nodejs.install. #2032 fixed this in the wrong place.
Fixes #2027 
NOTE TO REVIEWER: Please ensure you force push this package once it's been merged. 
Package doesn't install.
Installing in Windows Sandbox.
N/A
=> (nodejs.install) Fix silent arguments

automatic/bulk-crap-uninstaller/update.ps1
Switches bulk-crap-uninstaller to use Get-GitHubRelease
Part of #2007
Ran AU script locally, it updated the package correctly.
=> (bulk-crap-uninstaller) Switch AU to Get-GitHubRelease

automatic/notepadplusplus/update.ps1
Switches notepadplusplus to use the `Get-GitHubRelease` helper function for AU updates.
Also fixes `notepadplusplus.install` and `.commandline` as they dotsource the `notepadplusplus` AU script.
Fixes #2000
Once this is merged, update the list in #2007 
Ran AU locally for metapackage, .install and .commandline, and all worked.
N/A
=> (notepadplusplus) Update AU script with GitHub release script

automatic/python3-streams/python3-streams.nuspec, automatic/python3-streams/update.ps1
Fixed the issues with package name replacements in python3-streams package that I mentioned in #1993.
The package is failing automated package testing on Chocolatey Community Repository.
Checked the artifacts generated by AppVeyor
=> Fix package name replacements in python3-streams

automatic/openshift-cli/update.ps1
It was pointed out that OpenShift was no longer adding GitHub releases to track releases of openshift-cli.
Originally fixed the GH Releases issue, then found that even with it working it wasn't at the latest version.
This should solve that issue.
Update for this package was broken.
Fixes #1983 
- Tested locally with `.\update_all.ps1 -Name openshift-cli`
- ~[ ] I have updated the documentation accordingly (this usually means the notes in the …
=> (openshift-cli) Updates to not use GitHub Releases

automatic/audacity/update.ps1
This pull request fixes the updater to find the correct download URLs based on the new file name for the executables.
Without this change the binary files can not be found.
To have a working updater.
1. Tested locally by running `.\update_all.ps1 audacity`
=> (audacity) Fix file name changed for installer

automatic/gitextensions/update.ps1
Fix the update.ps1 for gitextensions to correctly get the versions
Currently updates are failing and there is a new unrelased version.
Fixes #2055 
Ran the update.ps1 and could see a v4 update
=> (gitextensions) Fix update.ps1

automatic/cygwin/Changelog.md, automatic/cygwin/cygwin.nuspec, automatic/cygwin/legal/VERIFICATION.txt, automatic/cygwin/tools/chocolateyInstall.ps1, automatic/cygwin/update.ps1
The main purpose of this pull request is to remove support for 32bit installation, which according to their latest changelog is no longer supported upstream.
Additionally, dependencies that only existing to provide compatibility support for versions older than Chocolatey CLI 0.11.0 has been removed as we no longer
support any versions that old.
To be able to update the package.
1. Run `.\update_all.ps1 cygwin`
Additionally, using the test environment:
1. Run `choco install cygwin --source 'Location_of_your_built_package'
2. Ensure it installs successfully
3. Run `choco uninstall cygwin`
4. Ensure it uninstalls successfully
5. Run `choco install cygwin --x86 --source 'Location_of_your_built_package'
6. Ensure it fails with a message saying `32bit installation is no longe supported.`
=> (cygwin) Remove 32bit installation support

automatic/qbittorrent/Readme.md, automatic/qbittorrent/qbittorrent.nuspec, automatic/qbittorrent/tools/VERIFICATION.txt, automatic/qbittorrent/tools/chocolateyinstall.ps1, automatic/qbittorrent/update.ps1
qBittorrent update to version 4.5.0
For 64-bit version only, last 32-bit qBittorrent version will remain 4.4.5
I made necessary changes to files:
automatic/qbittorrent/Readme.md
automatic/qbittorrent/tools/VERIFICATION.txt
automatic/qbittorrent/tools/chocolateyinstall.ps1
automatic/qbittorrent/update.ps1
choco will update to 4.5.0 on 64-bit systems
Fixes #2073
powershell
=> qBittorrent update to version 4.5.0

automatic/etcd/update.ps1, scripts/Get-AllGitHubReleases.ps1, scripts/au_extensions.psm1
This pull request fixes the update script for the etcd package by introducing a new helper to acquire github releases.
This new helpers grabs all of the github releases (may be limited by github themself).
To have a working package
1. Run `.\update_all.ps1 etcd`
=> (etcd) Fix update script

automatic/python3-streams/update.ps1
A follow-up to #1993, [python311](https://community.chocolatey.org/packages/python311) package was approved yesterday, we can drop previous limitations :tada: 
Hopefully, you don't mind this PR, I wasn't sure if it was fine for me to make this or if I should have just left it to maintainers.
This was a temporary measure while we were waiting for python311 package to get pushed to and approved on the community repository.
It hasn't, I assume it was tested when it was committed to #1993.
=> (python3-streams) Drop temporary disables in Python packages

automatic/mpc-hc-clsid2/update.ps1
Reverses the x86 and x64 installer matching that I'd reversed.
During the refactoring of a bunch of packages on Community Day, I pushed an update refactor that changed how we grabbed releases from GitHub and mixed up the x86 and x64 installer regexes. This sorts that out, as well as providing a release URL to add to the verification file.
Fixes #2095
Tested with a local run of `.\update_all.ps1 mpc-hc-clsid2 -ForcedPackages mpc-hc-clsid2`, double checking all resulting changes to the files on disk.
- ~[ ] My change requires a change to documentation (this …
=> (mpc-hc-clsid2) Fixes Mixed URLs

automatic/python3-streams/update.ps1
As it turns out, docs archives for EOL releases at docs.python.org do eventually get evicted. Therefore, I used the more reliable ftp.python.org instead. Note that I still had to keep the old docs.python.org for the version that's currently in development (3.12 right now) as the documentation on ftp.python.org only starts to appear when the RC phase starts. This is described in more detail in the "Doing Python Releases 101" document at https://peps.python.org/pep-0101/
Note that it is unlikely to ever get hit in the future once each package has at least one version since then it would simply never get to the point of downloading a zip for such an old release since it would have already been on Chocolatey by that point and update script would skip it due to no new version being available. …
=> (python3-streams) improve reliability of docs zip URL

automatic/ghostscript.app/ghostscript.app.nuspec, automatic/ghostscript.app/update.ps1, automatic/ghostscript/ghostscript.nuspec, automatic/ghostscript/update.ps1
The docsUrl and releaseNotes URLs now point to a fixed readthedocs.io page. The use of version numbers in the URLs are no longer needed and are removed from the automatic update script.
Fixes #2127 
Packages are failing Package Validator due to invalid URLs.
Not tested as this is only changes to the package metadata.
=> (ghostscript)(ghostscript.app) Fixed validation failures

automatic/gitextensions/gitextensions.nuspec
Added .NET 6 dependency for Git Extensions.
Fixes #2111 
Git Extensions now requires .NET 6.
1. Ran current `gitextensions` install and saw it failed, just like #2111 indicates.
2. Installed the `dotnet-6.0-desktopruntime` package.
3. Ran Git Extensions again and it worked.
4. Added dependency to the .nuspec file.
5. Created a test package using new dependency.
6. Installed test package.
7. Everything worked as it should.
=> (gitextensions) Add .NET 6 dependency

automatic/openshift-cli/openshift-cli.nuspec
The `mailingListUrl` is now invalid so it was removed.
**Once this is merged, the package will need to be pushed again.**
Fixes #2124 
Package is failing Package Validator with an invalid `mailingListUrl`
It hasn't been tested. The line containing the `mailingListUrl` was removed from the .nuspec file.
=> (openshift-cli) Remove invalid mailingListUrl

automatic/apache-httpd/apache-httpd.nuspec, automatic/apache-httpd/tools/helpers.ps1
Replaced Chocolatey private variables with their cmdlet equivalents, whcih requires Chocolatey CLI 1.2.0 so I've added that as a dependency.
Package is failing Package Validator.
Tested in the Windows Server 2019 Chocolatey Test Environment.
=> (apache-httpd)(#2151) Replace private variables

automatic/libreoffice-streams/tools/helpers.ps1
This changeset fixes a recently introduced update error currently impacting `libreoffice-fresh` v7.5.0+ (and by extension, `libreoffice-fresh` v7.4.6 and `libreoffice-still` v7.4.6+, since these would be built in the same AU run).
Fixes #2168.
Starting with LibreOffice v7.5.0.0.alpha1, the 64-bit installer adopted a new architecture string (`x86-64`) in its filename.
The Document Foundation's update service recently made v7.5.1 available for download on the Fresh branch, which triggered detection of a newly available software version which uses this pattern.
The update script makes use of some helper functions to construct the two streams (Fresh and Still) which reflect the branched release model of LibreOffice. `GetFilename` in particular probes The Document Foundation's Download …
=> (libreoffice-streams) Add missing 64-bit arch pattern to filename search

automatic/7zip.install/update.ps1
This should fix the replacement of checksumtype in the verification file, which was not being updated by `au_SearchReplace`.
The checksum type was missing from `7zip.install` in source. I checked [on CCR](https://community.chocolatey.org/packages/7zip.install#files) as well, to see that it wasn't just not present here.
As I was trying to replicate this in another package, I found that it should have been using the checksumtype64 (or the 32 version of the same variable) instead of just checksumtype. You can see this [in AU](https://github.com/chocolatey-community/chocolatey-au/blob/master/AU/Public/Get-RemoteFiles.ps1#L83).
`7zip.portable`, somewhat confusingly, sets `$Latest.Checksum` during the `BeforeUpdate` step, so I suspect this came across from there.
- Tested on the Jenkins PR
- ~[ …
=> (7zip.install) Fixes broken checksumtype SearchReplace

.github/DISCUSSION_TEMPLATE/ideas.yml, .github/ISSUE_TEMPLATE/config.yml
This pull request adds a very basic template requesting the information we want the user to have verified before they request adding features, or enhancing packages.
Some leg work is needed when requesting features, and we want the user to confirm that they have done this before creating the discussion.
As well as give them information about what we expect.
1. Go to https://github.com/AdmiringWorm/chocolatey-coreteampackages/discussions/new/choose
2. Select `Ideas`
3. Play around
=> (maint) Create basic template for features

automatic/codelite/update.ps1
This changeset adjusts the regex pattern used in scraping the latest stable version info from the [CodeLite download page](https://downloads.codelite.org/), to enable `codelite`'s update script to work correctly.
Fixes #2176.
As of v17.0.0's release, the website no longer contains the word "Release" in the table header that we scrape to determine the latest stable version. This causes `$version` to be set to `$null`, as there are no valid string matches against the current regex pattern.
Resolved by adjusting the regex pattern to reflect this change.
* OS Build: Windows 11 Pro v10.0.22621.0 (64-bit)
* PowerShell version: 7.3.3
* Chocolatey version: 1.3.1
* Vagrant Box Version: 3.0.0
* VM Provider: Virtualbox (although practically Hyper-V, since I manually converted the resulting virtual …
=> (codelite) Fix version scraping

automatic/k9s/tools/chocolateyinstall.ps1, automatic/k9s/update.ps1
In PR https://github.com/derailed/k9s/pull/1910 the x86_64 in the release was changed to amd64
so that :
`k9s_Windows_x86_64.tar.gz`
changed into
`k9s_Windows_amd64.tar.gz`
This will check for both and select the correct version
This will also close https://github.com/chocolatey-community/chocolatey-packages/issues/1999
It is really annoying that it is still not up to date to the latest version available
=> (k9s) Include new Amd 64 version

.github/CODEOWNERS, automatic/brave/legal/VERIFICATION.txt, automatic/brave/tools/chocolateyInstall.ps1, automatic/brave/update.ps1
The changes in this pull request updates the brave package to continue embedding the 64bit installers, while the 32bit installer is now being downloaded during runtime if the running computer is a 32bit system, or the user has requested to install the 32bit version of bave.
This pull request fixes #2158
The package has gotten too large to be able to embed both the 32bit and 64bit executables, as such we need to move to the next best thing which is to only partially embedd executables.
As a first step we need to create the expected package.
1. Run the script in the root directory with the following command: `.\update_all.ps1 brave`
2. Verify it created both a stable and beta versions (at the time of writing, these were version `1.49.128` and `1.50.101-beta`)
3. Verify the Chocolatey …
=> (brave) Change package to be partially embedded

automatic/wixtoolset/update.ps1, automatic/wixtoolset/wixtoolset.nuspec
The website looks have changed, which makes it harder to parse the website. With this in mind this pull request changes to track the v3 releases available on GitHub through our custom API helper instead.
We need to keep an eye on the development in v4 for this, in case they decide to release a full installer for it but as of right now that isn't available.
Ref #2187 (remember to tick the task for `wixtoolset` when merging)
To get the automatic updater fixed.
1. Run `.\update_all.ps1 wixtoolset -ForcedPackages wixtoolset`
2. Verify it created a new fix version successfully.
3. Restore a snapshot of chocolatey-test-environment
4. Run `choco install wixtoolset --source "C:\packages;chocolatey"` (change C:\packages to where you have the wixtoolset package)
5. Verify it successfully installed …
=> (wixtoolset) Change to only track GitHub v3 releases

.github/CODEOWNERS, automatic/totalcommander/README.md, automatic/totalcommander/TotalCommander.nuspec, automatic/totalcommander/legal/VERIFICATION.txt, automatic/totalcommander/tools/chocolateyInstall.ps1, automatic/totalcommander/tools/chocolateyUninstall.ahk, automatic/totalcommander/tools/chocolateyUninstall.ps1, automatic/totalcommander/tools/helpers.ps1, automatic/totalcommander/update.ps1
When digging into #2121 I had to rewrite the AHK file for the uninstallation. I then started testing the package parameters, and they were fairly, so I rewrote the package to make it work on the Chocolatey test Environment (Windows Server 2019) and Windows 10.
The changes:
* I rewrote the Autohotkey uninstall script to be version 2 compatible and it now works. Updated the dependency for `authotkey.portable` to minimum of 2.
* The package has a `/DesktopIcon` switch, and the description suggests that the package does not by default add a desktop icon. However, a desktop icon is added every time. I've removed the `/DesktopIcon` parameter (as it doesn't make sense anymore) and added a `/NoDesktopIcon` parameter. This is in keeping with most other packages (that add a desktop icon by default, …
=> (totalcommander) Fix and update package

automatic/sysinternals/tools/chocolateyBeforeModify.ps1
Minor fix for trailing space after "sysinternals" string in Write-Host call.
General clean-up, nothing fancy.
It hasn't, but it's a single-byte cosmetic change, so...
=> (sysinternals) fix minor cosmetic typo

automatic/vscode.install/vscode.install.nuspec
Remove dotnet4.5.2 dependency from VSCode.Install package.
Removed the dotnet4.5.2 dependency from VSCode.Install package.
The dotnet4.5.2 package is out of support, and it not required anymore from VSCode ever since Windows 7 went out of support.
This commit will fix https://github.com/chocolatey-community/chocolatey-packages/issues/2224
Tested both vscode.install and vscode.
- [] The changes only affect a single package (not including meta package).
=> Remove dotnet4.5.2 dependency

automatic/encfs4win/update.ps1, update_all.ps1
This pull request updates the automated updater to make use of the new API helper when getting releases from GitHub.
This change was needed as the old way of doing things does no longer work as these are populated using JavaScript on the website.
Additionally, the call to expanding aliases has also been updated to expand all aliases in a package directory so it will expand any aliases in `update.ps1` as well.
fixes #2192
To get the automated updater working again
1. Run `.\update_all.ps1 encfs4win`
2. Verify there are no failures, and the package update was ignored.
3. Run `.\update_all.ps1 encfs4win -ForcedPackages encfs4win\1.10`.
4. Verify a the package was updated with a new fix version for the latest `1.1.x` version.
=> (encfs4win) Use new API helper to get GitHub releases

automatic/universal-usb-installer/update.ps1
This pull request updates the automatic updater to treat any trailing character
as its own number to be appended to the last version part, this allows us to
create a new package version even when the software developer has created
a new version without using a pure version number.
ref #2187
To have a working automatic updater
1. Run `.\update_all.ps1 universal-usb-installer`
2. Verify it updated to `2.0.1.4100` (those last zeros are the fix version part)
=> (universal-usb-installer) Treat trailing character as a additional version number

automatic/jenkins/legal/VERIFICATION.txt, automatic/jenkins/update.ps1
The update script was swallowing too much on a match, and invalidating the match on the next run. This fixes the validation file, and fixes the update script.
This should fix the Jenkins package update.
The Jenkins package was failing to update. This should solve that issue!
- Checkout fix branch
- `.\update_all.ps1 jenkins`
- Observe changed files to ensure
- Jenkins package is updated successfully
- Verification.txt is still going to match the appropriate regex
- ~[ ] My change requires a change to documentation (this usually means the notes in the …
=> (jenkins) Fixes the Validation File Update

.appveyor.yml, .github/ISSUE_TEMPLATE/bug-report.yml
This updates the Chocolatey version used when building pull requests,
when pushing and running normal updates and removes an unsupported
version of Chocolatey CLI.
We always want to use the latest stable version of Chocolatey CLI when updating and pushing packages, the latest supported version when building pull request and to not list any versions of Chocolatey CLI that is too old for us to support.
N/A
=> (maint) Bump Chocolatey Version

automatic/nexus-repository/nexus-repository.nuspec
Removes the dependency for `TermurinJRE` from the `Nexus-Repository` package.
Nexus, it turns out, packs a version of [Azul Zulu](https://www.azul.com/) with the install. This means that the dependency is unrequired.
- Removed dependency from package, packed it
- Installed clean on a Windows Sandbox container
- Observed Nexus working nicely without any installed JRE package
I would argue this is not a breaking change, though folk may end up with an unrequired package installed after updating their Nexus package.
- ~[ ] My change requires a change to …
=> (nexus-repository) Removes Unnecessary Dependency

automatic/opera/README.md, automatic/opera/tools/chocolateyInstall.ps1
Add `/NoAutostart` param for opera since newer versions annoyingly add an autorun entry to registry by default. https://www.reddit.com/r/operabrowser/wiki/opera/installer_commands/
The param got added where params seem to be normally added.
As above, upgrading/installing Opera makes it autostart with Windows.
I hope this is enough as testing is stopping me from submitting PRs, need to learn how to test such changes and I don't have quite time for that. Filling this template already took longer than the small changes themselves.
Anyways, I ran:
- `choco pack` in the `opera` folder in git repository
- ` choco install Opera --debug --verbose --source . --params "'/NoAutostart'" -f`
- Installation completed, no autorun entry was found
Fixes #2285
=> (opera) Add Opera /NoAutostart param

automatic/vscode.install/update.ps1
Change the check to use github releases instead of the undocumented api.
This will fix issue https://github.com/chocolatey-community/chocolatey-packages/issues/2269
Note: This only fixes `vscode` and not `vscode insiders` as the insiders version is not in GitHub releases.
Version check URL is no longer working stopping the automatic package upgrades.
Ran update.ps1 to generate the new packages, installed the new version locally.
=> (vscode.install) Switch vscode to github release check

automatic/paint.net/tools/ChocolateyInstall.ps1, automatic/paint.net/update.ps1
I have made simple changes to the download part of Get-GithubRelease by specifying the MSI file instead of the exe file.
Adapted all the commands referencing the exe.
Adapted the silentinstall in the PackageArgs to conform with the basic MSI arguments as they are supplied when creating a new chocolatey package using choco new
See discussion:  #1978
See previous (failed/closed) PR: #1987
Tested the installation from a private repository.
=> (paint.net) Changed .exe to .msi installer

automatic/selenium-chromium-edge-driver/update.ps1
Changed the automatic update script to fetch the latest stable driver version directly from MS.
Currently the package is only updated if the edge driver download page has a driver link with the version matching the current version of the microsoft-edge package.
The versions of the selenium driver and browser don't necessarily match up and this caused the update script to be broken for quite a long time. Because of this now quite a few versions of the selenium drivers are missing on chocolatey.
Loading the latest stable driver version from MS and using that for the download links is a more stable approach for the update script. 
Fixes #2241 
Run locally
Had the almost identical PS script in use for the last ~ 1.5 years because for quite some time there was no up-to-date edge driver …
=> (selenium-chromium-edge-driver) Get stable driver version directly from MS

automatic/ant-renamer/update.ps1
This change ensures a scheme matching the one used by the releases URL is added to the download URL if no other is present.
The download URLs on the page are missing a scheme. Though this may work in browsers, it doesn't play nicely with our update scripts / PowerShell.
- Ran `update_all.ps1 -Name ant-renamer` before and after the changes, note no failure on new version
- Tested the (forcibly) generated package ran on a test environment
- ~[ …
=> (ant-renamer) Fixes Update Script (No Scheme)

automatic/juju/update.ps1
This fixes the update script so it doesn't choke if it can't find release notes within the GitHub release body.
The build was failing due to passing an empty string to `Update-Metadata`. This should fix that issue.
Please note that though I added a fallback method ("if the GitHub release exists but there is no link found, link to the GitHub release") in theory if the release page doesn't exist the releasenotes may point to an older version. We might consider updating `Update-Metadata` to accept blank strings and handle itself appropriately in that situation.
The example of the failing release is 'https://github.com/juju/juju/releases/tag/juju-3.3-beta1'
- Ran `upgrade_all.ps1 -Name juju` before and after changes were made …
=> (juju) Fixes Update.ps1 to handle missing release notes

automatic/simplewall/update.ps1
Simplewall have added another zip file to their releases containing pdbs. This was causing the build to fail. This addition to the EndsWith string results in only a single URL matching.
Builds for Simplewall, .install, and .portable were failing due to the update.ps1 for simplewall failing.
This fixes that.
- Ran `upgrade_all.ps1 -Name simplewall` before and after changes were made …
=> (simplewall) Fixes Update.ps1 Overenthusiastic Match

automatic/kubernetes-cli/update.ps1
Fixes a GitHub page-parse that no longer works / has been restricted by GitHub. This now uses the raw markdown file and parses that for the required links.
It seems we have a few more places where we were parsing GitHub pages - I thought we'd caught them all. The build was broken, and now should work.
- Ran `upgrade_all.ps1 -Name kubernetes-cli` before and after changes were made …
=> (kubernetes-cli) Fixes Update.ps1 (HTML parsing)

automatic/filezilla/update.ps1
Modified update.ps1 to use the URL in the releases variable to modify VERIFICATION.txt
Fixes #1881
See request in PR: #2166 
The download links for Filezilla use a unique value that is timed. Putting them into the VERIFCATION.txt file means that after the time has run out, the links don't work. Using the download page links instead.
This is a simple text file change so hasn't been tested.
=> (filezilla) Fix - verification URL pointing to download page

automatic/opera/README.md, automatic/opera/opera.nuspec, automatic/opera/tools/chocolateyUninstall.ps1, automatic/opera/tools/uninstall.ahk
This changeset modifies `opera`'s uninstallation process to close any running instances of Opera, then runs an AutoHotkey script, to work around Opera's decision to disable the `/silent` switch in its uninstaller.
Fixes #2249.
This should enable the package to complete uninstallation in an automated fashion.
I've added a new dependency on `chocolatey-core.extension` v1.3.4+ and `autohotkey.portable` v2.0.0+, as well as a new package parameter (`/RemoveUserData`) to facilitate the process and ensure possibly desired functionality is exposed for user consumption.
The uninstaller's workflow may change slightly if existing user data is detected. After initially pressing the Uninstall button, a survey page may appear in the uninstaller for the user to optionally provide feedback as to why it's …
=> (opera) Add unattended uninstallation support

.github/workflows/stale.yml
Update the stale messages used by the GitHub Action.
On the Contributing.md file, we include a note about not commenting just to try to circumvent the automatic closure. This adds a similar note directly to the comments left by the GitHub Action.
This is an update to the wording of the action, no testing has been done.
=> (maint) Update stale messages

automatic/nexus-repository/nexus-repository.nuspec
Fix the docsUrl for nexus-repository so it passes verification.
Bad links fail the verifier
N/A
<
=> (nexus-repository) Fix docsUrl in nuspec

automatic/ghostscript.app/ghostscript.app.nuspec, automatic/ghostscript.app/tools/ChocolateyInstall.ps1, automatic/ghostscript.app/tools/ghostscript.ahk
Add AHK install script after Artifex disabled the silent flag in the GhostScript installer.
Fixes #2221 
Artifex disabled the option to install GhostScript with the silent flag (it's get's always overridden).
Installing Ghostscript with Chocolatey is only possible by using AHK.
Uninstaller does not need adjustments as it still can be run with silent flag.
Tested successfully on latest Windows 11 fully patched.
Edit: Also tested successfully with with the latest chocolatey test environment.
=> (ghostscript.app) Use AHK for installation after silent install flag removal

automatic/vscode.install/README.md, automatic/vscode.install/tools/ChocolateyInstall.ps1, automatic/vscode.install/update.ps1, automatic/vscode/vscode.nuspec
Remove 32-bit checks.
vscode does not provide a 32-bit version anymore after 1.83, so the automatic update checks fail.
#2344
I wan't able to get the update checks running locally. Since I only removed the 32-bit URLs, I hope this is ok.
=> (vscode.install) fix vscode.install after 1.83

automatic/googlechrome/update.ps1
Fix Google Chrome Download Link
The google chrome download link has changed slightly, I fixed it so it will download reliably now.
I changed `https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise.msi` to `https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi` removing the `tag/s/` part, as that has apparently changed.
This fixes the chrome installer, as that is failing for my PCs I manage.
I don't fully know how to test this script, if someone can let me know, I will happily do whatever I need to.
=> (googlechrome) Fixed the Google Chrome Download Links

automatic/calibre/update.ps1
Updates the AU script for calibre to use the v7.x releases page
Similar to the changes in https://github.com/chocolatey-community/chocolatey-packages/pull/1947
Whenever Calibre has a major version bump, the releases page changes, so the script needs to change. 
Tested on Windows 10 22H2
=> (calibre) update AU script for v7.x

automatic/tixati/tixati.nuspec, automatic/tixati/tools/chocolateyInstall.ps1, automatic/tixati/tools/tixati.ahk
Rewrote the AutoHotKey script to be compatible with AHKv2.
The Tixoti package has an "open" dependency on AutoHotKey. When V2 of AHK was realeased, it had significantly different syntax, and it broke this package (and many others). The AHK script had to be rewritten. Also, launching the installer from the ChocolateyInstall.ps1 script rather than from AHK seems more "proper".
`choco pack` and `choco install tixoti -s . -y` and `choco uninstall tixoti -y`
=> (tixati) Overhauled AHK script for v2 (attempt 2)

automatic/prey/update.ps1
This package was relying on parsing the HTML for one of GitHub's release pages. I thought we'd caught all of these, but it seems not.
The build was broken due to there being a lack of matching links to parse on the returned site for GitHub, what with everything moving to rendering in delightful alternate technologies.
- Ran `upgrade_all.ps1 -Name prey` before and after changes were made
- ~[ ] I have updated the documentation accordingly …
=> (prey) Fixes Update.ps1 (HTML parsing)

automatic/youtube-dl/update.ps1
This commit both switches to using the GitHub releases for sourcing update information, but also adds nightly builds to the streams to build.
The build was broken due to the update-target being a site that has been taken down. This moves the target to the GitHub release page, and adds a nightly versions to the repository when found (with a `-nightly` addition to the version to ensure they track as pre-release).
- Ran `upgrade_all.ps1 -Name youtube-dl -force youtube-dl` before and after changes were made
- …
=> (youtube-dl) Fixes Update.ps1 and adds Nightly stream

automatic/nomacs/update.ps1
Updates the `Update.ps1` script to use the GitHub release API rather than parsing the (now unparsable) HTML pages.
Note: It seems that we've been publishing beta versions as full releases. Should we change that?
The build was broken.
- Ran `upgrade_all.ps1 -Name nomacs` before and after changes were made (with force, as there's no currently newer non-prerelease version available) …
=> (nomacs) Fixes Update.ps1 (HTML Parsing)

automatic/nomacs.portable/update.ps1
Updates the `Update.ps1` script to use the GitHub release API rather than parsing the (now unparsable) HTML pages.
Note: It seems that we've been publishing beta versions as full releases. Should we change that?
The build was broken.
- Ran `upgrade_all.ps1 -Name nomacs.portable` before and after changes were made (with force, as there's no currently newer non-prerelease version available)
- ~[ ] I have updated the documentation accordingly …
=> (nomacs.portable) Fixes Update.ps1 (HTML Parsing)

.github/CODEOWNERS, automatic/k9s/update.ps1
In pr https://github.com/derailed/k9s/pull/2153 they have changed the extension from txt to sha256, this change will make it possible to update k9s
=> (k9s) Update to checksum extension to sha256 

automatic/musescore/legal/VERIFICATION.txt, automatic/musescore/update.ps1
The changed hard-coded link is not necessary in the old format and the way it is worded suggests that the download location is sufficient. There is already a valid download-link generated and pushed to the VERIFICATION.txt, so there is no need for a second one.
In the VERIFICATION.txt were two msi-links included. As the first one is not necessary and suggests that the download location is sufficient, it would be great if it could be changed, because of some automations we are using.
This change does not harm or interrupt the update-module and its process at all as the link is only there for informational purpose.
=> (musescore) Cleanup update.ps1 links

automatic/inkscape/tools/chocolateyInstall.ps1
Make start menu entries visible for all users.
Workaround for upstream bug https://gitlab.com/inkscape/inkscape/-/issues/1618
Apply the workaround suggested in the upstream bug: Pass ALLUSERS=1 to the MSI installer.
Then, the start menu entries are visible for all users and not just for the one user that runs choco.
Fixes #2328 
- official choco test env 
- and also in custom VM
- You can see that it works by right-clicking on the Inkscape start menu entry --> More --> Open File Location. Check that it is NOT in C:\Users\...\AppData\... but somewhere system-wide
=> (inkscape) Create start menu entries for all users

automatic/vscode-insiders.install/tools/chocolateyInstall.ps1, automatic/vscode-insiders.install/update.ps1
Removes 32 bit from the package, fixes up the update script. 
32 bit builds have been discontinued, and the syntax of the update check url changed
Fixes #2404
Update script tested on Windows 10, package tested in Chocolatey test env
=> (vscode-insiders.install) fix update script, remove 32 bit support

.appveyor.yml
removed deprecated usage of cup and cinst
Remove depreciation and ensure forward compatibility with AppVeyor images
This has been running in my AppVeyor for a while now
=> (maint) remove old cinst and cup commands from .AppVeyor.yml

automatic/googlechrome/update.ps1
The api-url used for Google Chrome is not the Google Chrome version that will be downloaded.
The url is pointing to the extended releases. These are well behind and also not the version that will be downloaded from the url at this time (giving mismatch on hash). Move it to the stable-url which do match the downloaded msi.
- The versions of extend are way behind
- Hash mismatch when doing fresh install
- 
- Created the package with choco pack and the right hashes.
- 
=> Change the api-url to use the stable version

automatic/vim/tools/chocolateyinstall.ps1
Use Get-ChocolateyUnzip instead of Install-ChocolateyZipPackage to install Vim.
As mentioned in #2390, I replaced Install-ChocolateyZipPackage with Get-ChocolateyUnzip in the installation script.
Fixes [issue #2390](https://github.com/chocolatey-community/chocolatey-packages/issues/2390), where auto-validation fails because of a missing checksum required with Install-ChocolateyZipPackage
After applying the fix, I downloaded the Vim zip files and created a package with `choco pack`.
I installed this on a VM, and it installed Vim without errors.
=> (vim) Fix for issue #2390

automatic/cmake/update.ps1
The cmake download page was changed to have both old prerelease versions still available for download after the stable minor version is released. This causes the AU script to error, as the streams variable already has the key, so the stable version is not added. This adds a check to fix that.
Fixes #2394
As the `.install` and `.portable` packages reference this AU script, this change fixes both of them as well.
AU script ran on Windows 10. Package tested in Chocolatey test environment.
=> (cmake) Fix AU version detection

automatic/apache-httpd/apache-httpd.nuspec, automatic/blender/blender.nuspec, automatic/chromium/chromium.nuspec, automatic/cmake.install/cmake.install.nuspec, automatic/cmake.portable/cmake.portable.nuspec, automatic/codelite/codelite.nuspec, automatic/freevideoeditor/freevideoeditor.nuspec, automatic/git.portable/git.portable.nuspec, automatic/jitsi/jitsi.nuspec, automatic/jubler/jubler.nuspec, automatic/mkvtoolnix/mkvtoolnix.nuspec, automatic/msys2/msys2.nuspec, automatic/notepadplusplus.commandline/notepadplusplus.commandline.nuspec, automatic/openssl.light/openssl.light.nuspec, automatic/php/php.nuspec, automatic/pspp/pspp.nuspec, automatic/rapidee/RapidEE.nuspec, automatic/videoder/videoder.nuspec, manual/cdburnerxp/cdburnerxp.nuspec
This updates the references for packages that requires
a specific version of Chocolatey CLI, to remove those
references that required a version that we no longer
support.
We do not want to keep referencing Chocolatey CLI when the required version is one that we no longer support. At the time, the earliest version we support is 1.3.0.
No functional changes has been made, and as such has not been tested through the Chocolatey Test Environment.
Marked as a breaking change, as it techhnically is. However, it is a breaking change introduced by cleaning up packages.
=> (multiple) Remove unsupported reference on Chocolatey CLI

automatic/7zip.install/tools/chocolateyUninstall.ps1
Change uninstaller to ignore entries in registry from standalone 7-zip zstandard.
The standalone 7zip zstandard program (such as from winget mcmilk.7zip-zstd package) creates an entry in the registry beginning with "7-Zip ZS".
Because the choco package simply checks for entries beginning with "7-zip", this causes problems.
If both programs are installed, choco fails to uninstall either, because it detects the two entries.
And if the user runs the 7-zip uninstaller manually, subsequently running 'choco uninstall 7-zip.install' detects the "7-Zip ZS" key and uninstalls it eroneously.
=> (7zip.install) Fix uninstaller key lookup to ignore standalone 7zip zstandard

automatic/winscp.install/update.ps1, automatic/winscp.portable/update.ps1
WinSCP url has changed, appending a /download to the link.
This changes updates de URL and the parsing that goes along with it.
The package was failing to update on the community repo.
Lightly, as I'm on a traiin :)
=> (winscp*) Fixing URL parsing for download

automatic/nodejs.install/update.ps1
Instead of parsing a markdown file, the script uses official JSON files to find the latest versions of each support channel.
NodeJS website fundamentaly changed some weeks ago. I reached out to the NodeJS team [(Discussion 52407)](https://github.com/orgs/nodejs/discussions/52407) and got the hints to json files. Fixes #2452
I tested the content of the changed `au_GetLatest` method and also ran the `update.ps1` script (which downloaded the correct files but failed locally because of missing choco command [we dont use choco on our dev systems])
=> (nodejs)(nodejs.install) rework update script to be more future-proof (#2452)

.github/CODEOWNERS, automatic/krita/krita.nuspec, automatic/krita/update.ps1
update download page url
add tunisiano187 as CODEOWNER
update download page url
add tunisiano187 as CODEOWNER
Fix error on gist : https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#krita
The download page as changed, so the update.ps1 doesn't work anymore.
Directly on my computer with chocolatey-au
=> (krita) update download page url

automatic/chromium/legal/VERIFICATION.txt, automatic/chromium/tools/chocolateyInstall.ps1, automatic/chromium/update.ps1
This change removes the x86 binary from the package, leaving a link to it.
The final nupkg was too large to push to CCR, so we needed to cut space.
This change should serve many users, while still enabling x86 usage. 
As commented in the previous pull request, the decision was made to continue containing the x86 install.
Fixes #2295
Recreates #2299
- Built using `update_all.ps1`
- Installed with defaults
- Installed with `-x86` (note: hasn't been tested on an actual x86 machine)
- ~[ ] My change requires a change to documentation (this usually means the …
=> (chromium) Only Internalizes x64 Binary

automatic/autohotkey.install/tools/VERIFICATION.txt, automatic/autohotkey.install/tools/chocolateyInstall.ps1, automatic/autohotkey.install/update.ps1
Adds AutoHotkey v2 with v1 compatibility.
AutoHotkey v1.1 has been deprecated and v2 has been out for some time. There is concern around upgrading to v2 and v1 scripts failing. There are a lot of v1 script still on CCR.
I don't feel this is a breaking change (as functionality has not changed) so have not ticked that below.
Closes #1710 
It was tested in the Chocolatey Test Environment with the [Logitech Presentation](https://community.chocolatey.org/packages/logitech-presentation) package that has an AutohotKey v1 uninstall script.
=> (autohotkey.install)(#1710) Add AutoHotkey v2 with v1 compatibility

automatic/octave.portable/legal/VERIFICATION.txt, automatic/octave.portable/tools/chocolateyInstall.ps1, automatic/octave.portable/update.ps1
As per https://octave.org/download, there are no longer official 32 bit binaries for windows as of v8.4.0. This PR removes the 32 bit support from the package so it can be updated.
Fixes #2406
Update script ran on Windows 10, package tested in Chocolatey test env.
=> (octave.portable) Remove 32 bit support

automatic/tixati/tools/chocolateyInstall.ps1, automatic/tixati/tools/chocolateyUninstall.ps1
This should fix [issue #2182](https://github.com/chocolatey-community/chocolatey-packages/issues/2182) by ~~first closing~~ *notifying the user and quitting if* any Tixati application processes running on install or uninstall.
The Tixati package is significantly behind because issue #2812 has held it up (and I'm tired of waiting).  The choice was either to fail upgrades (or installs) with a message to close/quit if the Tixati application was running or to unilaterally close the process and perform the upgrade.  I chose the ~~latter~~ *former, after feedback and consideration*.
I started Tixati and then upgraded it via `choco upgrade tixati -y`.  Note:  this PR has not been run through the official Test Environment, but:
1. The current (pre-PR) package code *has* been tested/approved.
2. …
=> (tixati) Fix for app running on update (#2182)

automatic/freecad/tools/chocolateyInstall.ps1, automatic/freecad/update.ps1, automatic/freecad/update_helper.ps1
Fixes the update script regex and removes 32 bit references.
Fixes #2338 
The 32 bit builds are completely gone now, so the 32bit references in the install script can be removed.
Script tested on Windows 10, packages tested in Chocolatey test env.
=> (freecad) Fix portable regex and remove 32 bit references

automatic/datagrip/tools/ChocolateyInstall.ps1
The workaround, and folder having to be created before the installer is run, can be removed as the issue has been fixed in the installer. The installer argument, specifying the installer, should not be wrapped in quotes.
Fixes #2257
The package was creating two folders on install and installing to a custom location did not work.
Installing  in Windows Server 2019.
=> (datagrip) Fix installation folder

automatic/filezilla/update.ps1
This updates the `Invoke-WebRequest` used in the Filezilla update script to find the versions to add an accept header.
The filezilla update was failing due to an invalid version.
On investigation, the returned page had no useful content. This change fixes that, and allows us to continue grabbing updated links.
Before changes:
After changes:
- ~[ ] I have updated the documentation accordingly (this usually means the notes in the description …
=> (filezilla) Fixes DownloadPage Request

automatic/quiterss/update.ps1
Changes the update script to parse the folder structure, find the latest version, and find the exe within that folder.
The format of the downloads page (and what looks like the entire website) has changed quite considerably, to a hosted files/folders layout. This was breaking the update script.
- `Update_All.ps1 -Name quiterss -Forced quiterss` # [Succeeds]
- `choco install quiterss --Source Desktop --confirm`  # [Succeeds]
- ~[ ] I have …
=> (quiterss) Fixes Update.ps1

automatic/kubernetes-cli/update.ps1, scripts/Get-GitHubRelease.ps1, scripts/Get-GitHubRepositoryFileContent.ps1, scripts/au_extensions.psm1
Changing to `continue` rather than `return` when a URL isn't matched fixes an issue where a pre-release version broke our regex.
Also takes advantage of the REST API to get the changelogs, which improves performance from ~164s to ~86s on my machine.
We may consider releasing prerelease streams at some point, but we don't currently do so - otherwise, we could fix up the regex to respect full semver versions.
GetLatest was failing to return anything. On inspection, it seems that a latest -alpha release was causing get latest to return immediately instead of listing the rest of the available streams.
- Before changes:
- With just the fix to `continue`:
- Including the change to using the REST API:
- ~[ …
=> (kubernetes-cli) Fix Update.ps1 (Prerelease version broke all)

automatic/winscp.install/tools/chocolateyInstall.ps1, automatic/winscp.install/update.ps1
Instead of getting a wildcarded path, we are more specific about the path to the installer we want to run.
Upgrading when multiple versions of the installer were present for whatever reason may fail unexpectedly.
Fixes #2433
- Upgraded from 6.3.3 to 6.3.4 (new)
- Upgraded from 6.3.4 to 6.3.4.20240703 (patchfix)
- Tested building of regular and patchfix versions to ensure logic worked …
=> (winscp.install) Update File Path To Not Use Get-Item/Globbing

automatic/python3-streams/tools/helpers.ps1
Fixes https://github.com/chocolatey-community/chocolatey-packages/issues/1840
Close the security hole; make permissions consistent
All sub-folders are limited to administrators, so pip installs to user site-packages as expected if it's run as a normal user. I tested Python 3.9 and 3.12.
```
PS> python3.9.exe -m pip install pyreadline3
Defaulting to user installation because normal site-packages is not writeable
Collecting pyreadline3
Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3
Successfully installed pyreadline3-3.4.1
PS> python3.12.exe -m pip install pyreadline3
Defaulting to user installation because normal site-packages is not writeable
Collecting pyreadline3
Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing …
```
=> (python3-streams) Also lockdown sub-folders

automatic/autohotkey.install/README.md
Adds a note about the high virus count to the description of the package, copied from `autohotkey.portable`
The package currently has a high virus count, and cannot be exempted as it does not have the note in the package description like the `.portable` package has. 
Related issue #2187
Ran update script and ensured that nuspec was updated correctly.
=> (autohotkey.install) add to to description about virus positives

.github/ISSUE_TEMPLATE/bug-report.yml
Remove unsupported CLI versions. See the [wiki for supported versions](https://github.com/chocolatey-community/chocolatey-packages/wiki/Supported-Chocolatey-CLI-versions).
Unsupported CLI versions are still in the issue template.
N/A
N/A
=> (maint) Remove unsupported CLI versions

automatic/firefox/update.ps1
Mozilla changed their download pages. So au did not work anymore
change the download urls after investigation and testing.
fixes #2530 
powershell on local machine
=> (firefox) changed urls for download

automatic/itunes/tools/chocolateyInstall.ps1
Title says it all for the most part. Adding 3010 (`ERROR_SUCCESS_REBOOT_REQUIRED`) to `itunes`'s list of valid exit codes.
When I was upgrading to the latest package version (12.13.3.2), `iTunes64.msi` returned this exit code.
In this situation, this would cause Chocolatey CLI to print a misleading error message, despite both the package installation and underlying software installation succeeding. We should avoid suggesting an error condition occurred when no apparent problem exists.
1. `choco pack` against the modified package code.
2. Produce any condition that will require a reboot to successfully complete installation.
- Interestingly, I can consistently reproduce this with a clean image, despite taking no conscious action to force this situation. I suspect this may have become the …
=> (itunes) Add ERROR_SUCCESS_REBOOT_REQUIRED (3010) to Valid Exit Codes

automatic/1password/update.ps1
This fixes an issue where a manual package used by an automatic update script is not pushed to the Community Repository.
We want to be able to push fix versions of 1password package that have been moved to the manual directory.
Limited testing. Run
1. `.\update_all.ps1 1password -ForcedPackages '1password\OPW4'`
2. Ensure that the 1password4 nupkg package was copied to the 1password directory.
=> (1password) Fix OPW4 stream not pushed

.appveyor.yml, automatic/tortoisesvn/update.ps1
The current attempt of finding the download URL on SourceForge for TortoiseSVN doesn't work anymore.
It now gets the URL by checking data-release-url for "downloads.sourceforge.net".
I tested it with VSCode. It returned downloadable URLs. They were both downloadable with Firefox and System.Net.WebClient (PowerShell).
I also ran Update-Package and it completed without errors.
=> (tortoisesvn) Fix finding download URL from SourceForge

automatic/thunderbird/update.ps1
Update the thunderbird script to use ESR for the update helper.
Fixes #2515
Thunderbird was updated to use ESR naming for the executables.
Ran update script on Windows 10 22H2
=> (thunderbird) update script use ESR

automatic/autohotkey/update.ps1
I'm hoping this package will be the new example referenced from chocolatey-au. Even if it's not, having a locked installer package version seems to be best practice for metapackages going forward.
For more on this, see [chocolatey-au issue #69](https://github.com/chocolatey-community/chocolatey-au/issues/69)
None
None
=> (autohotkey) add square brackets to au_SearchReplace nuspec

automatic/graphviz/tools/chocolateyUninstall.ps1
Fixes #2512
Typo in the powershell script, the code made no sense and would crash.
Uninstallation was not possible due to crash of unintall powershel script
The fixed script was run successfully and uninstallation succeeded
- [ x] The changes only affect a single package (not including meta package).
=> (graphviz) fix typo preventing uninstallation

automatic/gitextensions/gitextensions.nuspec
Update the .NET dependency on Git Extensions
The minimum .NET version of Git Extensions is now .NET 8.0.8.
Installed package with updated dependencies and confirmed it worked as expected.
Fixes #2535
=> (gitextensions) Update .NET dependency

README.md
Fixed a few links to repository pages inside the README such as Discussions, Issues, Pull Requests. Also fixed a typo.
GitHub treats relative links as relative to repo's code root directory, so `discussions` becomes `blob/master/discussions` instead of the intended page. One common workaround is to use a relative path that goes back 2 levels like `../../discussions`.
=> (maint) Fix broken links to discussions/issues/PRs in README

automatic/notepadplusplus.commandline/tools/chocolateyInstall.ps1, automatic/notepadplusplus.install/tools/chocolateyInstall.ps1
_NOTE: This will require pushing a package fix version._
Removes relaunching Notepad++ as part of the package.
This fixes #2334: the problem that launching the application does so in the context of the elevated Chocolatey CLI session.
This replaces the `Write-Host` text and removes the Start-Process that launched the application in the elevated context.
=> (GH-2334) (notepadplusplus.commandline)(notepadplusplus.install) Stop relaunch as Admin

automatic/nodejs.install/README.md, automatic/nodejs.install/legal/VERIFICATION.full.txt, automatic/nodejs.install/legal/VERIFICATION.x64.txt, automatic/nodejs.install/tools/chocolateyInstall.ps1, automatic/nodejs.install/update.ps1, automatic/nodejs/README.md
This updates the NodeJS updater to support version 23 of the
application, while still keeping support for older versions.
This also refreshes the VERIFICATION.txt used, as well as the install
script to make use of a more (upcoming) standardized template.
fixes #2556
To continue publishing versions of the NodeJS package.
Only the updater has been tested.
1. Run `.\update_all.ps1 -ForcedPackages 'nodejs.install\23' nodejs.install`
2. Verify the package was properly updated to v23.x of NodeJS
3. Run `.\update_all.ps1 -ForcedPackages 'nodejs.install\23' nodejs.install`
4. Verify the packgae was properly updated to v22.x of NodeJS
5. Repeat step 1-2.
6. Repeat steps 1-5 using `nodejs` instead of `nodejs.install`
=> (nodejs*) Update NodeJS updater to support v23

.github/workflows/respond-to-issue.yaml, .github/workflows/respond-to-pr.yaml
Add auto response messages to issues and PR's that are submitted. This will help provide an understanding of what people should expect.
There are a number of PR's being submitted that are wrong, and issues being raised where people expect the community team to do all the work. I hope this helps to address some of this (it won't fix it but every little bit helps).
This is currently working over on [my GitHub repository](https://github.com/pauby/ChocoPackages/tree/master/.github/workflows).
=> (maint) Add issue and PR auto responses

manual/cyg-get/cyg-get.nuspec, manual/cyg-get/tools/cyg-get.ps1
Correct a bug when $cygRoot contain space.
Adding some " to allow space in variable $cygRoot.
If CygWin is installed in "C:\Program Files\CygWin64", "cyg-get firefox" install defaults packages and firefox in the directory "C:\Program".
https://github.com/chocolatey-community/chocolatey-packages/issues/2489
choco install -y --params "/InstallDir:'C:\Program Files\CygWin64' /site:'ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/sources.redhat.com/cygwin/'" Cygwin
choco install -y cyg-get
cyg-get install firefox
=> (cyg-get) Space in $cygRoot

automatic/mkvtoolnix/update.ps1
Updates the AU script to work again
Fixes #2570
Looks like there was a breaking change on the releases website, it now requires a trailing slash.
Tested on Win10 and in test env
=> (mkvtoolnix) fix AU script

automatic/virtualbox/update.ps1
The virtualbox extension package changed naming conventions with the v7.1 release. This updates the AU script to reflect that changed convention.
Fixes #2545
Tested on Win10 and in test env
=> (virtualbox) fix au script

automatic/filezilla/update.ps1
Add headers to the filezilla installer download so it does not get blocked. 
Fixes #2571
Tested on Win10 and in test env
=> (filezilla) fix AU update script

automatic/php/update.ps1
Added `vcredist` version for PHP 8.4
PHP 8.4 uses` vs17`, so the `php` update script needs to have a `vcredist` version for that.
By running the update script and generating the packages locally.
=> (php) Add vcredist version for PHP 8.4

.appveyor.yml, .github/ISSUE_TEMPLATE/bug-report.yml
Update to the latest Chocolatey CLI version.
New Chocolatey CLI release.
N/A
=> (maint) Update to latest Choco version

automatic/python3-streams/update.ps1
As per [CPython issue #2672](https://github.com/python/pythondotorg/issues/2672), alpha and beta builds have no official docs built. Furthermore, as of [CPython PR #124489](https://github.com/python/cpython/pull/124489), the archives we previously referenced are no longer built. The change applies from Python 3.12 onwards based on what I can see in the docs archive.
The more recent versions of Python do not get packages built, as per [Issue #2555](https://github.com/chocolatey-community/chocolatey-packages/issues/2555). The [previous PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2575) did not work for the 3.14 alpha releases and, based on the CPython issue, may continue to break for new releases.
I tested the Python3 update script directly and saw the correct …
=> (python3-streams) Fix copyright reading logic and zip URL generation in python3-streams

automatic/azcopy10/tools/chocolateyInstall.ps1
Update the azcopy10 package urls as the azureedge.net no longer work. See also https://github.com/Azure/azure-storage-azcopy/issues/2903.
Installing azcopy10 currently fails with the following:
```
Attempt to get headers for https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (409) Conflict."
Downloading azcopy10 64 bit
from 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'
ERROR: The remote file either doesn't …
```
=> (azcopy10) update package urls

test_all.ps1
The test_all.ps1 script fails to set the appropriate security protocols for PowerShell versions earlier than 6. This pull request backports a fix from [chocolatey-au](https://github.com/majkinetor/au/issues/142).
This change fixes a problem I experienced when testing locally.
I tested this locally. Making the change made the error go away and set the security protocols correctly.
=> (chocolatey-packages) Update security protocol handling in test_all.ps1 for PowerShell 6+

automatic/inkscape/README.md, automatic/inkscape/tools/chocolateyInstall.ps1, automatic/inkscape/update.ps1
As the 32bit version of inkscape has been dropped, remove support from package.
Fixes  #2552
Tested on Win10 22H2 and in test env
=> (inkscape) drop 32 bit support

automatic/python/README.md, automatic/python3-streams/README.md, automatic/python3-streams/tools/chocolateyInstall.ps1, automatic/python3-streams/update.ps1, automatic/python3/README.md
The Python license has changed. This has broken the parsing logic and new versions are failing to be picked up by the automatic updater.
Python 3.13.2, 3.12.9, 3.11.11, and 3.11.10 have all been missed by the automatic updater. This change fixes the logic so the packages will be correctly created.
I ran the `update.ps1` script and `update_all.ps1` and confirmed that the packages are correctly created.
=> (python3-streams) Fix Python 3 License Parsing

automatic/vcredist140/tools/chocolateyInstall.ps1
Removes old OS version checks 
As Windows XP, vista and 7 are no longer supported by current versions of Chocolatey CLI, the checks in this package can be removed for these older OS versions. These checks are not supported in windows sandbox currently, as per #2618 
https://docs.chocolatey.org/en-us/chocolatey-components-dependencies-and-support-lifecycle/
Fixes #2618 
Package tested on Win 10 and in test env
=> (vcredist140) remove old os version checks

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Document that master should not be used for PR's.
This is tribal knowledge, but is not officially documented.
N/A
=> (doc) Updated docs and PR template to confirm PR's should not come from master

automatic/ruby.install/legal/VERIFICATION.txt, automatic/ruby.install/ruby.install.nuspec, automatic/ruby.install/update.ps1, automatic/ruby.portable/ruby.portable.nuspec, automatic/ruby.portable/update.ps1
This fixes the issue with the updater not picking up the latest version of the package, as well as implementing a new feature to ensure that we only update when the license is what we expect it to be.
This check also includes the latest edition of the license in the package.
- Fixes #2639
- To ensure we do not update the package if distribution rights changes.
1. Run `.\update_all.ps1 -Name 'ruby*'`.
2. Verify all ruby packages is updated to `3.4.2.1` (The version number may be different during your run).
3. Verify the `LICENSE.txt` file was replaced with the latest edition of the license.
=> (ruby*) Fix updater and implement license check

automatic/git.install/README.md, automatic/git.install/legal/VERIFICATION.txt, automatic/git.install/tools/chocolateyInstall.ps1, automatic/git.install/update.ps1, automatic/git.portable/README.md, automatic/git.portable/legal/VERIFICATION.txt, automatic/git.portable/tools/chocolateyInstall.ps1, automatic/git.portable/update.ps1
Git for Windows stopped building 32-bit installers and 32-bit PortableGit. There are only "64-bit"(AMD64) and ARM64 versions now.
It hasn't.
=> (git) Prepare for 2.49.0 update

automatic/calibre/update.ps1
Updates AU script to scrape Github releases page to get the latest version number.
Update script outdated. 
Does not use the Github download URL, as Github binaries removed from older releases.
Fixes #2646 
Win11 and test env
=> (calibre) switch AU script to use Github for version

automatic/tixati/update.ps1
Fixes the updater to read the current website layout.
fixes #2490
The website layout for downloads has changed.
Ran the updater and installed/uninstalled the package locally. Both x86 and x64 installs were tested.
=> (tixati) fix updater for the current website layout

automatic/mkdocs-material/update.ps1
Fixes the mkdocs-material AU script version. 
Package was outdated and failing update in appveyor.
Instead of trying to scrape the webpage for the latest version number, instead use the RSS feed on Pypi for this package.
Script tested in PowerShell v5.1
Package tested in test env.
=> (mkdocs-material) fix AU script

automatic/simplewall.portable/tools/chocolateyInstall.ps1, automatic/simplewall.portable/update.ps1, automatic/simplewall/update.ps1
Updates the archive type for portable simplewall. 
Fixes #2660 
All three `simplewall*` packages use a shared update script from the metapackage, thus the change in archive type broke all three update scripts. 
Tested AU for all three  `simplewall*` packages in PowerShell v5.1
Tested `simplewall.portable` install and uninstall in test env.
=> (simplewall) update portable archive type

automatic/nmap/nmap.nuspec, automatic/nmap/tools/install.ahk
Updates the autohotkey script to be autohotkey v2 compatible, and changes the dependency to autohotkey v2.0.0+
Fixes #2623 
Autohotkey v2 has syntax changes, this updates the script to work with those changes.
I also made some minor tweaks to the flow of the script, to ensure both fresh installs and upgrades/reinstalls work. I'm not sure if this is related to the v2 script upgrade, or Nmap installer changes in more recent versions.
Tested in the test environment.
Tested a fresh installation, tested a force reinstallation, and tested an upgrade from v7.95.0
=> (nmap) make AHK v2 compatible

automatic/waterfox/update.ps1
Fixes the version parsing/mangling in the waterfox AU script. 
Fixes #2648 
Waterfox stopped having the `G` prefix on versions, necessitating a change to the update script.
Tested update in powershell 5.1, package in test env.
=> (waterfox) fix AU version parsing

automatic/freecad/update_helper.ps1
Update the regex to match the newer version of Freecad.
Since Freecad 1.00, the release assets naming scheme changed.
This chocolatey package has been out of date ever since.
This PR is essentially PR #2578 with the changes implemented.
1. Regex Tester
2. Chocolatey-test-environment.
- The `update.ps1` script was first run locally to update the package version, 
- then the local packages were used as a source for choco within the test environment.
Stable, portable and dev versions were successfully installed and uninstalled.
=> fix(freecad): update release name regex

.appveyor.yml, .github/ISSUE_TEMPLATE/bug-report.yml
This change removes it from the issues templates, as well as updating the "PR version" used by AppVeyor to 2.3.0.
Chocolatey CLI 2.2.2 is now more than a year old.
This repository supports the latest versions that are less than a year old, so we are removing 2.2.2 from the supported configuration.
No testing has been done.
- ~[ ] Bug fix (non-breaking change which fixes an issue)~ …
=> (maint) Updates Supported Versions of Chocolatey CLI

automatic/tixati.portable/tools/chocolateyInstall.ps1, automatic/tixati.portable/update.ps1
Fixes both the updater and the install script to handle the download being split between x86/x64 versions.
The website layout for downloads has changed and broke the updater.
The updater has been tested locally. Package install/uninstall has been tested locally and in the test environment.
=> (tixati.portable) fix updater and update package to v3.33

automatic/7zip.install/tools/chocolateyInstall.ps1, automatic/7zip.install/tools/chocolateyUninstall.ps1
Shim the 7zG.exe command line tool in addition to the existing 7z.exe shim
7zG should be in PATH if 7z.exe is in there too, as both might be used interchangably (7zG spawns a GUI window to show progress, which is an user feedback enhancement if unpacking/testing a long archive).
My personal use case for this is would be to make an explorer right click entry to unzip zip files using a different codepage than the current systemwide one, which wouldn't spawn a terminal window.
Works as excepted. To test I went in the install script, replaced the file in the packageArgs to the path of a 7z2500-x64.exe I downloaded from 7-zip's site. Tested using 7zG from the command line worked, and that the shim gets removed on uninstall.
Change is low risk, so I didn't went to test further, everything I …
=> (7zip.install) Shim 7zG.exe as well

automatic/ruby.portable/tools/chocolateyInstall.ps1, automatic/ruby.portable/tools/chocolateyUninstall.ps1
To fix #2256, the .bat and .cmd files in the Ruby bin folder are shimmed. 
When the package is installed, commands in the Ruby bin folder are not added to the path or shimmed, so are not available on the command line everywhere. 
A new package was created with the code and run in the Chocolatey Test Environment. Shims are created on install and removed on uninstall. 
N/A
=> (ruby.portable) Shim bat and cmd

automatic/selenium-chromium-edge-driver/selenium-chromium-edge-driver.nuspec, automatic/selenium-chromium-edge-driver/update.ps1
Changed base URL in `selenium-chromium-edge-driver.nuspec` & `update.ps1`-file. 
From https://msedgedriver.azureedge.net/
to https://msedgedriver.microsoft.com/
Trying to automate an automation setup in an vm, and this URL is blocking the installation of `selenium-chromium-edge-driver`.
Ran the command `choco install selenium-chromium-edge-driver`.
This is the result:
``` bash
Chocolatey v2.5.0
Installing the following packages:
selenium-chromium-edge-driver
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading selenium-chromium-edge-driver 138.0.3351.83... 100%
selenium-chromium-edge-driver v138.0.3351.83 [Approved]
selenium-chromium-edge-driver package files install completed. Performing …
```
=> (selenium-chromium-edge-driver) base url change

automatic/curl/tools/chocolateyInstall.ps1
Additional change following this [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2713).
This should have been included in the previous commit, where the 32bit installer was removed, as it is no longer provided by the project.
- Ran .\update_all.ps1 -Name curl, observed failure
- Updated package files
- Ran .\update_all.ps1 -Name curl, got update for 8.16.0
=> (curl) Remove mention of 32bit file

automatic/1password8/update.ps1
This PR modifies the update script to have a more brittle (but also working) method for grabbing the MSI link, due to the change in the provided link from 1password.
The update script was failing to find the setup, as 1Password has moved to providing only msix links on the default download page.
MSI links still exist based on the version, so we will rely on that not changing for now.
- Updated the package (and the 1password package)
- Tested installation / uninstallation of the package
- ~[ ] My change requires a change to documentation (this usually means …
=> (1password8) Fix Download Link Generation

automatic/peazip.install/peazip.install.nuspec, automatic/peazip/peazip.nuspec
This commit update the projectSourceUrl to go to the GitHub repository for this application. The previous URL is no longer working.  It also introduces an empty files element in the nuspec file to prevent the update.ps1 and readme.md from being packed into the nupkg.
It was requested in the linked issue.
- Ran `update_all.ps1 -name peazip` and packed the resulting files
=> (peazip #2309) Fix URL and package contents

automatic/vlc.install/update.ps1, automatic/vlc.portable/update.ps1, automatic/vlc/update.ps1
- PowerShell update to construct VLC download URLs with HTTPS instead of HTTP.
- Change URL32 and URL64 in automatic/vlc/update.ps1 and URL32 in automatic/vlc.portable/update.ps1 to prefix generated links with 'https:'.
- Ensure secure downloads and avoid mixed content or insecure redirects by using HTTPS for VLC download URLs.
- Aligns with modern transport security requirements and fixes potential security issues.
- Run `.\update_all.ps1 "vlc*" -ForcedPackages "vlc vlc.install vlc.portable"`
- Verify no errors are reported.
=> (vlc*) Use HTTPS for VLC download URLs

automatic/speccy/update.ps1
The speccy download webpage has changed, and it no longer contains the explicit download URL.  Instead, let us construct the URL based on the known portion of the download URL
(https://download.ccleaner.com/spsetup???.exe)
and then put the major and minor portions of the version number where the ??? is.  This means very brittle, but I can't see another way of doing this :-(
Updating of the speccy package isn't working.
- Ran `update_all.ps1 -name speccy`
=> (speccy) Update based on change to webpage

automatic/librecad/update.ps1
This change ensures the x86 installer should not match the x64 exe.
We should consider adding the x64 installer to our package, but:
a) It doesn't need to be a part of this fix
b) It's not clear what the best way forward is - ship the x64 binary, and leave the x86 as a download, continue shipping the x86 and add the x64 as a download, ship both binaries? (25MB each, currently)
I can address that in this PR, or otherwise intend to open an issue to discuss the best move and then action it.
LibreCAD has added a Win64 artifact to their build output. This was being found along with the x86 installer that we were looking for.
- `.\update_all.ps1 librecad`
- `Get-ChildItem .\automatic\ -Filter *.nupkg -Recurse | Sort-Object LastWriteTime | Select-Object -Last 1 | Set-Clipboard`
- `choco install …
=> (librecad) Fixes Update Filtering
