chocolatey-community/chocolatey-packages

- automatic/gimp/gimp.nuspec
- automatic/gimp/tools/chocolateyInstall.ps1
- automatic/gimp/tools/chocolateyUninstall.ps1
silent args were not stringent enough to install or uninstall silently.  updated to suppress progress boxes.
also, filled in empty nuspec tags and corrected poor info
> fixed gimp; install+uninstall were not silent

- README.md
To clarify and remove ambiguity, add some words.
It would be clever to, at some point, write in 3 words (otherwise no one will read it, trust me) how someone can maintain their own autopackage here (through pull requests) and why (so when they decide to die, the package is in the system and easily maintainable by others).
> Add some magic words to README.md

- automatic/smartftp/smartftp.nuspec
changed vcredist2013 to vcredist2015
> updated SmartFTP

- packages/vcredist2015/tools/chocolateyInstall.ps1
- packages/vcredist2015/tools/chocolateyUninstall.ps1
- packages/vcredist2015/vcredist2015.nuspec
This adds Visual C++ Redistributable Packages for Visual Studio 2015
Newer version of #75
> Added vcredist2015 package

- automatic/smartftp/tools/chocolateyInstall.ps1
- automatic/smartftp/tools/chocolateyUninstall.ps1
smartftp: removed deprecated Write-ChocolateyFailure
> smartftp: removed deprecated Write-ChocolateyFailure

- automatic/smartftp/smartftp.nuspec
added admin tag. See https://github.com/chocolatey/package-validator/wiki/AdminTagShouldBeUsedWhenUsingAdminHelper
> smartftp: added admin tag

- automatic/ultradefrag/tools/chocolateyInstall.ps1
- automatic/ultradefrag/ultradefrag.nuspec
> UltraDefrag - Added support for package parameters

- automatic/ffmpeg/tools/chocolateyInstall.ps1
> ffmpeg: clean up older versions

- automatic/libreoffice-help/libreoffice-help.nuspec
- automatic/libreoffice-oldstable/libreoffice-oldstable.nuspec
- automatic/libreoffice/libreoffice.nuspec
> (GH-127) Corrected owners element in nuspec

- automatic/avidemux/avidemux.nuspec
> (GH-124) Added missing owners element

- automatic/codeblocks/codeblocks.nuspec
> (GH-123) Added missing owners element

- automatic/flashplayerppapi/flashplayerppapi.nuspec
> (GH-122) Corrected owners element

- automatic/WinPcap/WinPcap.nuspec
> (GH-137) Added missing title and owners element

- automatic/ffmpeg/ffmpeg.nuspec
- automatic/freecad/freecad.nuspec
- automatic/freeciv/freeciv.nuspec
- automatic/no-ip-duc/no-ip-duc.nuspec
- automatic/x-moto/x-moto.nuspec
- packages/tsremux/tsremux.nuspec
> (GH-141) Corrected owners element

- automatic/hostsman/hostsman.nuspec
> (GH-144) Added packagesourceurl

- automatic/fiddler4/fiddler4.ketarin.xml
> (GH-170) http to https

- automatic/Cygwin/Cygwin.nuspec
- automatic/Cygwin/tools/chocolateyInstall.ps1
- automatic/Cygwin/tools/chocolateyUninstall.ps1
While looking through the script I noticed a few logical errors that needed correcting. If github isn't showing you my comments inline with the code on the PR, it does so here: https://github.com/Link-Satonaka/chocolatey-coreteampackages/commit/13b5a3a4ba54b125c027d0ae7a24bce16b773a88
> Get cygwin into Bin-Root and a few other corrections

- automatic/flashplayerplugin/tools/chocolateyInstall.ps1
Script only checked for major version and ignored minor version.  Now it checks both.
> Check full version

- automatic/python2-x86_32/tools/chocolateyInstall.ps1
- automatic/python2/tools/chocolateyInstall.ps1
> added scripts directory to Python2 install path

- automatic/smartftp/smartftp.nuspec
Added Google Cloud Storage to description.
> smartftp: updated description

- automatic/pspp/pspp.ketarin.xml
- automatic/pspp/pspp.nuspec
- automatic/pspp/tools/chocolateyInstall.ps1
@gep13 I have received a polite request to update this package from 2014. I'm now on Crete working on another project, so I've attempted to create an autopackage after hours without actually testing this on Windows. They obfuscate their paths a bit, but I think I've got the regexes worked out.
Could you be so kind as to see if this builds? If it does, it would be awesome if you could merge this and add it to the ketarin machine.
> Initial PSPP autopackage draft

- automatic/diskdefragtouch/diskdefragtouch.ketarin.xml
- automatic/diskdefragtouch/diskdefragtouch.nuspec
- automatic/diskdefragtouch/tools/chocolateyInstall.ps1
Works, but needs autoupdate on version or looks very outdated.
Ref for combining work: #219
> Initial commit

- automatic/lightworks/lightworks.ketarin.xml
- automatic/lightworks/lightworks.nuspec
- automatic/lightworks/tools/chocolateyInstall.ps1
:warning: important! Fixed dl urls
Ref for less work: #219
> :wrench: Lightworks new download url

- packages/wixtoolset/tools/chocolateyInstall.ps1
- packages/wixtoolset/tools/chocolateyUninstall.ps1
- packages/wixtoolset/wixtoolset.nuspec
* Bumping wixtoolset to latest version (_3.10.3.3007_)
* Changed the uninstall _{GUID}_ to the one found in my computer when installing 3.10.3 directly from [wixtoolset.org](http://wixtoolset.org).
> (wixtoolset) Updating to 3.10.3.3007

- automatic/chromium/chromium.nuspec
@gep13 Clarification of the install directory for those that may install this package in the future.
> Chromium Clarification of Package

- automatic/chromium/chromium.ketarin.xml
@gep13 Adding MD5 Checking for downloaded file.
> Ketarin File Update to MD5

- automatic/Clover/tools/chocolateyInstall.ps1
Fixes chocolateyInstall.ps1 from #280 (I think)
> Fix Clover install script

- packages/rdcman/rdcman.nuspec
- packages/rdcman/tools/chocolateyInstall.ps1
(already pushed to chocolatey.org)
> rdcman: add checksum, switch to HTTPS

- automatic/smartftp/tools/chocolateyInstall.ps1
use registry to find installed package
> SmartFTP: updated install script

- automatic/python3/python3.nuspec
- automatic/python3/tools/chocolateyInstall.ps1
- automatic/python3/update.ps1
> Python3 AU updater + fixes

- automatic/audacity/audacity.nuspec
- automatic/audacity/tools/chocolateyInstall.ps1
- automatic/audacity/update.ps1
- extensions/chocolatey-fosshub.extension/chocolatey-fosshub.extension.nuspec
- extensions/chocolatey-fosshub.extension/extensions/Get-UrlFromFosshub.psm1
@ferventcoder can you take a look at the following?  Thoughts?
> Updated Fosshub extension to latest requirements and test with audacity

- automatic/chromium/tools/chocolateyUninstall.ps1
- automatic/chromium/update.ps1
The Uninstall file is fixed to correct its issue of not Uninstalling, and Update is updated to take advantage of the changes that will be taking place in the API for Chromium
> Chromium Fix & Update for future

- automatic/kb2999226/kb2999226.nuspec
- kb2999226/tools/chocolateyinstall.ps1
@gep13 
A member on the gitter channel still really needs this package as a dependency for their package. This package was not in the chocolatey community feed. It has been tested and works. It will install the KB if not already installed, and skips install if already installed. Since it is a Microsoft KB no uninstaller in needed. The package should not need updating because it is static. Thank you for considering this package for the community feed.
> Proposal of package kb2999226

- automatic/codelite/codelite.nuspec
- automatic/codelite/tools/chocolateyInstall.ps1
- automatic/codelite/update.ps1
* Updated license url to their github repository
* Added project source url
* Added bug tracker url
* Added docs url
* Added mailing list url
* Updated description and summary
* Made au replace release notes on update
* Added Copyright
* Updated package source url
* Uninstall isn't completely silent, pops up a message box asking the user whether to
Remove user configuration or not. (Didn't want to handle this since I believe this is a decision
that should be made by the user).
@gep13 
***NOTE:*** to fix issue #252 the package can be packed and pushed as is, before running au.
***NOTE 2:*** The latest version (9.2.0) is currently in reject state.
> (codelite) Migrated to AU

- automatic/Firefox/Firefox.nuspec
- automatic/thunderbird/thunderbird.nuspec
- extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec
- extensions/chocolatey-core.extension/extensions/Get-WebContent.psm1
- extensions/chocolatey-fosshub.extension/chocolatey-fosshub.extension.nuspec
> (core extension) PowerShell v2 support

- automatic/chromium/tools/chocolateyInstall.ps1
- automatic/chromium/tools/chocolateyUninstall.ps1
@gep13 
Installer was updated to newer version; Install switch is now needed for the %appdata% install location.
[Uninstall was failing](https://gist.github.com/choco-bot/252bc75f383bab81697a010c88e24ab0#file-uninstall-txt-L261-L299), and This should now fix it 😃
> Chromium Install & Uninstall Fixes

- automatic/blender/blender.nuspec
- automatic/blender/tools/chocolateyInstall.ps1
- automatic/blender/tools/chocolateyUninstall.ps1
- automatic/blender/update.ps1
* Added update.ps1
* Updated chocolateyInstall.ps1
* Updated chocolateyUninstall.ps1 to use 'chocolatey-uninstall.extension'
* Updated license url
* Added project source url
* Added bug tracker url
* Added mailing list url
* Updated release notes url
* Added chocolatey-uninstall.extension dependency
**NOTE:** latest version (2.78) is in moderation, and needs to be updated.
> (blender) Migrated to AU

- automatic/audacity/audacity.nuspec
- automatic/avidemux/avidemux.nuspec
- automatic/codeblocks/codeblocks.nuspec
- automatic/mkvtoolnix/mkvtoolnix.nuspec
- automatic/qbittorrent/qbittorrent.nuspec
@majkinetor @AdmiringWorm we can pull this one in once the outstanding question about the core-extension has been answered.
> (fosshub) Updated depdendencies

- automatic/Cygwin/Cygwin.nuspec
- automatic/Cygwin/tools/chocolateyInstall.ps1
- automatic/Cygwin/tools/chocolateyUninstall.ps1
- automatic/virtualbox/tools/chocolateyInstall.ps1
- automatic/virtualbox/virtualbox.nuspec
Please check it out due to popularity of the package:
- Added bunch of parameters requested here and there (see commit message)
- Made it work with cyg-get again
- Made it able to use proxy
- Uninstaller will delete cygwin files
> Cygwin enhacements

- manual/googlechrome-extensions/googlechrome-github-expandinizr/googlechrome-github-expandinizr.nuspec
- manual/googlechrome-extensions/googlechrome-github-expandinizr/tools/chocolateyInstall.ps1
- manual/googlechrome-extensions/googlechrome-github-expandinizr/tools/chocolateyUninstall.ps1
- manual/googlechrome-extensions/googlechrome-github-expandinizr/tools/install_x64.reg
- manual/googlechrome-extensions/googlechrome-github-expandinizr/tools/install_x86.reg
@bcurran3 does this look like it should work to you?
I have tried to install it, but nothing seems to happen.
> (expandinizr) Added new package

- automatic/smartftp/README.md
Added readme with original package maintainer.
> smartftp: added readme

- automatic/php/php.nuspec
- automatic/php/tools/chocolateyInstall.ps1
- automatic/php/tools/chocolateyUninstall.ps1
- automatic/php/tools/helpers.ps1
- automatic/php/update.ps1
- icons/php.svg
Note: Due to vcredist dependency testing requries ~700MB downloads.
> (new package) Php

- automatic/smartftp/smartftp.nuspec
KB2533623 is only required on Windows 7 and Windows Server 2008 R2.
Note: package author update
> smartftp: added KB2533623 dependency

- manual/vcredist2017/README.md
- manual/vcredist2017/tools/chocolateyInstall.ps1
- manual/vcredist2017/tools/chocolateyUninstall.ps1
- manual/vcredist2017/vcredist2017.nuspec
migrated from https://github.com/jberezanski/ChocolateyPackages/tree/master/vcredist2017
version updated to 2017 RC
> migrated and updated vcredist2017 from jberezanski

- manual/kb2670838/Tools/ChocolateyInstall.ps1
- manual/kb2670838/kb2670838.nuspec
https://www.microsoft.com/en-us/download/details.aspx?id=36805
> Adds Windows kb2670838 - Platform update

- automatic/mkvtoolnix/mkvtoolnix.nuspec
- automatic/mkvtoolnix/tools/chocolateyInstall.ps1
- automatic/mkvtoolnix/update.ps1
No fix is needed, software updates quite frequently, and also this requires foshub extension fixed.
> (mkvtoolnix) Guidelines - Added to PATH - No Foshub [AU mkvtoolnix]

- automatic/virtualbox/tools/Start-ProcessNonElevated.ps1
- automatic/virtualbox/tools/chocolateyBeforeModify.ps1
- automatic/virtualbox/tools/chocolateyInstall.ps1
- automatic/virtualbox/tools/helpers.ps1
- automatic/virtualbox/update.ps1
- automatic/virtualbox/virtualbox.nuspec
https://github.com/chocolatey/chocolatey-coreteampackages/issues/423
> (virtualbox) GH-423

- automatic/nomacs.portable/nomacs.portable.nuspec
- automatic/nomacs.portable/tools/VERIFICATION.txt
- automatic/nomacs.portable/tools/chocolateyInstall.ps1
- automatic/nomacs.portable/update.ps1
- automatic/nomacs/nomacs.nuspec
- automatic/nomacs/tools/chocolateyInstall.ps1
- automatic/nomacs/update.ps1
This is ready except for proxy (see https://github.com/chocolatey/chocolatey-coreteampackages/issues/395#issuecomment-264851727). 
Waiting for feedback from authors on how to set it up since it uses online installer.
> (nomacs*) Guidelines (fixes #395)

- automatic/everything/Everything.nuspec
- automatic/everything/tools/License.txt
- automatic/everything/tools/VERIFICATION.txt
- automatic/everything/tools/chocolateyInstall.ps1
- automatic/everything/tools/chocolateyUninstall.ps1
- automatic/everything/update.ps1
Check it out (#443).
Notice the [Convert-ToEmbeded](https://github.com/chocolatey/chocolatey-coreteampackages/blob/9dc73656c3384c017e20957a3a3ced12dda8c71b/automatic/everything/update.ps1#L21-L48) function and how it is used. Perhaps somebody else will find it useful and if so, I may add it to AU.
> (everything) new package

- automatic/visualstudiocode/update.ps1
Add missing import for extensions in update script of Visual Studio Code
Fixes #472
> (visualstudiocode) Fix update script

- automatic/tor-browser/tor-browser.nuspec
Update nuspec to be conform with core team guidelines
> (tor-browser) Update nuspec to guidelines

- automatic/flashplayerplugin/update.ps1
@gep13 
The original version of getting the Current Version was not working anymore
Also Adobe changed the URL to include the Current Version in the link
> (Adobe Flash Player) Current Version needs to be updated

- automatic/flashplayerppapi/tools/ChocolateyUninstall.ps1
@gep13 @AdmiringWorm 
Missed file for name change
> Flash Player PPAPI missed file

- automatic/flashplayerppapi/update.ps1
Fix AU error by returning version from au_GetLatest
> (Flashplayerppapi) Fix AU script

- manual/vscode-extensions/vscode-csharpextensions/vscode-csharpextensions.nuspec
Update metadata according to the guidelines
> (vscode-csharpextensions) Update according to the guidelines

- extensions/chocolatey-core.extension/CHANGELOG.md
- extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec
- extensions/chocolatey-core.extension/extensions/Get-UninstallRegistryKey.ps1
> (core.extension) Get-UninstallRegistryKey: PowerShell 2 compatibility

- automatic/nodejs/nodejs.nuspec
Don't add update.ps1 to Chocolatey package
> Remove update.ps1 from package

- automatic/putty.install/update.ps1
- automatic/putty.portable/update.ps1
- automatic/putty/update.ps1
Should fix the failing PuTTY packages
> (putty*) Update AU script for changes on website and make more robust

- automatic/qtox/legal/LICENSE.txt
- automatic/qtox/legal/VERIFICATION.txt
- automatic/qtox/qtox.nuspec
- automatic/qtox/tools/chocolateyInstall.ps1
- automatic/qtox/update.ps1
Fixes the error in the AU script and change to an embedded package
> (qtox) Update AU script and change to an embedded package

- automatic/clementine/clementine.nuspec
- automatic/clementine/legal/LICENSE.txt
- automatic/clementine/legal/VERIFICATION.txt
- automatic/clementine/tools/chocolateyInstall.ps1
- automatic/clementine/tools/chocolateyUninstall.ps1
- automatic/clementine/update.ps1
Feel free to squash all commits on merge.
> (clementine) Changed to embedded package

- automatic/visualstudiocode/visualstudiocode.nuspec
- manual/visualstudiocode-disableautoupdate/tools/chocolateyInstall.ps1
- manual/visualstudiocode-disableautoupdate/tools/chocolateyUninstall.ps1
- manual/visualstudiocode-disableautoupdate/tools/helpers.ps1
- manual/visualstudiocode-disableautoupdate/visualstudiocode-disableautoupdate.nuspec
Disable auto update by default. Added "EnableAutoUpdate" parameter for enable auto update
> (visualstudiocode) Disable auto update by default

- automatic/lightalloy/lightalloy.nuspec
- automatic/lightalloy/tools/chocolateyInstall.ps1
- automatic/lightalloy/tools/lightalloy.au3
- automatic/lightalloy/update.ps1
:warning: __Do not merge yet, broken__ 
:information_source: No fosshub dependency
I'm trying to create a package for `lightalloy` and I'm getting some errors I don't expect/understand.
```
lightalloy - checking updates using au version 2017.1.14
nuspec version: 4.8.8.20161201
remote version: 4.9.2
New version is available
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\au\Public\Update-Package.ps1:346 char:98
+ ... *' } | select -First 1 | % { $Latest[$_] } | split-Path -Leaf) -match ...
+                                                  ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
+ FullyQualifiedErrorId : …
```
> Added lightalloy

- automatic/PDFCreator/PDFCreator.nuspec
- automatic/PDFCreator/tools/chocolateyInstall.ps1
> (pdfcreator) Fixed print spool not running on install

- automatic/flashplayerplugin/update.ps1
Adding IE Cookie Setting code to the Beginning, and a removal of the Setting at the End of the `GetLatest` function. Also added a Close to the IWR request #382 
This should remedy the "Vector Smash" error for this Package
@gep13 @AdmiringWorm @pascalberger
> FlashPlayerPlugin AU Update

- automatic/sysinternals/sysinternals.nuspec
- automatic/sysinternals/tools/chocolateyInstall.ps1
- automatic/sysinternals/tools/helpers.ps1
- automatic/sysinternals/update.ps1
Also removed duplicate urls/checksums that isn't needed.
Required to merge with `[AU sysinternals]` in the merge title
> (sysinternals) Added support for nano server

- automatic/qbittorrent/qbittorrent.nuspec
- automatic/qbittorrent/tools/VERIFICATION.txt
- automatic/qbittorrent/tools/chocolateyinstall.ps1
- automatic/qbittorrent/update.ps1
> (qbittorrent) Add support for 64-bit installer

- manual/wixtoolset/tools/chocolateyInstall.ps1
- manual/wixtoolset/tools/chocolateyUninstall.ps1
- manual/wixtoolset/wixtoolset.nuspec
Bumps to 3.11 RC for VS2017 integration.
> (wixtoolset) Bump version to 3.11

- manual/wixtoolset/tools/chocolateyInstall.ps1
add checksum to the newest wix package....
I'm not sure what you will have to do to add this package since it already exists in chocolatey, but since this org is chocolatey I'm sure you can use super admin powerz
> (wixtoolset) add checksum to wix package

- automatic/waterfox/update.ps1
@AdmiringWorm @gep13 @pascalberger 
The current Regex  will fail for the newest version. This Regex will help to also future proof the update script in the future.
> (Waterfox) Regex Change

- extensions/chocolatey-core.extension/CHANGELOG.md
- extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec
- extensions/chocolatey-core.extension/extensions/Get-EffectiveProxy.ps1
> (core.extension) Get-EffectiveProxy

- automatic/nomacs.portable/README.md
- automatic/nomacs.portable/update.ps1
- automatic/nomacs/README.md
- automatic/nomacs/nomacs.nuspec
- automatic/nomacs/tools/chocolateyInstall.ps1
- automatic/nomacs/tools/install-script.js
- automatic/nomacs/update.ps1
> (nomacs*) added readme.md; added proxy

- automatic/Opera/tools/chocolateyInstall.ps1
- automatic/Opera/tools/helpers.ps1
- automatic/Opera/update.ps1
> (opera) Fixed version parsing and included 64bit

- manual/svg-explorer-extension/Readme.md
- manual/svg-explorer-extension/legal/LICENSE.txt
- manual/svg-explorer-extension/legal/VERIFICATION.txt
- manual/svg-explorer-extension/svg-explorer-extension.nuspec
- manual/svg-explorer-extension/tools/chocolateyInstall.ps1
- manual/svg-explorer-extension/update.ps1
> (svg-explorer-extension) Embedded package

- automatic/7zip.install/7zip.install.nuspec
- automatic/7zip.install/Changelog.md
- automatic/7zip.install/tools/chocolateyInstall.ps1
- automatic/7zip.install/update.ps1
- scripts/Update-ChangelogVersion.ps1
- scripts/au_extensions.psm1
> (7zip.install) Added changelog + helper to update the changelog version on update

- manual/virtualdub/virtualdub.nuspec
In my recent PR, I overlooked adding the legal folder to nuspec; minor correction
> (virtualdub) add legal folder to nuspec!

- manual/kb2999226/kb2999226.nuspec
- manual/kb2999226/tools/chocolateyinstall.ps1
Also add missing release notes for previous version.
> (kb2999226) fix KB id in install script

- automatic/dropbox/dropbox.nuspec
- automatic/dropbox/tools/chocolateyinstall.ps1
- automatic/dropbox/update.ps1
Reverted the version to the stable version
Added error checking for Dropbox process
> (Dropbox) Couple of small fixes

- automatic/dropbox/update.ps1
- automatic/dropbox/update_helper.ps1
Update to dropbox  to always have the correct stable version, and to allow for the dropbox-beta package in the future
@AdmiringWorm 
I might have at least lowered the time to **_2 min 52 sec_**
> (dropbox) update for stable version

- automatic/notepadplusplus.install/tools/chocolateyInstall.ps1
Fix an error where a wildcard pattern is being used instead of a regex
pattern when calling Get-AppInstallLocation.
softwareName should have stayed as the regex pattern-based string ("notepad++") instead of the wildcard pattern-based ("Notepad++*") because the called function that uses the parameter is Get-AppInstallLocation ... and the description for the first $AppNamePattern argument to that Get-AppInstallLocation function is "Regular expression pattern". The Install-ChocolateyPackage function doesn't use the "softwareName" argument key as far as I can tell, so it is only used for getting the apps install location after installation has completed.  (More details in the submitted issue related to this.)
Issue submitted for this: …
> (notepadplusplus.install) Fix error pattern match

- automatic/dropbox/update_helper.ps1
@AdmiringWorm @gep13 @pascalberger 
This is a condensed code fix of the dropbox update_helper file. This will allow the dropbox package to check the version with the dropbox forum and verify if that version is a stable build.
This cleans up the rushed coding job I did previously. The code is now condensed, and still readable 😄 
Tested in Appveyor and locally, and all changes work with the given file being the only change.
> (dropbox) update_helper file changes

- automatic/ffmpeg/README.md
- automatic/ffmpeg/ffmpeg.nuspec
- automatic/ffmpeg/tools/chocolateyInstall.ps1
- automatic/ffmpeg/update.ps1
> (ffmpeg) added README.md; remove older install dirs

- automatic/smartftp/smartftp.nuspec
updated vcredist from version 14.10.25008.0 to 14.10.25017.0
> smartftp: updated vcredist version

- automatic/dropbox/update_helper.ps1
@AdmiringWorm @majkinetor @gep13 @pascalberger 
Update to fix the unspecified version error in the gist reports
This will fix the [`Invalid version: 31.4.2529.4.2029.4.20`](https://gist.github.com/gep13/bd2eaa76f2a9ab739ca0544c502dca6e) that has popped up in the last few gist reports
Dropbox forum changed the listing of the latest versions.
> (dropbox) Update to update_helper file due to forum changes

- .appveyor.yml
@majkinetor @AdmiringWorm quick sanity check on this please?
> (maint) Updated choco version number

- automatic/winscp.install/update.ps1
Exclude RC versions from update
Fixes #823 
Tested locally
> (winscp*) Exclude RC versions from update

- automatic/nuget.commandline/update.ps1
Determine latest version from nuget.org and add support for pre-release versions
Fixes #820
Tested locally
> (nuget.commandline) Determine latest version from nuget.org

- automatic/smartftp/README.md
> (smartftp) Removing myself as maintainer

- automatic/tor-browser/tools/chocolateyInstall.ps1
access via system.security.accesscontrol.filesystemaccessrule - oops:
Access control entries (ACEs) are the individual rights inside of an ACL. An ACE can also be called a FileSystemAccessRule. This is a .NET object that has five parameters;
The security identifier ($Username);
The right (Modify);
Inheritance settings (ContainerInherit,ObjectInherit) which means to force all folders and files underneath the folder to inherit the permission we’re setting here;
Propagation settings (None) which is to not interfere with the inheritance settings;
Type (Allow).
> (tor-browser) Update chocolateyInstall.ps1

- automatic/opera/opera.nuspec
- automatic/opera/tools/chocolateyInstall.ps1
- automatic/opera/tools/helpers.ps1
- automatic/opera/update.ps1
> (opera) removed x32 bit check

- automatic/openssl.light/tools/chocolateyInstall.ps1
Some refactoring and fix for the issue
> (openssl) GH #873

- automatic/dropbox/update_helper.ps1
This should fix the invalid version issue that shows up every so often
@AdmiringWorm @pascalberger @gep13 
This should fix the invalid version issue
This has been tested in [Appveyor](https://ci.appveyor.com/project/RBZ/development)
> (dropbox_beta) Invalid Version Issue

- .appveyor.yml
- update_all.ps1
Per [Gitter discussion](https://gitter.im/chocolatey/chocolatey-coreteampackages) with @majkinetor and @AdmiringWorm, here are a couple of changes related to AU streams:
- ability to force update a specified stream: `[AU nodejs\8.9:8.9.0]`
- push all generated packages
> Support for AU streams

- CONTRIBUTING.md
Make clear that what column to use in MyUninstaller
> Make clear that what to use in MyUninstaller

- automatic/firefox/update_helper.ps1
@AdmiringWorm @majkinetor @gep13 
There is a change that has happened with the latest 57.0 version
The website might have changed, but this edit to the update helper script will again give a 64 bit url.
If it fixes an open issue, please link to the issue here.
**_Url_**` = "https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0`**_/win32_**`/${locale}/Firefox%20Setup%2057.0.exe"`
**_Url64_**` = "https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0/`**_win32_**`/${locale}/Firefox%20Setup%2057.0.exe"` 
`Firefox - checking updates using AU version 2017.8.30`
`Found redirected url 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0/win32/en-US/Firefox Setup 57.0.exe`
`URL check`
`nuspec version: 56.0`
`remote version: 57.0`
`New version is …
> (Firefox) update to get 64bit url

- automatic/typescript/Readme.md
- automatic/typescript/typescript.nuspec
- Fix spelling/typo
- mention this is a Node.js package
- Fixes #929
> (typescript) Fix 'Microsof' typo

- automatic/peazip.install/Readme.md
- automatic/peazip.install/legal/LICENSE.txt
- automatic/peazip.install/legal/VERIFICATION.txt
- automatic/peazip.install/peazip.install.nuspec
- automatic/peazip.install/tools/chocolateyinstall.ps1
- automatic/peazip.install/tools/chocolateyuninstall.ps1
- automatic/peazip.install/update.ps1
- automatic/peazip/Readme.md
- automatic/peazip/peazip.nuspec
- automatic/peazip/update.ps1
- icons/peazip.svg
See #910.
Just opened the PR that removes the package from the original location: https://github.com/dtgm/chocolatey-packages/pull/335
> (peazip*) migrated from dtgm

- automatic/krita/README.md
- automatic/krita/krita.nuspec
- automatic/krita/legal/LICENSE.txt
- automatic/krita/legal/VERIFICATION.txt
- automatic/krita/tools/chocolateyInstall.ps1
- automatic/krita/tools/chocolateyUninstall.ps1
- automatic/krita/update.ps1
- icons/krita.svg
Embedded, updated, modernized... Rewritten.
Package is outdated and unmaintained.
Testing environment.
- [Original Repository](https://github.com/dtgm/chocolatey-packages/)
> (krita) migrated from dtgm

- automatic/bleachbit.install/README.md
- automatic/bleachbit.install/bleachbit.install.nuspec
- automatic/bleachbit.install/legal/LICENSE.txt
- automatic/bleachbit.install/legal/VERIFICATION.txt
- automatic/bleachbit.install/tools/chocolateyInstall.ps1
- automatic/bleachbit.install/tools/chocolateyUninstall.ps1
- automatic/bleachbit.install/update.ps1
- automatic/bleachbit/README.md
- automatic/bleachbit/bleachbit.nuspec
- automatic/bleachbit/update.ps1
- icons/bleachbit.svg
Rewritten. Beta versions support  has been added.
Package lacks beta-versions support. Maintainer is not responsive. 
Also note that the latest (stable) release was almost 2 years ago.
Testing environment.
- [Original Repository](https://github.com/dtgm/chocolatey-packages/)
- [Open Issues](https://github.com/dtgm/chocolatey-packages/issues):
- None.
> (bleachbit*) migrated from dtgm

- automatic/kubernetes-cli/tools/chocolateyInstall.ps1
Fix software update problem
Add *-Force* parameter to Move-Item, otherwise error is thrown on software update.
Tested on local environment.
> (kubernetes-cli) Fix binary overwrite error

- automatic/screencloud/tools/chocolateyUninstall.ps1
Adds missing reference to the uninstall executable.
> (screencloud) Add missing uninstall file path

- .github/PULL_REQUEST_TEMPLATE.md
Updated with a few more fixes.
> Fixed typos in PR template

- automatic/firefox/tools/chocolateyInstall.ps1
Fixes a typo and removes a redundant word.
> (firefox) Improved message wording

- automatic/curl/update.ps1
@gep13 @AdmiringWorm @majkinetor @pascalberger 
The current website doesn't list 7z as a downloadable source anymore
Why is this change required? What problem does it solve?
package failing to update via AU
Tested locally via Latest _pre_ version of AU
> (curl) Update to latest version

- automatic/paint.net/paint.net.nuspec
Add dependency to KB2670838 
Will be required for 4.0.22 on Windows 7. For details see [here](https://blog.getpaint.net/2018/04/01/paint-net-4-0-22-and-windows-7-platform-update/)
Haven't tested as 4.0.22 is not yet out
> (paint.net) Add dependency to KB2670838

- automatic/argusmonitor/README.md
- automatic/argusmonitor/argusmonitor.nuspec
- automatic/argusmonitor/legal/LICENSE.txt
- automatic/argusmonitor/legal/VERIFICATION.txt
- automatic/argusmonitor/tools/chocolateyInstall.ps1
- automatic/argusmonitor/tools/chocolateyUninstall.ps1
- automatic/argusmonitor/update.ps1
Adds Argus Monitor.
https://www.argotronic.com/en/
Package doesn't exist.
Ran `update.ps1`, `Test-Package -Install` and `Test-Package -Uninstall`.
> (argusmonitor) New package

- automatic/vagrant/tools/chocolateyinstall.ps1
> (vagrant) add vagrant plugin repair

- automatic/1password/update.ps1
@gep13 @AdmiringWorm @majkinetor @pascalberger 
Adjustment of the fetching of the versions for the stream; Added the Before Update block to make for local use without errors/multi dependencies in the nuspec file; added the beta versions to the package.
This will fetch the OPW4, OPW7, & OPW7 beta versions. Since the latest link for OPW6 also is following the OPW7 listing. It is not listed but can be added should it diverge in the future.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
This fixes the issue #1048 
Please describe in detail how you tested your changes.
Tested locally and via Appveyor
- [Open Issues](link_to_the_generic_location_of_open_issues) …
> (1password) Update to fetch latest Versions & Beta

- manual/visualstudiocode-disableautoupdate/visualstudiocode-disableautoupdate.nuspec
Update dependency to new Visual Studio Code package
Dependency should be on new package to have it supporting up to date versions.
Not tested
> (visualstudiocode-disableautoupdate) Update dependency to new Visual Studio Code package

- manual/vscode-extensions/vscode-azurerm-tools/README.md
- manual/vscode-extensions/vscode-azurerm-tools/update.ps1
- manual/vscode-extensions/vscode-azurerm-tools/vscode-azurerm-tools.nuspec
- manual/vscode-extensions/vscode-csharpextensions/README.md
- manual/vscode-extensions/vscode-csharpextensions/update.ps1
- manual/vscode-extensions/vscode-csharpextensions/vscode-csharpextensions.nuspec
- manual/vscode-extensions/vscode-ember-cli/README.md
- manual/vscode-extensions/vscode-ember-cli/update.ps1
- manual/vscode-extensions/vscode-ember-cli/vscode-ember-cli.nuspec
- manual/vscode-extensions/vscode-ember-frost/README.md
- manual/vscode-extensions/vscode-ember-frost/update.ps1
- manual/vscode-extensions/vscode-ember-frost/vscode-ember-frost.nuspec
- manual/vscode-extensions/vscode-icons/README.md
- manual/vscode-extensions/vscode-icons/update.ps1
- manual/vscode-extensions/vscode-icons/vscode-icons.nuspec
Add README to VSCode extension packages, update dependency to new Visual Studio Code package name and update metadata where outdated and note about versioning.
Updates package to with current metadata
Not tested locally
> (vscode-*) Add README, update dependency and metadata

- automatic/qbittorrent/tools/chocolateyinstall.ps1
- automatic/qbittorrent/tools/chocolateyuninstall.ps1
- automatic/qbittorrent/update.ps1
This package is often cited as an example of good package. However, the way installation and update process was made was outdated. The architecture bitness was still detected manually, while Chocolatey+AU could do it via the `file` and `file64` statements.
We removed a bunch of unneeded stuff and cleaned the package to respect convention (legal file path, no semi colon, etc.)
Cleaning and avoid new comers to make issues when they check this package showcased as example.
Not tested. Waiting for CI build to complete.
> Clean qbittorrent package to respect convention

- automatic/keepassxc/README.md
Small typo. This is the SVG icon we uploaded not the PNG one.
Make the README work again.
Simply displayed the page.
> Use KeePassXC SVG icon version instead

- automatic/vscode/tools/ChocolateyInstall.ps1
- automatic/vscode/tools/helpers.ps1
- automatic/vscode/update.ps1
Before trying to install/upgrade check version number
Avoid closing/reinstalling vscode if user is trying to upgrade all packages and vscode has properly already updated because of background downloader.
Tested it with `choco pack` and `cinst --source . vscode -y -f`
Tried repacking it giving bogus vscode path and script proceeded to reinstalling.
> (vscode) Support version check

- automatic/sourcetree/update.ps1
Update release notes link for each version.
The current release notes link is outdated.
Tested update locally
> (sourcetree) Update link to release notes for each version

- automatic/gpg4win-light/README.md
- automatic/gpg4win-light/gpg4win-light.nuspec
- automatic/gpg4win-vanilla/README.md
- automatic/gpg4win-vanilla/gpg4win-vanilla.nuspec
- automatic/gpg4win/README.md
- automatic/gpg4win/gpg4win.nuspec
> fix typo: ligth -> light

- automatic/dropbox/update.ps1
@gep13 @AdmiringWorm @majkinetor @pascalberger 
Due to the latest versions of dropbox now having larger versioning numbers. The original version regex was having issues. This should fix the issue going forward until 4 digit versions are upon the dropbox package.
Why is this change required? What problem does it solve?
This [error](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#dropbox) has been showing up for the last few days.
Please describe in detail how you tested your changes.
Tested locally with the latest version of AU & Chocolatey
> (Dropbox) The remote server returned an error: (403) Forbidden

- automatic/libreoffice-streams/tools/chocolateyInstall.ps1
> (libreoffice-streams) added msi logging

- automatic/libreoffice-streams/libreoffice-streams.nuspec
LibreOffice is currently broken on the verifier because of a missing update. Ensure the update is present before performing the installation.
*The update will likely require a reboot extension from the verifier.*
LibreOffice was broken and the latest version was not available for users to enjoy.
Tested on Windows 10 + on the Windows Server 2012 R2 vagrant verifier box.
N/A
> [LibreOffice Streams] Fix dependency on new KB update (new msi requirements)

- automatic/ruby/update.ps1
Suppress downloading ruby with devkit because the order "with/without devkit" changed on the download page since version 2.5.1.
local
> (ruby) Update update.ps1

- manual/vcredist140/tools/data.ps1
- manual/vcredist140/vcredist140.nuspec
- manual/vcredist2017/vcredist2017.nuspec
on Win10 1803 x64: clean install, upgrade from 14.12.25810, uninstall
on Win7 SP1 x64: upgrade from 14.12.25810
> (vcredist140, vcredist2017) update to 14.15.26706

- automatic/nomacs.portable/update.ps1
- automatic/nomacs/update.ps1
> (nomacs*) Fix the update script

- automatic/datagrip/README.md
- automatic/datagrip/tools/ChocolateyInstall.ps1
- automatic/datagrip/tools/silent.config
- automatic/datagrip/update.ps1
* Changed the way datagrip is updated (faster, and use of SHA256 from upstream)
* Added silent installation file
* Added workaround for installer bug https://youtrack.jetbrains.com/issue/IDEA-202935
The installer is changed requires a silent answer file.
Added a workaround for a known bug in the installer: https://youtrack.jetbrains.com/issue/IDEA-202935 --> fixed in 2018.3.1
Tested using the chocolatey-test-environment
> (datagrip) Fix for 2018.3 version

- CONTRIBUTING.md
Fixed spelling and tweaked wording for readability in CONTRIBUTING.md
Made some spelling and readability changes in CONTRIBUTING.md
Reading through the contributing instructions earlier, I noticed a couple of misspelt words and a few spots where the grammar could be clearer.
I didn't log an issue as I considered it a minor/cosmetic change. I could log one if necessary?
No testing - documentation file.
> Fixed spelling and tweaked wording for readability in CONTRIBUTING.md

- automatic/dropbox/update_helper.ps1
@AdmiringWorm @majkinetor @gep13 
This should not be needed. The original code should be correct, but a bug prevents the current script from finding 63.4.102 version. This version is the latest stable version via the forum.
Due to a weird bug in PowerShell execution this fix is necessary. I noticed the bug when dropbox updated today with the Stable version being the same as the Beta version. 
This has been tested via Local AU and Appveyor
> (dropbox) Update to code so latest version is detected

- automatic/webstorm/README.md
- automatic/webstorm/tools/ChocolateyInstall.ps1
- automatic/webstorm/tools/silent.config
- automatic/webstorm/update.ps1
Fixed webstorm, 2018.3 and up requires a silent.config
Updated update.ps1 to improve speed
Added option to define installDir 
2018.3 and up requires a silent.config
Using local chocolatey-test-environment
> (webstorm) added silent.config and improved update source.

- automatic/ultradefrag/legal/LICENSE.txt
- automatic/ultradefrag/legal/VERIFICATION.txt
- automatic/ultradefrag/tools/chocolateyInstall.ps1
- automatic/ultradefrag/tools/chocolateyUninstall.ps1
- automatic/ultradefrag/ultradefrag.nuspec
- automatic/ultradefrag/update.ps1
This makes the package ultradefrag embedded.  I added legal folder (and added it to nuspec this time 🙃) with verification file and license and of course, made the update script embed installers.
> (ultradefrag) Embedded package

- automatic/php/README.md
- automatic/php/legal/LICENSE.txt
- automatic/php/legal/VERIFICATION.txt
- automatic/php/php.nuspec
- automatic/php/tools/chocolateyInstall.ps1
- automatic/php/tools/chocolateyUninstall.ps1
- automatic/php/tools/downloadInfo.csv
- automatic/php/tools/helpers.ps1
- automatic/php/update.ps1
This makes the package php embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages. From what I understood from conditions in license there also have to be one information attached, so I added it to package description:
> Redistributions of any form whatsoever must retain the following
acknowledgment:
"This product includes PHP software, freely available from
<http://www.php.net/software/>".
> (php) Embedded package

- automatic/tv-browser/legal/LICENSE.txt
- automatic/tv-browser/legal/VERIFICATION.txt
- automatic/tv-browser/tools/chocolateyInstall.ps1
- automatic/tv-browser/tools/chocolateyUninstall.ps1
- automatic/tv-browser/tv-browser.nuspec
- automatic/tv-browser/update.ps1
This makes the package tv-browser embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages.
// this is last PR for now, have a good night/day
I checked update.ps1, to see if it works properly, I tested the package in testing environment to see, if it installs and uninstalls properly. It seems that uninstallation isn't completely silent - there is a dialog asking if you want to remove app's data. However, I don't think there's a way to suppress it in this installer (NSIS).
> (tv-browser) Embedded package

- automatic/winpcap/README.md
- automatic/winpcap/legal/LICENSE.txt
- automatic/winpcap/legal/VERIFICATION.txt
- automatic/winpcap/tools/chocolateyInstall.ps1
- automatic/winpcap/tools/chocolateyUninstall.ps1
- automatic/winpcap/tools/winpcapInstall.ahk
- automatic/winpcap/update.ps1
- automatic/winpcap/winpcap.nuspec
This makes the package winpcap embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages. Also I updated README with information needed by license.
> (winpcap) Embedded package

- automatic/scribus/tools/chocolateyInstall.ps1
- automatic/sparkleshare/legal/LICENSE.txt
- automatic/sparkleshare/legal/VERIFICATION.txt
- automatic/sparkleshare/sparkleshare.nuspec
- automatic/sparkleshare/tools/chocolateyInstall.ps1
- automatic/sparkleshare/update.ps1
- automatic/tv-browser/tools/chocolateyInstall.ps1
- automatic/ultradefrag/tools/chocolateyInstall.ps1
This makes the package sparkleshare embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages.
> (sparkleshare) Embedded package

- automatic/python2/legal/LICENSE.txt
- automatic/python2/legal/VERIFICATION.txt
- automatic/python2/python2.nuspec
- automatic/python2/tools/chocolateyInstall.ps1
- automatic/python2/update.ps1
This makes the package python2 embedded. I added legal folder with verification file and license and edited update script, so it embeds the packages.
> (python2) Embedded package

- automatic/mp3tag/tools/ChocolateyUninstall.ps1
- automatic/mp3tag/update.ps1
This adds support for beta versions of mp3tag to update script. As a releases url it uses forum post by developer, which is edited on every update with either stable or beta version (indicated by "Status" in post).
Also, starting with version 2.91h (beta), uninstall can be silent, so I added chocolateyUninstall.ps1 for that.
I'm sure some people use beta versions of this app to have most recent functionality.
I tested if update script works (I also used one of older edits of the post, with stable status and it works as well. After that I tested the package in chocolatey test environment to see if package install and uninstall properly and silently.
> (mp3tag) Support for beta versions

- automatic/libreoffice-streams/README.fresh.md
- automatic/libreoffice-streams/README.md
- automatic/libreoffice-streams/README.still.md
Describe the package purpose as per new upstream description.
Consistency.
N/A
N/A
- [] My change requires a change to documentation (this usually means the notes in the description of a package).
> Update libreoffice readme as per new upstream description

- extensions/chocolatey-vscode.extension/CHANGELOG.md
- extensions/chocolatey-vscode.extension/README.md
- extensions/chocolatey-vscode.extension/chocolatey-vscode.extension.nuspec
- extensions/chocolatey-vscode.extension/extensions/Install-VsCodeExtension.ps1
- extensions/chocolatey-vscode.extension/extensions/Uninstall-VsCodeExtension.ps1
- extensions/chocolatey-vscode.extension/extensions/chocolatey-vscode.psm1
Create a new extension for managing Visual Studio Code extensions.
Provides robust routines for installing and uninstalling Visual Studio Code extensions which can be used in specific packages.
Requires also Core extension to be added as a dependency.
Fixes part of #500 
Tested locally
> Add chocolatey-vscode.extension

- automatic/firefox/update_helper.ps1
Fix for Firefox ESR.
Now download
https://download.mozilla.org/?product=firefox-60.5.2esr-ssl&os=win64&lang=de
instead of
https://download.mozilla.org/?product=firefox-esr-60.5.2-ssl&os=win64&lang=de
which does not exist, see:
https://gist.github.com/choco-bot/8f0e1afa351906d4e583b95bbe8f11d0
> (FirefoxESR) Update update_helper.ps1

- automatic/googlechromebeta/googlechromebeta.nuspec
- automatic/googlechromebeta/tools/chocolateyInstall.ps1
- automatic/googlechromebeta/update.ps1
Better testing of the auto-update code so the code will now handle more scenarios.
Update package to v73.0.3683.67
Bug fix
> (googlechromebeta) - bug fix

- manual/vscode-extensions/vscode-icons/vscode-icons.nuspec
Update minimum required Visual Studio Code version
Update minimum required Visual Studio Code version as documented on [extension page](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)
Not tested
> (vscode-icons) Update minimum required Visual Studio Code version

- automatic/brave/brave.nuspec
> (brave) Remove unused AHK dependency

- automatic/dropbox/tools/chocolateyinstall.ps1
- automatic/dropbox/update.ps1
@AdmiringWorm @majkinetor @gep13 
This will fix Issue #1270 
Due to a Posh v3 variable used that defaults to null in Posh v2 systems. Changed to use same variable if not defined. Fixed the version check to check for pre version suffix and remove it.
> (dropbox) issue with helper.ps1 (#1272) [AU dropbox]

- automatic/sourcetree/update.ps1
- automatic/sourcetree/update_helper.ps1
@pascalberger @AdmiringWorm 
This will fix the `update.ps1` file to read the JavaScript generated website for the Sourcetree application.
This uses a helper function to read the JavaScript generated website page and parse it with powershell.
This fixes Issue #1261 
Recycle of the helper script in package wps-office-free
> (sourcetree) Fixes Issue #1261

- automatic/gpg4win/README.md
- automatic/gpg4win/gpg4win.nuspec
Couldn't use the provided example until I read https://chocolatey.org/docs/how-to-parse-package-parameters-argument#step-2---add-package-parameters-to-the-description
I just ran `choco install gpg4win --version=3.1.6 --package-parameters="/Config:C:\path\to\gpg4win.ini"` and watched in Process Hacker the command line passed to `gpg4win-3.1.6.exe`. I saw `gpg4win-3.1.6.exe /S /C=C:\path\to\gpg4win.ini`
None of the above since it's just a typo.
> gpg4win: fix example when using config file

- automatic/sourcetree/update_helper.ps1
Update release notes to current URL
URL of release notes have changed
Tested locally
> (sourcetree) Update release notes URL

- automatic/paint.net/paint.net.nuspec
Fixes #1299 
Tested on local test environment
> (paint.net) Update dependencies

- automatic/kitty/legal/VERIFICATION.txt
New download locations for KiTTY executables
The download location for KiTTY files is changed. 
The current version V.071.0.6 causes errors and all the KiTTY tools cannot be used.
Changed the links to the most recent files and checked if the link would provide the right file
> New download location for KiTTY executables

- extensions/chocolatey-azuredatastudio.extension/CHANGELOG.md
- extensions/chocolatey-azuredatastudio.extension/README.md
- extensions/chocolatey-azuredatastudio.extension/chocolatey-azuredatastudio.extension.nuspec
- extensions/chocolatey-azuredatastudio.extension/extensions/Install-AzureDataStudioExtension.ps1
- extensions/chocolatey-azuredatastudio.extension/extensions/Uninstall-AzureDataStudioExtension.ps1
- extensions/chocolatey-azuredatastudio.extension/extensions/chocolatey-azuredatastudio.psm1
A new extension for packages which install Azure Data Studio extensions. Similar to the `chocolatey-vscode.extension`.
Simplifies authoring of Chocolatey package which install Azure Data Studio extension.
Tested locally with different installations of Azure Data Studio.
> (chocolatey-azuredatastudio.extension) Add new extension for Azure Data Studio extensions

- automatic/avidemux/tools/avidemux.qs
- automatic/avidemux/tools/chocolateyInstall.ps1
- automatic/avidemux/tools/chocolateyUninstall.ps1
- automatic/avidemux/update.ps1
Added QT script for automating the new 64bit installer (and uninstaller)
fixes #1322
> (avidemux) Avidemux new installer

- automatic/putty/README.md
Resolves #1293
This is just a simple English grammar fix.
---
**P.S.:** You might want to come up with a better commit name when merging.
review?(@majkinetor)
> docs(putty): Fix wording of f4f1f9e4459742d28fcffb7103b8c7d85dcd8910

- automatic/ffmpeg/update.ps1
ffmpeg added a new static build of lgpl this will not detect it
This will fix a update [issue](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors) due to a new build being released.
> (ffmpeg) Update issue

- automatic/notepadplusplus/update.ps1
This is due to a change on the Owners website. This fixes issue [here](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors)
> (notepad plus plus) update issue

- automatic/apache-httpd/tools/helpers.ps1
Fixed the non-Powershell v2 compatibility comlet of Get-NetTCPConnection
@majkinetor @AdmiringWorm @gep13 
This solution uses netstat for retrieval of the information requested using the windows 8 or newer system comlet of Get-NetTCPConnection. Has been tested on a windows 7 machine.
> (apache-httpd) Fixed compatibility with Powershell v2

- automatic/msys2/tools/chocolateyinstall.ps1
- automatic/msys2/tools/helpers.ps1
Replacement for PR #1346 which is the same as abandoned one #1296
Fixes issue #1286.
/cc @diablodale @mkevenaar @floh96 @cprivite
> (msys2) fix and tidy up installer

- PSScriptAnalyzerSettings.psd1
This adds a [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) settings file.
**PSScriptAnalyzer** is the [ESLint](https://eslint.org) of the PowerShell world.
It has lint rules that help prevent issues like #828 from happening in the first place.
It also has native integration in **VS Code**, which provides squiggly lines for detected issues.
I’ve been using this configuration for a while.
Note that this currently isn’t run in CI, as I don’t really know how to do that with AppVeyor, and I use **VS Code**’s **PSScriptAnalyzer** integration.
> chore: Add `PSScriptAnanlyzerSettings.psd1`

- automatic/python3/README.md
- automatic/python3/tools/chocolateyInstall.ps1
> (python3) add test for installdir

- automatic/alldup/alldup.nuspec
- automatic/alldup/tools/chocolateyInstall.ps1
- automatic/gpg4win/README.md
- extensions/chocolatey-core.extension/CHANGELOG.md
- extensions/chocolatey-core.extension/chocolatey-core.extension.nuspec
- extensions/chocolatey-core.extension/extensions/Remove-Process.ps1
> Added Remove-Process to extensions; Test with alldup

- automatic/vim/tools/chocolateybeforemodify.ps1
- automatic/vim/tools/chocolateyinstall.ps1
- automatic/vim/tools/chocolateyuninstall.ps1
- automatic/vim/tools/helpers.ps1
- automatic/vim/update.ps1
Delete old version and turn them into symlinks to new version.
Overwrite old version's directory with symlink to new version's directory.
When there are already symlinks, relink it.
This example illustrates my aim:
```
**First install
C:\tools\vim\vim80
**Updated to vim81
C:\tools\vim\vim80 -> vim81
C:\tools\vim\vim81
**Updated to vim82
C:\tools\vim\vim80 -> vim82
C:\tools\vim\vim81 -> vim82
C:\tools\vim\vim82
```
Current vim package doesn't delete old version when minor version upgraded.
Vim's minor version has updated recently, and now most users have two versions on their machine.
```
**Current situation
C:\tools\vim\vim81
C:\tools\vim\vim82
```
This is actually my mistake. I overlooked this upgrade scenario when I fixed this package.
This change turns `vim81` into symlink to `vim82` …
> (vim)Symlink to new version

- automatic/audacity/update.ps1
Signed-off-by: Jerome Benoit <jerome.benoit@sap.com>
Switch audacity update script to an up to date download site. 
- Fixed issues:
> (Audacity) Switch audacity update script to use fossies.org.

- automatic/wps-office-free/wps-office-free.nuspec
Update description of wps-office-free
> (wps-office-free) Update metadata

- automatic/chromium/update.ps1
Updated for New API, spacing, and stable
@gep13 @AdmiringWorm @majkinetor @pascalberger 
This will update the chromium package to the latest stable and snapshot version using @woolyss API v5. The coding is in place should chocolatey want to use the stable arm version as a package in the future.
The issue #1392 was brought up and this will fix the issue.
Local repo, and appveyor
> (chromium) Stable and Snapshots update

- automatic/julia/tools/chocolateyinstall.ps1
- automatic/julia/tools/chocolateyuninstall.ps1
The Julia installer has changed on 1.4.0. `/S` no longer silences the installer, causing the installation to [hang and eventually fail](https://gist.github.com/choco-bot/6b7df821f5bf3c3a990d67c4ddec0a48). This fix changes the silent installation argument from `/S` to `/VERYSILENT`.
Tested locally.
> (julia) fix silent install argument

- automatic/gimp/update.ps1
@AdmiringWorm @gep13 @pascalberger @majkinetor 
Fixes the whole sub-revision issue.
Fixes issue #1464 
> (gimp) This will update the package for minor version releases

- automatic/msys2/legal/VERIFICATION.txt
- automatic/msys2/msys2.nuspec
- automatic/msys2/update.ps1
32 bit version removed from upstream
> (msys2) removed 32 bit variant

- automatic/gimp/update.ps1
@AdmiringWorm @gep13 @pascalberger @majkinetor 
Fix of the regex to not be so restrictive, and will allow RC builds. I went through gimp's old download archive. The only pre-releases found had the RC designation. I updated this regex to allow those to be in the version. These RC builds were also x64 builds, but even that in the file name didn't cause a version conflict.
> (gimp) Update to the update regex

- automatic/cutepdf/update_helper.ps1
@AdmiringWorm @gep13 @pascalberger @majkinetor 
This will fix the issue of the minor release with the same version numbers.
The current version of the package on the community feed is outdated. This will update to the latest version, and add padding if the version is the same. It might take 24hrs but the package with auto update.
> (cutepdf) Will fix the new version with same version issue

- automatic/wps-office-free/update_helper.ps1
url needs to be changed to the new one
@AdmiringWorm @majkinetor  @gep13 
The Url needs to be updated to the newer url. This will make it so the package will update again in the future.
Failure to update
> (wps-office-free) Url Update

- automatic/vscode.install/README.md
- automatic/vscode.install/tools/helpers.ps1
- automatic/vscode.install/vscode.install.nuspec
Make vscode.install able to associate with supported files
Current package doesn't support associating with supported files
Not tested
> (vscode.install) Make package able to associate with supported files

- automatic/inkscape/tools/chocolateyInstall.ps1
Upstream changed the location of inkscape.exe for version 1.0
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this repository.
- [x ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
> Updated the location of inkscape.exe

- automatic/nomacs/legal/VERIFICATION.txt
- automatic/nomacs/tools/chocolateyInstall.ps1
Cleanup 32bit leftovers from GH-1491
> (nomacs) cleanup unused 32bit artifact handling

- automatic/avidemux/legal/VERIFICATION.txt
- automatic/avidemux/tools/chocolateyInstall.ps1
- automatic/avidemux/update.ps1
to support unmatched releases
#1480 
Raw PS-tested/Not tested
> (avidemux) Update update.ps1

- automatic/dropbox/tools/chocolateyinstall.ps1
- automatic/dropbox/tools/chocolateyuninstall.ps1
- automatic/dropbox/update.ps1
- automatic/dropbox/update_helper.ps1
@AdmiringWorm @gep13 @majkinetor @pascalberger 
This will update the package updater to use Get-Version instead of a regex to find the newest version from the source url. This change will also allow the helper to have a up to date regex for the getting of versions from the dropbox forums.
This also changes the spacing to be more uniform.
Package outdated due to the older update regex failing to provide the correct version from the source url #1504 
Local Windows 10 AU and a [Appveyor](https://ci.appveyor.com/project/RBZ/development/builds/34035240)
> (dropbox) regex and spacing updates

- automatic/brave/brave.nuspec
- automatic/brave/update.ps1
Correction of the icon, the verifier refused the package because of it.
> (brave) icons url update to solve the verifier error

- .github/CODEOWNERS
- automatic/kubelogin/README.md
- automatic/kubelogin/kubelogin.nuspec
- automatic/kubelogin/legal/LICENSE.txt
- automatic/kubelogin/legal/VERIFICATION.txt
- automatic/kubelogin/tools/chocolateyInstall.ps1
- automatic/kubelogin/update.ps1
Added a new package 😅
fixes #1511 
`choco install kubelogin`
```powershell
> choco install -s . kubelogin
> Get-Command kubelogin
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     kubelogin.exe                                      0.8.1.0    C:\ProgramData\chocolatey\bin\kubelogin.exe
> kubelogin --version
kubelogin version v1.20.0
```
> (kubelogin) add package for kubelogin cli

- automatic/kubelogin/kubelogin.nuspec
Fixed icon url check
`choco install kubelogin`
🤷‍♂️
> (kubelogin) skip icon url check

- automatic/winscp.install/tools/chocolateyInstall.ps1
- automatic/winscp.install/tools/chocolateyUninstall.ps1
@AdmiringWorm @majkinetor  @gep13 @pascalberger @wget 
This will add a shim to the `WinSCP.com` file.  The created shim will be referenced by `WinSCP.com.exe` when created.
This will create and remove the shim for `WinSCP.com`. This is an additional help for those that use this program from the cmd/posh shell
This is to fix the issues #1134 and #1412 
This has been tested locally (Win 10 build 2004)
> (winscp.install) Un/Install Shim for winscp.com for cmd/posh usage

- automatic/supertuxkart/update.ps1
@AdmiringWorm @gep13 @majkinetor @wget @pauby 
This will get the latest version of the program now currently released.
> (supertuxkart) Update fix for latest version

- automatic/lightworks/lightworks.nuspec
@AdmiringWorm  @gep13 @majkinetor 
This updated the author for this software as requested by issue #1544 
> (lightworks) updated the author of the software

- automatic/nodejs.install/tools/chocolateyInstall.ps1
add logging as asked here https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chocolatey-community/chocolatey-coreteampackages/1543)
> (nodejs.install) log installation

- automatic/notepadplusplus/update.ps1
@AdmiringWorm @gep13 @majkinetor @pascalberger 
This will update the package(s) to the latest version which is causing [Errors in the update status](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors).
The community wanting to help with PR #1549 that updates all files manually, and since `AU` updated packages don't work this way. I thank @TreyRuffy for his effort.
Local AU installation
> (notepadplusplus) Update for the changed due to new version

- automatic/youtube-dl/legal/VERIFICATION.txt
- automatic/youtube-dl/update.ps1
- automatic/youtube-dl/youtube-dl.nuspec
Change to download Youtube-DL self-contained Python script from official Youtube-DL site, some updates to metadata (copyright/license etc).
Youtube-DL Github repository has been attacked, but package is still available from official Youtube-DL site (which has consistently displayed the version format and exe link for several years).
Tested on Vagrant per chocolatey-test-environment.
> Youtube-DL package update

- automatic/chromium/tools/chocolateyInstall.ps1
@AdmiringWorm @gep13 @majkinetor @pascalberger @pauby 
This is needed due to a bug that is still in the stable version of the package #1566
Issue #1566 
Tested Locally with AU and install computer
> (chromium) update the detritus cleanup of the install

- automatic/nmap/nmap.nuspec
- automatic/nmap/tools/chocolateyInstall.ps1
- automatic/nmap/tools/install.ahk
- automatic/nmap/update.ps1
> (nmap) ahk installer

- automatic/php/update.ps1
PHP 8.0.0 dependency update
Update PHP package
Need to test
> Update dependency for PHP 8.0.0

- automatic/php/php.nuspec
- automatic/php/update.ps1
This PR reverts the dependency change for PHP in #1585 from `visualstudio2019buildtools` to `vcredist140`.
This fixes #1587. 
`visualstudio2019buildtools` is not required for installing PHP runtime. `vcredist140`, which was being used for previous versions of PHP is sufficient and correct dependency for PHP 8.0.0.
- `visualstudio2019buildtools` is not the correct dependency for PHP 8.0.0 while `vcredist140` is.
- This issue is also a blocker for installing PHP 8.0.0 on GitHub Actions/Azure windows environments as `visualstudio2019buildtools` conflicts with their VS setup. actions/virtual-environments#2170
Tested on clean `mcr.microsoft.com/windows/servercore:ltsc2019` and `mcr.microsoft.com/windows:2004` docker images.
If you see near the end of logs, php does not work until `vcredist140` …
> [PHP] Revert dependency for PHP 8.0.0 to vcredist140

- automatic/sourcetree/sourcetree.nuspec
Update license URL
Fixes #1605
URL tested in Browser. Otherwise not tested
> (sourcetree) Update license URL

- automatic/notepadplusplus.install/tools/chocolateyInstall.ps1
Cleanup must run directly after Install-ChocolateyInstallPackage
In case of issue with Get-AppInstallLocation cleanup won't run
No
> (notepadplusplus.install) Fix setup cleanup

- manual/vcredist2008/vcredist2008.nuspec
- manual/vcredist2010/README.md
- manual/vcredist2010/tools/chocolateyInstall.ps1
- manual/vcredist2010/vcredist2010.nuspec
- manual/vcredist2015/vcredist2015.nuspec
- imported vcredist2010 from https://github.com/MarkRobertJohnson/ChocolateyPackages
- cleaned up metadata and install script
- fixed reboot handling (https://github.com/MarkRobertJohnson/ChocolateyPackages/pull/16)
- updated to the latest version
The existing package on chocolatey.org started failing because Microsoft removed the (outdated) installers used by that package version.
Manually, in a Windows 10 2004 VM.
- [Original Repository](https://github.com/MarkRobertJohnson/ChocolateyPackages)
- [Open Issues](https://github.com/MarkRobertJohnson/ChocolateyPackages/pulls)
> (vcredist2010) Import and update to newest version

- automatic/ffmpeg-full/README.md
- automatic/ffmpeg-full/ffmpeg-full.nuspec
- automatic/ffmpeg-full/legal/LICENSE.txt
- automatic/ffmpeg-full/legal/VERIFICATION.txt
- automatic/ffmpeg-full/tools/chocolateyInstall.ps1
- automatic/ffmpeg-full/update.ps1
- automatic/ffmpeg/README.md
- automatic/ffmpeg/ffmpeg.nuspec
- automatic/ffmpeg/legal/VERIFICATION.txt
- automatic/ffmpeg/update.ps1
- Adds package `ffmpeg-full` to install the `full build` of ffmpeg, whereas the `ffmpeg` package just installs the `essentials build`
- update descriptions of `ffmpeg` package to note that this is just installing the `essentials build`
- update the `update.ps1` script to use [this version info](https://www.gyan.dev/ffmpeg/builds/release-version) to check for the latest version (bugfix)
For video heavy work environments it is helpful to have the full ffmpeg build with support for all possible codecs and features.
The maintainer of the remote decided to remove the build date from the version, so installing older versions with the same script is expected to fail.
- Set up this [chocolate-test-environment](https://github.com/majkinetor/chocolatey-test-environment)
- did test for install, …
> Add ffmpeg-full and update ffmpeg

- automatic/displayfusion/update.ps1
Commented out invalid beta URL that now returns a 404 error.
Commented out invalid beta URL
Current AU package fails because beta URL is invalid.  New stable version was released on 5/4/21 but has not been packaged/pushed due to the invalid URL causing update script to fail 
Changes were tested in my AU environment using `.\test_all.ps1 displayfusion`
> (displayfusion) Update update.ps1

- automatic/minishift/README.md
- automatic/minishift/minishift.nuspec
Update description & README to clarify OpenShift compatibility.
Clarify tool compatibility.
No tests, only .nuspec update.
> (minishift) Update description & README to clarify OpenShift 3-only support

- .github/CODEOWNERS
- automatic/octave.portable/README.md
- automatic/octave.portable/octave.portable.nuspec
- automatic/octave.portable/tools/chocolateyInstall.ps1
- automatic/octave.portable/tools/chocolateyUninstall.ps1
- automatic/octave.portable/update.ps1
Add a new maintainer for the octave.portable package.
Add a new maintainer to address the [RFM request](chocolatey-community/chocolatey-package-requests/issues/990) by @abejenaru. While maintenance is being migrated the package has been updated to reflect current package contribution guidelines.
Specific changes made are:
* Minor formatting updates to README.md
* Include copyright handling for Nuspec updates
* Powershell script formatting and style changes
Fixes chocolatey-community/chocolatey-package-requests/issues/990
The updates to the package do not reflect any functional change.  Package has been tested by:
* Validating the package using cnc
* Resetting version numbers to force a package update followed by:
i)  Add and remove the built package in the Chocolatey test environment
ii) …
> (octave.portable) Add new package maintainer

- manual/lockhunter/lockhunter.nuspec
- manual/lockhunter/tools/chocolateyInstall.ps1
Updated LockHunter to 3.4.2
LockHunter 3.4.2 has been released at Apr 26th, 2021
https://blog.crystalrich.com/lockhunter-3-4-released/
Because only version in `lockhunter.nuspec`, version-part of url and checksum value in `chocolateyInstall.ps1` are changed,
so I only test the installation file can work fine with silentArgs on my Windows 10 x64
and the checksum are the same when I download the installation file on different machine.
> (lockhunter) Updated to 3.4.2

- automatic/k9s/k9s.nuspec
This should potentially fix #1714 issue - k9s update not being pushed to chocolatey package registry.
Resetting the version so it would be updated by automation and thus a new version pushed to the feed.
This should fix #1714.
The package update itself was tested with previous PR (see that linked issue for details). This should just force automation to update the package.
> (k9s) fix for package update not pushed to chocolatey feed

- CONTRIBUTING.md
Updated the CONTRIBUTING doc with the following changes:
* Update label URL's to work with new label names;
* Ensure all label URL's are consistent;
* Add CODEOWNERS step;
The labels were renamed and after speaking to @AdmiringWorm, the step to update the CODEOWNERS file is sometimes forgotten.
N/A
> (doc) Update contributing doc

- automatic/mono/Readme.md
- automatic/mono/mono.nuspec
Noticed that there was a typo in the spelling of `choco` in the package description, so thought I would correct it.
```
chocol -> choco
```
Once seen, it cannot be unseen
N/A
> (mono) Fix typo in description

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/outdated-report.yml
This commit adds new issue forms that need
to be filled out, as well as adding links to the discussion
page for things we do not want to have issues created directly for.
This pull request adds new issue forms that need to be filled out when creating issues on the repository, as well as links to the discussion page for things we do not want to have issues created for directly.
To make it easier to for maintainers working on the repository to maintain it.
Basic testing on my local fork by setting the default branch to this branch, and creating issues.
EDIT: I have changed my own fork so the issue forms can be tested out. It can be tested by creating a new issue here: https://github.com/AdmiringWorm/chocolatey-coreteampackages/issues (issues will be disabled on that repository when …
> (#1754) Add issue forms to use

- automatic/ruby.portable/README.md
- automatic/ruby.portable/legal/LICENSE.txt
- automatic/ruby.portable/legal/VERIFICATION.txt
- automatic/ruby.portable/ruby.portable.nuspec
- automatic/ruby.portable/tools/chocolateyInstall.ps1
- automatic/ruby.portable/update.ps1
This migrates in ruby.portable. 
The metadata is updated in accordance with the ruby package's metadata, the package is switched to embedded, and the install script code style is updated.
An AU script is also added, 
Part of #1757 
Should not be merged until #1786 is merged
Ran `update.ps1` to validate that it creates packages for the various minor releases (2.4 and newer).
Installed and uninstalled packages in test env to validate that they work.
- [Original Repository](https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/ruby.portable)
- [Open Issues](https://github.com/ferventcoder/chocolatey-packages/issues) *Add the different issues underneath, and tick those that are fixed in this PR*
> (ruby.portable) Migrate package, update code and metadata, add AU

- automatic/mumble/README.md
I've updated the README.md files for mumble. These should flow into the 'description` in the .nupspec file.
Note that how we add this info, the message and the formatting are all up for debate. I wanted to get something up here for discussion. Once agreed, I feel we should require any updates to a package to add this to the README files (perhaps by adding it to https://github.com/chocolatey-community/chocolatey-packages/issues/1754).
Questions are still being asked via Disqus for many packages. As Disqus is generally not responded to it makes sense to clarify where questions and issues should be raised. Going forward we should add this to all packages.
I haven't tested this as it was an update to Markdown.
N/A.
> (mumble) Clarify where to raise issues / questions

- automatic/wget/README.md
I've updated the README.md file for wget. These should flow into the 'description` in the .nupspec file.
Questions are still being asked via Disqus for many packages. As Disqus is generally not responded to it makes sense to clarify where questions and issues should be raised. Going forward we should add this to all packages.
I haven't tested this as it was an update to Markdown.
N/A.
> (wget) Clarify where to raise issues / questions

- automatic/keepassxc/keepassxc.nuspec
- automatic/keepassxc/legal/VERIFICATION.txt
- automatic/keepassxc/tools/chocolateyInstall.ps1
- automatic/keepassxc/update.ps1
Removes all code used for the 32-bit installer of KeePassXC as it isn't supported anymore.
Fixes #1829 
I updated the package with the update.ps1 script and successfully installed/uninstalled it afterwards.
> (keepassxc) remove 32-bit support

- .github/ISSUE_TEMPLATE/bug-report.yml
Updates the list of Chocolatey CLI versions in the bug report issue form.
There have been multiple versions of Chocolatey CLI released since this issue form was updated.
N/A
N/A
N/A
> Update issue form with current Chocolatey CLI versions.

- automatic/vlc.install/tools/chocolateyInstall.ps1
- automatic/vlc.install/update.ps1
> (vlc) Fix 32-bit install on 64-bit, 64-bit install on 32-bit platforms

- automatic/git.install/tools/helpers.ps1
> (git.install) GH-1867: powershell 2 compatibility

- automatic/freecad/README.md
@gep13
This is to resolve the issue #1872 experienced by many users of the FreeCAD package. @pauby was instrumental in making this PR possible. Many _Thanks_ for their _guidance_ and _patience_ in getting to this point.
> (freecad) Update to Readme due to error upon install over previous install

- .github/CODEOWNERS
- automatic/es/README.md
- automatic/es/es.nuspec
- automatic/es/legal/License.txt
- automatic/es/legal/VERIFICATION.txt
- automatic/es/tools/chocolateyInstall.ps1
- automatic/es/update.ps1
This PR creates the Everything Command Line package. AU script included.
Part of #1705
I named the package `es`, since that it what the software is called by the vendor. 
I am adding this package here since the `everything` package is also maintained here. I'd also be fine with maintaining it in my chocolatey-packages repository. 
Once this package is approved on the Community Repository, then the `everything` package can be updated to remove es.exe
`update.ps1` tested locally.
Passed install and uninstall in the test environment.
N/A
> (es) Add everything command line (es) package

- manual/sauerbraten/tools/chocolateyInstall.ps1
> Update sauerbraten to 2020 version

- automatic/freecad/update_helper.ps1
@gep13 @AdmiringWorm @TheCakeIsNaOH 
This will address the issue #1922 and make the script future proof. It is meant to make the package up and working for the community.
> (freecad) Rewrite to address issue 1922

- automatic/apache-httpd/apache-httpd.nuspec
- automatic/apache-httpd/readme.md
- automatic/apache-httpd/tools/chocolateyInstall.ps1
- automatic/apache-httpd/update.ps1
Update the regex to use vs17 rather than vc15, vc15 is no longer provided.
There is a security issue in both apache-httpd 2.4.53 and the first provided version of apache-httpd 2.4.54. There is a newer openssl out recently that mitigates known security issues. No package was automatically added due to lack of a matching regex.
> (apache-httpd) Update to use vs17 for binaries, vc15 are no longer provided.

- automatic/kubernetes-cli/update.ps1
Update `kubernetes-cli` to the latest supported versions.
See https://github.com/chocolatey-community/chocolatey-packages/discussions/1901#discussioncomment-3082957
I've tested (un)installing in my machine.
> (kubernetes-cli) Update to the latest supported versions

- CONTRIBUTING.md
- automatic/calibre/Readme.md
- automatic/calibre/legal/VERIFICATION.txt
- automatic/calibre/tools/chocolateyInstall.ps1
- automatic/calibre/update.ps1
Update AU script for 6.x releases
calibre 6 is released but the auto update script can only fetch version 5 releases. This pull request updates the script for calibre 6, I also delete the 32bit code since calibre 6 is 64bit only.
The AppVeyor tests are passed. I don't use Windows so I didn't test on my machine...
> Update calibre from 5.44.0 to 6.0.0

- .github/CODEOWNERS
- automatic/freecad/update_helper.ps1
@gep13 @AdmiringWorm @luzpaz @adrianinsaval
This will fix the package from trying to push as a embedded package as it is **not** an embedded package. It happened because  I forgot to update for removing the `zip` files. This will also allow for direct updating of the dev minor version as a separate variable from the update script. This will only be needed if the update helper logic fails.
This will fix issue #1941
Intranet and appveyor
> (freecad) Updated to remove files and dev version issues {Take 2}

- automatic/freecad/update.ps1
- automatic/freecad/update_helper.ps1
@AdmiringWorm 
I forgot to update the file name to make the package active again ☹️ 
This will help that and is updated to take care of files not being removed before packing.
> (freecad) Update name to make the package active

- automatic/audacity/audacity.nuspec
Update the documentation URL so that the automated tests pass and users can install newer versions. Fixes #1996.
Upstream changed their docs location
n/a
> (audacity) Update docs url

- automatic/vlc/vlc.nuspec
This changeset removes `(Install)` from the `vlc` package's `title` value.
Fixes #1939.
`vlc` was historically an unlabeled installer package, but as of [v3.0.17.4](https://community.chocolatey.org/packages/vlc/3.0.17.4), was converted to a metapackage, with the installer-related functionality forked to `vlc.install`. The modified title was likely [accidentally introduced](https://github.com/chocolatey-community/chocolatey-packages/commit/2013aac73cb4802b83c3ab06ca16c5e402ccb36f#diff-d865bca7c0a62436cc66079a7edf8f745f5c2208d727e8644b11fc0a1e1cc186R6) during the conversion process.
`choco pack`ed against the modified Nuspec file in my environment:
- **Operating System Version:** Microsoft Windows NT 10.0.22000.0
- **OS Edition:** Windows 11 Pro
- **OS Architecture:** 64-bit
- **PowerShell …
> (vlc) Remove incorrect package type indicator from metapackage title

- automatic/freecad/tools/chocolateyInstall.ps1
- automatic/freecad/update_helper.ps1
@gep13  @AdmiringWorm 
This is to make the package update with the merge of #2007 that fixes the GitHub Update to release assets bug. This will also fix the package install of the portable package so to pass moderation.
> (freecad) Update to use new script and portable package update

- automatic/minikube/update.ps1
update to new github style and rebase
Github changes break the update
fixes https://github.com/chocolatey-community/chocolatey-packages/issues/1994
Powershell locally
> (minikube) update to new github style

- automatic/git.install/ARGUMENTS.md
- automatic/git.install/README.md
- automatic/git/README.md
Updated the command examples to be correct (were missing end quotes) and to follow best practice (start `"'` and end `'"`)
Typos and following best practice.
N/A
N/A
> (git git.install) Command example follow best practice

- automatic/virtualbox/Readme.md
Fix typo in virtual;box package - INCURE to INCUR.
Typo.
N/A 
N/A
> (virtualbox) Fix typo

- automatic/dropbox/tools/chocolateyinstall.ps1
- automatic/dropbox/update.ps1
@gep13 @AdmiringWorm @majkinetor 
This will update this package to install 64 bit versions that dropbox has now made available.
This was requested in issue #2004 
Appveyor and local intranet
> (dropbox) Update for 64 bit install inclusion

- automatic/gobby/update.ps1
This pull request updates the updater to make use of the new script to grab the latest release.
Additonally, I have also changed to include the actual release notes in the package.
To have the updater fixed.
1. Run `.\update_all.ps1 gobby -ForcedPackages gobby`
> (gobby) Fix updater for gobby

- automatic/lightscreen/update.ps1
This pull request fixes the updater for the lightscreen package by changing the updater to make use of the new github helper to acquire the release.
To have a working package updater
1. Ran `.\update_all.ps1 lightscreen -ForcedPackages lightscreen`
> (lightscreen) Fix the update script

- automatic/speccy/update.ps1
Amended the regex that detects the version.
I also refactored some code to make it easier to maintain (at least for me). This is in a separate commit that can be removed if necessary.
Fixes #2038
Package was not picking up new version.
Ran the update script and it picked up the new version as expected.
> (speccy) Fix version detection

- CONTRIBUTING.md
- Fix typos, orthography, and grammar to improve readability.
- Clarify the syntax of the `tags` tag as it was ambiguous.
I thought, all the tags needed to be separated by hyphens (`-`). Instead, tags needed to be separated by spaces (` `), and only multi-word tags are kept together with hyphens.
- ~My change requires a change to documentation (this usually means the notes in the description of a package).~
- ~I have updated the documentation accordingly (this usually means the notes in the description of a package).~
- ~I have updated the package description and it is less than 4000 characters.~
- ~The added/modified package passed install/uninstall in the chocolatey test environment.]~
- ~The changes only affect a single package (not including meta package).~
> Fix typos, orthography, grammer, and clarify the syntax of the `tags` tag

- automatic/brackets/README.md
This pull request adds information for the brackets package about where users may open up issues when they experiences issues with the package, as well as where they can ask any questions about the package.
Questions are asked in Disqus that goes unanswered, and when people have problems with the package they are sending emails which we usually don't want.
N/A
> (brackets) Add notes about problems with the package

- automatic/autohotkey.install/tools/VERIFICATION.txt
- automatic/autohotkey.portable/tools/VERIFICATION.txt
The previous link does no longer exist. The contents are the same.
...
...
...
> (autohotkey) Change License URL

- automatic/k9s/tools/chocolateyinstall.ps1
- automatic/k9s/update.ps1
New releases are now in zip format instead of tar.gz, this is to update that
Releases can now be pulled properly
It is only a zip, so not necessary to locally test it.
> (k9s) download zip instead of tar.gz

- .github/CODEOWNERS
Define code owner for Azure Data Studio and Visual Studio Code extensions
Make sure correct reviewer is automatically assigned
N/A
> Set code owners for extensions

- automatic/webstorm/tools/ChocolateyInstall.ps1
- automatic/webstorm/tools/ChocolateyUnInstall.ps1
Fixes the uninstall for Webstorm and closes https://github.com/chocolatey-community/chocolatey-packages/issues/2208
The uninstall registry key for Webstorm changed at some point from starting with JetBrains Webstorm to just Webstorm. 
* Installed Webstorm (choco install -y webstorm)
* Uninstalled Webstorm (choco uninstall -y webstorm) and saw it not find the registry uninstall key in the log and Chocolatey launched the Webstorm uninstall UI so I manually uninstall Webstorm
* Updated uninstall script software name to Webstorm *
* Ran choco pack to create new version of package
* Ran choco install -y webstorm --debug --verbose --source . 
* Ran choco uninstall -y webstorm --debug --verbose --source . and this time saw that it found the uninstall key and silently uninstalled Webstorm
> (webstorm) fix: webstorm uninstall script

- automatic/brave/update.ps1
This is currently broken as https://brave-browser-downloads.s3.brave.com/latest/release.version is now moved to https://brave-browser-downloads.s3.brave.com/latest/release-windows-x64.version. Same for beta.
> (brave) Update version endpoint

- automatic/inkscape/README.md
Added a note about reinstallation not working.
Issue #2157 highlighted this issue and we need to make it clear.
Fixes #2157 
This is just a README change.
> (inkscape) Add note about reinstalling

- automatic/autohotkey.portable/README.md
**When this PR is merged, please push a new 2.0.3 version of the `autohotkey.portable` package.**
Add a Notes section to the description confirming where to find information on AV false positives and where to ask questions or raise issues for the package.
The latest 2.0.3 version of `autohotkey.portable` has 6 AV detections, and we need to add an official explanation to the description.
This is just a change to the markdown / package description.
> (autohotkey.portable) Add note about AV false positives and where to ask questions

- automatic/jenkins/jenkins.nuspec
- automatic/jenkins/update.ps1
The change proposed updates the bug tracker URL, adds a mailing list URL, changes the changelog URL from weekly to the LTS changelog and uses a non-deprecated download URL.
Current changes are either wrong or incomplete, this PR aims to fix them.
Tested locally.
> (jenkins) Update changelog, bugtracker, mailing list and download URL

- automatic/kubelogin/tools/chocolateyInstall.ps1
- automatic/kubelogin/tools/chocolateyUninstall.ps1
Added shim using the naming convention as expected by the kubectl plugin system
#2282 
Locally
> (kubelogin) Added shim with expected name

- automatic/diskdefragtouch/README.md
- automatic/diskdefragtouch/diskdefragtouch.nuspec
- automatic/kingsoft-office-free/README.md
- automatic/pspp/Readme.md
- automatic/pspp/pspp.nuspec
- automatic/sidesync/README.md
- automatic/sidesync/sidesync.nuspec
- automatic/speccy/README.md
- automatic/speccy/speccy.nuspec
- automatic/tor-browser/tools/chocolateyInstall.ps1
- manual/assaultcube/assaultcube.nuspec
- manual/tipp10/README.md
- manual/virtualdub/README.md
I noticed [an encoding issue in `tools\chocolateyInstall.ps1`](https://github.com/chocolatey-community/chocolatey-packages/blob/e1e5f11fee93dcdf29f7d7486aea70077bdecc40/automatic/tor-browser/tools/chocolateyInstall.ps1#L21) of [`tor-browser`](https://community.chocolatey.org/packages/tor-browser), so I found and solved other similar issues thanks to the Python script given in the first commit description.
Except:
- https://github.com/chocolatey-community/chocolatey-packages/commit/ee1d11b172235e1a947a46e6dc6de27ba0574cfb#diff-aae96f15f0ec487d0ff4b45ad768a1c36c8378749fe23d9e2f5e690168a285f4L2-R2
- https://github.com/chocolatey-community/chocolatey-packages/commit/5fef977571d5ba5c5c2259392fc4b644ce677f6b
I am sure of my method.
> (multiple) Correct `cp1252` encoding in `utf-8`

- README.md
Added a note on unlikely acceptance of new or migrated packages. Made clear that the maintenance team is primarily the Chocolatey Team in their spare time. Cleaned up some typos and text.
To make it clearer.
Just an update to the README.
N/A
> (doc) Document accepting new / migrated packages and maintenance team

- automatic/ruby.install/ruby.install.nuspec
- automatic/ruby.install/tools/chocolateyInstall.ps1
- automatic/ruby.portable/ruby.portable.nuspec
- automatic/ruby/ruby.nuspec
As discussed with @AdmiringWorm in https://github.com/chocolatey-community/chocolatey-packages/issues/2260#issuecomment-1878142315 - attempts to workaround the failing `ProjectSourceUrl` checks in automation for all Ruby packages on the assumption that the old URLs are now being blocked on `git.ruby-lang.org` for some reason (`The ProjectSourceUrl element in the nuspec file should be a valid Url`).
Also corrects silent install for RubyInstaller packages.
- Fixes #2260 
All new Ruby versions are stuck in validation right now due to `ProjectSourceUrl` (also affects portable install).
_Edited:_
There are also historical issues going back to `3.2.0` with RubyInstaller due to the installer now adding a `/allusers` vs `/currentuser` option which must be chosen even for silent installs, which …
> (ruby*) Correct package verification failures

- .appveyor.yml
- scripts/Update-IconUrl.ps1
- scripts/Update-PackageSourceUrl.ps1
Recently a extension package that extends the validation rules used in Chocolatey CLI was introduced, as such we should start making use of this package when updating packages to be pushed to the Chocolatey Community Repository.
We should go forward as an example of what do use, and ensure that we attempt to not push packages that will error out on the Package Validator when possible.
1. Install the chocolatey-community-validation.extension package (currently not approved, and requires specifiying version 0.1.0).
2. Run the update_all script using a specific package (might want to add the same package as a forced package).
3. Verify that it either succeeded, or exited with an exit code of 1 (more information would be in one of the build artifacts).
> (maint) Add Chocolatey Community Validation Extension to build script

- automatic/musescore/legal/LICENSE.txt
- automatic/musescore/legal/VERIFICATION.txt
- automatic/musescore/musescore.nuspec
Updates `licenseUrl` based on upstream rename https://github.com/musescore/MuseScore/commit/56cb92e0beb5d2eeedf4546c45db15f57688ea6f
Fixes #2411 
Went to link in browser, and tested package.
> (musescore) Update licenseUrl

- automatic/mkdocs-material/update.ps1
Fixes the update script to account for compatible version dependency in requirements.txt
https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers
Fixes #2408
Update script ran on Windows 10, package tested in Chocolatey test env.
> (mkdocs-material) Add case for dependency versioning change

- automatic/graphviz/graphviz.nuspec
Update URL to upstream changelog file. The graphviz repo's default branch has been renamed from `master` to `main `.
Prevents 404 when following link under "Release Notes" on Chocolatey website.
> (graphviz) Update changelog URL in graphviz.nuspec

- automatic/blender/blender.nuspec
Updates the packageSourceUrl to the new source repository location.
Fixes #2391
N/A, as documentation change only.
> (blender) update projectSourceUrl

- automatic/wixtoolset/wixtoolset.nuspec
This PR fixes multiple invalid URLs in the nuspec, as mentioned in the [valdation report](https://community.chocolatey.org/packages/wixtoolset/3.14.0)
Validation should be expedited, because v3.14.0 is actually a security related release.
N/A
> (wixtoolset) Fix validation issues

- automatic/rdcman/rdcman.nuspec
This updates the nuspec file to include the section that controls what files should be included or not.
We do not want to embedd files that shouldn't be embedded into the package that gets created.
fixes #2430 
1. Run `.\update_all.ps1 rdcman -ForcedPackages rdcman`
2. Wait for the updater to finish
3. Find the newly created `nupkg` file in the rdcman folder
4. Open or extract the contents of the package file.
5. Verify no unexpected files were included in the creation of it.
> (rdcman) Add missing files section

- automatic/es/legal/VERIFICATION.txt
- automatic/es/tools/chocolateyInstall.ps1
- automatic/es/update.ps1
The filename as changed, so the regex isn't working anymore.
I've updated it to work again.
Regex wasn't working anymore
> (es) New regex

- .appveyor.yml
- .github/ISSUE_TEMPLATE/bug-report.yml
- Add 2.4.0 as a valid chocolatey CLI version to the issue template
- Updated .appveyor.yml
new CLI version released
N/A
> (maint) Updates for Chocolatey CLI 2.4.0 release

- automatic/vlc/vlc.nuspec
Filter files to embed only the nuspec
Useless files embedded, including update.ps1
on my update git
Issue : https://github.com/chocolatey-community/chocolatey-packages/issues/2580
> (vlc) Dont embed useless files

- automatic/mattermost-desktop/tools/chocolateyInstall.ps1
Add silentArg ALLUSERS=1 for package mattermost-desktop
If silentArg ALLUSERS=1 is not set the package is installed as user only
Only tested via installing the msi manually
> (mattermost-desktop) Add silentArg ALLUSERS=1

- automatic/cmake.install/Readme.md
- automatic/cmake.install/tools/chocolateyInstall.ps1
- automatic/cmake/Readme.md
Update Readme and install script to current cmake defaults.
The installer automatically adds cmake to the PATH starting with [version 3.0.30](https://cmake.org/cmake/help/latest/release/3.30.html#:~:text=The%20precompiled%20Windows%20.msi%20installers%20provided%20on%20cmake.org%2C%20when%20performing%20a%20fresh%20installation%2C%20now%20modify%20the%20system%2Dwide%20PATH%20by%20default.%20When%20replacing%20an%20existing%20installation%20of%203.30%20or%20later%2C%20the%20PATH%20modification%20preference%20is%20preserved%20by%20default.). Also the [respective installer argument](https://gitlab.kitware.com/cmake/cmake/-/blob/66a33b6663e954deed4d64af40038dccee0947a5/Utilities/Release/WiX/options.wxs#L19-26) takes the values `0` and `1` (legacy values are still supported though).
See …
> (cmake)(cmake.install) Update note for PATH to new defaults

- manual/lockhunter/lockhunter.nuspec
- manual/lockhunter/tools/chocolateyInstall.ps1
Lockhunter's installer has changed again in-place, so the hash needs to be updated. This has happened before multiple times, see eg. https://github.com/chocolatey-community/chocolatey-packages/pull/2228
Executing `choco install lockhunter` results in the following failure:
```
Download of lockhuntersetup_3-4-3.exe (3.22 MB) completed.
Error - hashes do not match. Actual value was '02F738111A7EF929B8017277109FF3CB188ED0896FA385B79205DA888AFA266D'.
ERROR: Checksum for 'C:\Users\petamas\AppData\Local\Temp\chocolatey\lockhunter\3.4.3.20220526\lockhuntersetup_3-4-3.exe' did not meet '982dda5eec52dd54ff6b0b04fd9ba8f4c566534b78f6a46dada624af0316044e' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are …
```
> (lockhunter) Update checksum and version

- automatic/audacity/update.ps1
This commit converts the update script to use it for sourcing the version _and_ the download URLs.
The audacity package has failed the last 20+ builds with "Unable to connect to the remote server". As it seems to work on my local machine, I suspect the AudacityTeam.org site is blocking our automation.
We were already ending up with the download URLs from the GitHub release page, so this change seems like it improves the simplicity of the update logic and should (hopefully) fix the failing updates.
- `.\update_all.ps1 -Name audacity -ForcedPackages audacity`  # Note: the package isn't currently outdated, just failing the build.
- Installed on my local test system
`choco install audacity --confirm --version 3.7.4.20250703`
- Uninstalled on my local test system
`choco uninstall audacity …
> (audacity) Changes Update Logic to use GitHub Releases

- automatic/php/php.nuspec
This PR adds a note to the PHP package description regarding known false positives triggered by VirusTotal scans of deplister.exe, a diagnostic utility included in Windows builds of PHP. The issue has been confirmed and does not indicate a security risk. For more info see https://github.com/php/php-src/issues/14875.
Newer versions of the PHP package are being held in the moderation queue with higher than normal Virus Detections, and in order to be able to be exempted from Virus Scanning, this additional information needs to be in the description of the package.
This is a simple addition to the description, and doesn't need any further testing.
N/A
> (php) Document known false positives for deplister.exe in PHP package description

- COMMITTERS.md
document how manual packages are updated and pushed.
It isn't documented and maintainers need to know how to do it.
I did this task this morning and it worked as expected. This is just documenting it.
N/A
> (doc) Document updating manual packages

- automatic/sqlite/update.ps1
- Parse the commented CSV embedded in SQLite download page HTML to discover artifacts
- Add Get-SqliteWindowsDownload to convert CSV to objects, filter Windows-only artifacts, extract artifact type and arch, and group by VERSION
- Replace fragile link-scraping and URL existence checks with CSV parsing and structured grouping
- Validate exactly one version present and select DLL (x86/x64) and tools (x64) URLs
- Make artifact discovery reliable against changes to the release page layout
- Fix missing artifact selection for SQLite releases by using the authoritative CSV block
- Simplify and harden downstream update logic
- Tested by calling `.\update_all.ps1 "sqlite*"`
> (sqlite) Parse SQLite download CSV and select Windows artifacts
